'use strict';

const HEALTH_TICK_MS = Math.max(60_000, Number(process.env.GOLIATH_HEALTH_TICK_MS || 60_000));
const DEEP_SCAN_MS = Math.max(300_000, Number(process.env.GOLIATH_HEALTH_DEEP_SCAN_MS || 300_000));
const HEARTBEAT_STALE_MS = Math.max(180_000, Number(process.env.GOLIATH_HEALTH_HEARTBEAT_STALE_MS || 300_000));
const SOCIAL_STALE_MULTIPLIER = Math.max(2, Number(process.env.GOLIATH_HEALTH_SOCIAL_STALE_MULTIPLIER || 3));
const SOCIAL_MIN_STALE_MS = Math.max(180_000, Number(process.env.GOLIATH_HEALTH_SOCIAL_MIN_STALE_MS || 300_000));
const INCIDENT_REMINDER_EVERY = Math.max(10, Number(process.env.GOLIATH_HEALTH_INCIDENT_REMINDER_EVERY || 25));
const REPORT_HOUR_UTC = Math.min(23, Math.max(0, Number(process.env.GOLIATH_HEALTH_REPORT_HOUR_UTC || 8)));

module.exports = { HEALTH_TICK_MS, DEEP_SCAN_MS, HEARTBEAT_STALE_MS, SOCIAL_STALE_MULTIPLIER, SOCIAL_MIN_STALE_MS, INCIDENT_REMINDER_EVERY, REPORT_HOUR_UTC };
