'use strict';

const express = require('express');
const os = require('os');
const fs = require('fs');
const path = require('path');
const { getRuntimeRoot, resolveRuntimePath } = require('../../../config/runtimePaths');

const guildManager = require('../../../core/guild/guildManager');
const serverBackup = require('../../../core/security/restoreBackup/backup');

const router = express.Router();

const ENVIRONMENT_PORTS = [
  { key: 'dev', environment: 'DEV', port: 3001 },
  { key: 'beta', environment: 'BETA', port: 3011 },
  { key: 'production', environment: 'PRODUCTION', port: 3021 },
];

function shouldLogEnvironmentUnavailable() { return process.env.NODE_ENV === 'production'; }
function splitIds(value) { return String(value || '').split(',').map((id) => id.trim()).filter(Boolean); }
function getOwnerIds() { return [...new Set([...splitIds(process.env.OWNER_ID), ...splitIds(process.env.OWNER_IDS), ...splitIds(process.env.BOT_OWNER_ID), ...splitIds(process.env.BOT_OWNER_IDS)])]; }
function isOwnerUser(userId) { if (!userId) return false; return getOwnerIds().includes(String(userId)); }
function isInternalOwnerRequest(req) { const token = String(process.env.OWNER_INTERNAL_TOKEN || '').trim(); if (!token) return false; const headerToken = String(req.headers['x-goliath-owner-token'] || '').trim(); return headerToken === token; }
function requireOwner(req, res, next) { if (!req.session?.user) return res.status(401).json({ success: false, error: 'Not authenticated.' }); if (!isOwnerUser(req.session.user.id)) return res.status(403).json({ success: false, error: 'Forbidden' }); return next(); }
function requireOwnerOrInternal(req, res, next) { if (isInternalOwnerRequest(req)) return next(); return requireOwner(req, res, next); }
function getRuntimeMode() { return String(process.env.BOT_MODE || 'dev').trim().toUpperCase(); }
function getEnvironmentKey(environment = getRuntimeMode()) { const env = String(environment || 'DEV').toUpperCase(); if (env === 'PRODUCTION' || env === 'PROD') return 'production'; if (env === 'BETA') return 'beta'; return 'dev'; }
function getEnvironmentLabel(environment = getRuntimeMode()) { const env = String(environment || 'DEV').toUpperCase(); if (env === 'PRODUCTION' || env === 'PROD') return 'PRODUCTION'; if (env === 'BETA') return 'BETA'; return 'DEV'; }
function getDiscordClient(req) { return req.client || req.app?.get?.('goliath.client') || req.app?.locals?.client || req.app?.locals?.discordClient || global.client || global.discordClient || null; }
function buildGuildIconUrl(guild) { if (!guild?.id || !guild?.icon) return null; const ext = String(guild.icon).startsWith('a_') ? 'gif' : 'png'; return `https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}.${ext}?size=256`; }
function buildOwnerGuildPayload(guild, forcedEnvironment = null) { const mode = forcedEnvironment || getRuntimeMode(); const iconUrl = buildGuildIconUrl(guild); return { id: guild.id, guildId: guild.id, name: guild.name, guildName: guild.name, icon: guild.icon || null, iconUrl, iconURL: iconUrl, environment: mode, runtimeMode: mode, memberCount: Number(guild.memberCount || 0), ownerId: guild.ownerId || null, ownerName: null, botConnected: true, connected: true, status: 'connected' }; }
function normaliseSecurityIncidents(security = {}) { const incidents = Array.isArray(security.incidents) ? security.incidents : []; return incidents.filter(Boolean).map((incident) => ({ ...incident, severity: incident.severity || incident.level || 'info', type: incident.type || incident.eventType || incident.action || 'security_event', timestamp: incident.timestamp || incident.createdAt || incident.time || null })); }
function buildGuildSecurityOverview(guild, environment = getRuntimeMode()) { const guildId = guild.guildId || guild.id; const security = guildManager.getSecurityConfig(guildId) || {}; const incidents = normaliseSecurityIncidents(security); const lockdown = security.lockdown || { active: false }; const quarantine = security.quarantine || { users: {} }; const quarantinedCount = Object.keys(quarantine.users || {}).length; const criticalIncidents = incidents.filter((incident) => String(incident.severity || '').toLowerCase() === 'critical').length; const webhookIncidents = incidents.filter((incident) => String(incident.type || '').toLowerCase().includes('webhook')).length; return { guildId, guildName: guild.guildName || guild.name || 'Unknown Guild', environment, threatLevel: security.threatLevel || 'low', incidentCount: Number(security.totalIncidents || incidents.length || 0), criticalIncidents: Number(security.criticalIncidents || criticalIncidents || 0), webhookIncidents, lockdownActive: Boolean(lockdown.active), quarantinedCount, recentIncidents: incidents.slice(0, 10), updatedAt: new Date().toISOString() }; }
function summariseSecurityGuilds(guildSecurity = []) { const totals = { guilds: guildSecurity.length, incidents: 0, critical: 0, lockdowns: 0, quarantinedUsers: 0, webhookIncidents: 0, protectedGuilds: 0 }; const recentIncidents = []; for (const item of guildSecurity) { totals.incidents += Number(item.incidentCount || 0); totals.critical += Number(item.criticalIncidents || 0); totals.lockdowns += item.lockdownActive ? 1 : 0; totals.quarantinedUsers += Number(item.quarantinedCount || 0); totals.webhookIncidents += Number(item.webhookIncidents || 0); if (item.threatLevel !== 'unknown') totals.protectedGuilds += 1; for (const incident of item.recentIncidents || []) recentIncidents.push({ ...incident, guildId: item.guildId, guildName: item.guildName, environment: item.environment }); } recentIncidents.sort((a, b) => new Date(b.timestamp || 0).getTime() - new Date(a.timestamp || 0).getTime()); return { totals, recentIncidents: recentIncidents.slice(0, 25) }; }
function getPackageInfo() { try { const pkg = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf8')); return { name: pkg.name || 'goliath', version: pkg.version || 'unknown' }; } catch { return { name: 'goliath', version: 'unknown' }; } }
function getGitCommitSha() { return String(process.env.GITHUB_SHA || process.env.COMMIT_SHA || process.env.GIT_COMMIT || '').trim() || null; }
function getBuildTime() { return String(process.env.BUILD_TIME || process.env.BUILD_DATE || process.env.DEPLOYED_AT || '').trim() || null; }
function getRuntimePathsStatus(environment = getRuntimeMode()) { const base = getRuntimeRoot(getEnvironmentKey(environment)); const folders = ['guilds', 'logs', 'backups', 'data', 'cache']; return Object.fromEntries(folders.map((folder) => { const fullPath = path.join(base, folder); return [folder, { path: fullPath, exists: fs.existsSync(fullPath) }]; })); }
function safeReadJson(filePath, fallback = null) { try { if (!filePath || !fs.existsSync(filePath)) return fallback; return JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch { return fallback; } }
function getDirectorySize(dirPath) { if (!dirPath || !fs.existsSync(dirPath)) return 0; let total = 0; const entries = fs.readdirSync(dirPath, { withFileTypes: true }); for (const entry of entries) { const fullPath = path.join(dirPath, entry.name); try { if (entry.isDirectory()) total += getDirectorySize(fullPath); else total += fs.statSync(fullPath).size; } catch {} } return total; }
function formatBytes(bytes = 0) { const value = Number(bytes || 0); if (!Number.isFinite(value) || value <= 0) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); const amount = value / Math.pow(1024, index); return `${amount >= 10 || index === 0 ? amount.toFixed(0) : amount.toFixed(1)} ${units[index]}`; }

function scanBackupFiles(backupsPath, environment = getRuntimeMode()) {
  if (!backupsPath || !fs.existsSync(backupsPath)) return [];
  const results = [];
  const guildFolders = fs.readdirSync(backupsPath, { withFileTypes: true }).filter((entry) => entry.isDirectory());
  for (const guildFolder of guildFolders) {
    const guildId = guildFolder.name;
    const guildRoot = path.join(backupsPath, guildId);
    const typeFolders = fs.readdirSync(guildRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory());
    for (const typeFolder of typeFolders) {
      const backupType = typeFolder.name;
      const typeRoot = path.join(guildRoot, backupType);
      const files = fs.readdirSync(typeRoot, { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.endsWith('.json') && !entry.name.endsWith('.integrity.json'));
      for (const file of files) {
        const filePath = path.join(typeRoot, file.name);
        const backup = safeReadJson(filePath, {});
        const stats = fs.statSync(filePath);
        const integrityPath = `${filePath}.integrity.json`;
        const integrity = safeReadJson(integrityPath, null);
        const validation = (() => { try { return serverBackup.validateServerBackup(backup, { guildId: backup?.guild?.id || guildId, strict: false }); } catch (error) { return { valid: false, safe: false, errors: [error.message], warnings: [], blockers: [error.message] }; } })();
        results.push({ id: backup.backupId || file.name.replace(/\.json$/, ''), backupId: backup.backupId || file.name.replace(/\.json$/, ''), environment, guildId: backup.guild?.id || guildId, guildName: backup.guild?.name || 'Unknown Guild', backupType: backup.backupType || backup.type || backup.metadata?.backupType || backupType, createdAt: backup.createdAt || stats.mtime.toISOString(), createdBy: backup.createdBy || backup.requestedBy || 'system', reason: backup.reason || 'Server backup', path: filePath, sizeBytes: stats.size, sizeLabel: formatBytes(stats.size), roles: Array.isArray(backup.roles) ? backup.roles.length : 0, channels: Array.isArray(backup.channels) ? backup.channels.length : 0, integrity: { exists: Boolean(integrity), verified: Boolean(backup.integrity?.verified || integrity?.integrity?.hash), generatedAt: backup.integrity?.generatedAt || integrity?.integrity?.generatedAt || null, path: integrityPath }, validation: { valid: validation.valid !== false, safe: validation.safe !== false, warnings: Array.isArray(validation.warnings) ? validation.warnings.length : 0, errors: Array.isArray(validation.errors) ? validation.errors.length : 0, blockers: Array.isArray(validation.blockers) ? validation.blockers.length : 0 } });
      }
    }
  }
  return results.sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime());
}

function readRestoreQueue(environment = getRuntimeMode()) { const recoveryRoot = resolveRuntimePath(getEnvironmentKey(environment), 'recovery', 'restoreRequests'); const pending = safeReadJson(path.join(recoveryRoot, 'pending.json'), { requests: [] }); const history = safeReadJson(path.join(recoveryRoot, 'history.json'), { requests: [] }); const audit = safeReadJson(path.join(recoveryRoot, 'audit.json'), { requests: [] }); const pendingRequests = Array.isArray(pending.requests) ? pending.requests : []; const historyRequests = Array.isArray(history.requests) ? history.requests : []; const auditRequests = Array.isArray(audit.requests) ? audit.requests : []; return { path: recoveryRoot, exists: fs.existsSync(recoveryRoot), pending: pendingRequests.slice(0, 25), history: historyRequests.slice(0, 25), audit: auditRequests.slice(0, 25), counts: { pending: pendingRequests.length, history: historyRequests.length, audit: auditRequests.length, failed: historyRequests.filter((request) => String(request.status || '').toLowerCase() === 'failed').length } }; }
function buildBackupOverview(req, forcedEnvironment = getRuntimeMode()) { const environment = getEnvironmentLabel(forcedEnvironment); const runtimePaths = getRuntimePathsStatus(environment); const backupsPath = runtimePaths.backups?.path; const restorePoints = scanBackupFiles(backupsPath, environment); const restoreQueue = readRestoreQueue(environment); const backupSizeBytes = getDirectorySize(backupsPath); const lastBackupAt = restorePoints[0]?.createdAt || null; const failedIntegrity = restorePoints.filter((backup) => !backup.integrity?.exists || backup.validation?.valid === false).length; const warnings = []; if (!runtimePaths.backups?.exists) warnings.push('Backup folder missing'); if (failedIntegrity) warnings.push(`${failedIntegrity} backup integrity/validation issue(s)`); if (restoreQueue.counts.failed) warnings.push(`${restoreQueue.counts.failed} failed restore request(s)`); return { environment, mode: environment, status: getDiscordClient(req)?.isReady?.() ? 'online' : 'degraded', runtimePaths, backups: { path: backupsPath, restorePoints: restorePoints.length, sizeBytes: backupSizeBytes, sizeLabel: formatBytes(backupSizeBytes), lastBackupAt, failedIntegrity, recent: restorePoints.slice(0, 15) }, restoreQueue, services: { backupWorker: 'available', restoreQueue: restoreQueue.exists ? 'available' : 'not_initialised' }, checkedAt: new Date().toISOString(), warnings, warning: warnings[0] || '' }; }
function summariseBackupEnvironments(environments = []) { const totalSizeBytes = environments.reduce((sum, environment) => sum + Number(environment.backups?.sizeBytes || 0), 0); const restorePoints = environments.reduce((sum, environment) => sum + Number(environment.backups?.restorePoints || 0), 0); const restoreQueuePending = environments.reduce((sum, environment) => sum + Number(environment.restoreQueue?.counts?.pending || 0), 0); const failed = environments.reduce((sum, environment) => sum + Number(environment.backups?.failedIntegrity || 0) + Number(environment.restoreQueue?.counts?.failed || 0), 0); const warnings = environments.reduce((sum, environment) => sum + (Array.isArray(environment.warnings) ? environment.warnings.length : environment.warning ? 1 : 0), 0); const lastBackupAt = environments.map((environment) => environment.backups?.lastBackupAt).filter(Boolean).sort((a, b) => new Date(b).getTime() - new Date(a).getTime())[0] || null; return { environments: environments.length, ready: environments.filter((environment) => environment.runtimePaths?.backups?.exists && environment.status !== 'offline').length, restorePoints, totalSizeBytes, totalSizeLabel: formatBytes(totalSizeBytes), restoreQueuePending, failed, warnings, lastBackupAt, health: warnings || failed ? 'attention' : 'healthy' }; }
function buildModuleSummary() { const guildIds = guildManager.getAllGuildIds ? guildManager.getAllGuildIds() : []; const moduleTotals = {}; for (const guildId of guildIds) { const data = guildManager.getGuildData(guildId) || {}; const modules = data.modules || {}; for (const [key, value] of Object.entries(modules)) { if (!moduleTotals[key]) moduleTotals[key] = { key, enabled: 0, disabled: 0, configured: 0 }; moduleTotals[key].configured += 1; if (value && typeof value === 'object' ? value.enabled !== false : value !== false) moduleTotals[key].enabled += 1; else moduleTotals[key].disabled += 1; } } return Object.values(moduleTotals).sort((a, b) => a.key.localeCompare(b.key)); }
function buildRuntimePayload(req, forcedEnvironment = getRuntimeMode()) { const client = getDiscordClient(req); const totalMemory = os.totalmem(); const freeMemory = os.freemem(); const processMemory = process.memoryUsage(); const packageInfo = getPackageInfo(); const guilds = client?.guilds?.cache ? [...client.guilds.cache.values()] : []; const wsPing = Number(client?.ws?.ping || 0); const readyAt = client?.readyAt?.toISOString?.() || null; const uptime = process.uptime(); return { mode: forcedEnvironment, environment: forcedEnvironment, status: client?.isReady?.() ? 'online' : 'degraded', process: { pid: process.pid, uptime, uptimeMs: Math.round(uptime * 1000), nodeVersion: process.version, platform: process.platform, arch: process.arch, cwd: process.cwd(), packageName: packageInfo.name, version: packageInfo.version, commitSha: getGitCommitSha(), buildTime: getBuildTime() }, system: { hostname: os.hostname(), platform: os.platform(), release: os.release(), cpuCount: os.cpus().length, loadAverage: os.loadavg(), uptime: os.uptime(), memory: { total: totalMemory, free: freeMemory, used: totalMemory - freeMemory } }, memory: { total: totalMemory, free: freeMemory, used: totalMemory - freeMemory, process: { rss: processMemory.rss, heapTotal: processMemory.heapTotal, heapUsed: processMemory.heapUsed, external: processMemory.external, arrayBuffers: processMemory.arrayBuffers } }, discord: { ready: Boolean(client?.isReady?.()), userId: client?.user?.id || null, username: client?.user?.tag || client?.user?.username || null, readyAt, wsStatus: client?.ws?.status ?? null, wsPing, guildCount: guilds.length, memberCount: guilds.reduce((sum, guild) => sum + Number(guild.memberCount || 0), 0) }, services: { dashboardApi: 'online', discordGateway: client?.isReady?.() ? 'online' : 'offline', guildJson: 'online', backupWorker: 'available', socketHub: 'available' }, runtimePaths: getRuntimePathsStatus(forcedEnvironment), modules: buildModuleSummary(), checkedAt: new Date().toISOString() }; }
function summariseRuntimeEnvironments(environments = []) { return { total: environments.length, online: environments.filter((env) => env.status === 'online').length, degraded: environments.filter((env) => env.status === 'degraded').length, offline: environments.filter((env) => env.status === 'offline').length, guilds: environments.reduce((sum, env) => sum + Number(env.discord?.guildCount || 0), 0), members: environments.reduce((sum, env) => sum + Number(env.discord?.memberCount || 0), 0) }; }

async function fetchInternalJson(port, route, fallback, logLabel, environment, options = {}) { try { const token = String(process.env.OWNER_INTERNAL_TOKEN || '').trim(); const response = await fetch(`http://127.0.0.1:${port}${route}`, { method: options.method || 'GET', headers: { 'Content-Type': 'application/json', 'x-goliath-owner-token': token }, body: options.body ? JSON.stringify(options.body) : undefined }); if (!response.ok) { if (options.returnOffline) return { environment, mode: environment, status: 'offline', port, error: `HTTP ${response.status}` }; console.warn(`[${logLabel}] ${environment} returned ${response.status}`); return fallback; } return response.json(); } catch (error) { if (shouldLogEnvironmentUnavailable()) console.warn(`[${logLabel}] ${environment} unavailable on port ${port}:`, error.message); if (options.returnOffline) return { environment, mode: environment, status: 'offline', port, error: error.message }; return fallback; } }
async function fetchEnvironmentGuilds(port, environment) { const payload = await fetchInternalJson(port, '/api/owner/guilds', { guilds: [] }, 'OWNER GUILDS ALL', environment); const guilds = Array.isArray(payload.guilds) ? payload.guilds : []; return guilds.map((guild) => ({ ...guild, environment, runtimeMode: environment, sourcePort: port })); }
async function fetchEnvironmentSecurity(port, environment) { const payload = await fetchInternalJson(port, '/api/owner/security', { guilds: [] }, 'OWNER SECURITY ALL', environment); const guilds = Array.isArray(payload.guilds) ? payload.guilds : []; return guilds.map((guild) => ({ ...guild, environment, runtimeMode: environment, sourcePort: port })); }
async function fetchEnvironmentRuntime(port, environment) { const payload = await fetchInternalJson(port, '/api/owner/runtime/local', null, 'OWNER RUNTIME ALL', environment, { returnOffline: true }); if (payload?.status === 'offline') return payload; return { ...(payload.runtime || {}), environment, mode: environment, port, sourcePort: port }; }
async function fetchEnvironmentBackups(port, environment) { const payload = await fetchInternalJson(port, '/api/owner/backups/local', null, 'OWNER BACKUPS ALL', environment, { returnOffline: true }); if (payload?.status === 'offline') return { environment, mode: environment, status: 'offline', sourcePort: port, port, runtimePaths: getRuntimePathsStatus(environment), backups: { restorePoints: 0, sizeBytes: 0, sizeLabel: '0 B', recent: [], failedIntegrity: 0 }, restoreQueue: { pending: [], history: [], audit: [], counts: { pending: 0, history: 0, audit: 0, failed: 0 } }, warnings: [payload.error || 'Environment unavailable'], warning: payload.error || 'Environment unavailable', checkedAt: new Date().toISOString() }; return { ...(payload.environment || payload), environment, mode: environment, sourcePort: port, port }; }
async function proxyManualBackup(port, environment, body) { return fetchInternalJson(port, '/api/owner/backups/manual/local', null, 'OWNER MANUAL BACKUP', environment, { method: 'POST', body, returnOffline: true }); }

router.get('/me', requireOwner, (req, res) => res.json({ success: true, owner: true, user: req.session.user, mode: getRuntimeMode() }));
router.get('/guilds', requireOwnerOrInternal, (req, res) => { const client = getDiscordClient(req); const mode = getRuntimeMode(); if (!client?.guilds?.cache) return res.status(503).json({ success: false, error: 'Discord client unavailable.' }); const guilds = [...client.guilds.cache.values()].map((guild) => buildOwnerGuildPayload(guild, mode)).sort((a, b) => a.name.localeCompare(b.name)); const byEnvironment = { dev: mode === 'DEV' ? guilds : [], beta: mode === 'BETA' ? guilds : [], production: mode === 'PRODUCTION' ? guilds : [] }; return res.json({ success: true, owner: true, mode, runtimeMode: mode, guilds, ...byEnvironment }); });
router.get('/guilds/all', requireOwnerOrInternal, async (req, res) => { try { const results = await Promise.all(ENVIRONMENT_PORTS.map((environmentConfig) => fetchEnvironmentGuilds(environmentConfig.port, environmentConfig.environment))); const devGuilds = results[0] || []; const betaGuilds = results[1] || []; const productionGuilds = results[2] || []; const guilds = [...devGuilds, ...betaGuilds, ...productionGuilds].sort((a, b) => { const environmentOrder = { DEV: 1, BETA: 2, PRODUCTION: 3 }; const environmentCompare = (environmentOrder[a.environment] || 99) - (environmentOrder[b.environment] || 99); if (environmentCompare !== 0) return environmentCompare; return String(a.name || '').localeCompare(String(b.name || '')); }); return res.json({ success: true, owner: true, mode: 'GLOBAL', runtimeMode: 'GLOBAL', guilds, dev: devGuilds, beta: betaGuilds, production: productionGuilds, environments: { dev: { port: 3001, guilds: devGuilds.length }, beta: { port: 3011, guilds: betaGuilds.length }, production: { port: 3021, guilds: productionGuilds.length } } }); } catch (error) { console.error('[OWNER GUILDS ALL]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.get('/security', requireOwnerOrInternal, (req, res) => { const client = getDiscordClient(req); const mode = getRuntimeMode(); if (!client?.guilds?.cache) return res.status(503).json({ success: false, error: 'Discord client unavailable.' }); const guilds = [...client.guilds.cache.values()].map((guild) => buildGuildSecurityOverview(buildOwnerGuildPayload(guild, mode), mode)).sort((a, b) => String(a.guildName || '').localeCompare(String(b.guildName || ''))); const summary = summariseSecurityGuilds(guilds); return res.json({ success: true, owner: true, mode, runtimeMode: mode, guilds, ...summary, updatedAt: new Date().toISOString() }); });
router.get('/security/all', requireOwner, async (req, res) => { try { const requestedEnvironment = String(req.query.environment || 'all').toUpperCase(); const results = await Promise.all(ENVIRONMENT_PORTS.map((environmentConfig) => fetchEnvironmentSecurity(environmentConfig.port, environmentConfig.environment))); let guilds = [...(results[0] || []), ...(results[1] || []), ...(results[2] || [])]; if (requestedEnvironment !== 'ALL') guilds = guilds.filter((guild) => String(guild.environment || '').toUpperCase() === requestedEnvironment); const summary = summariseSecurityGuilds(guilds); return res.json({ success: true, owner: true, mode: 'GLOBAL', runtimeMode: 'GLOBAL', environment: requestedEnvironment, guilds, ...summary, updatedAt: new Date().toISOString() }); } catch (error) { console.error('[OWNER SECURITY ALL]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.get('/backups/local', requireOwnerOrInternal, (req, res) => { try { const environment = buildBackupOverview(req, getRuntimeMode()); return res.json({ success: true, owner: true, mode: environment.environment, runtimeMode: environment.environment, environment, environments: [environment], summary: summariseBackupEnvironments([environment]), updatedAt: new Date().toISOString() }); } catch (error) { console.error('[OWNER BACKUPS LOCAL]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.get('/backups', requireOwner, async (req, res) => { try { const requestedEnvironment = String(req.query.environment || 'all').toUpperCase(); let environments = await Promise.all(ENVIRONMENT_PORTS.map((environmentConfig) => fetchEnvironmentBackups(environmentConfig.port, environmentConfig.environment))); if (requestedEnvironment !== 'ALL') environments = environments.filter((environment) => String(environment.environment || '').toUpperCase() === requestedEnvironment); return res.json({ success: true, owner: true, mode: 'GLOBAL', runtimeMode: 'GLOBAL', environment: requestedEnvironment, environments, summary: summariseBackupEnvironments(environments), updatedAt: new Date().toISOString() }); } catch (error) { console.error('[OWNER BACKUPS]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.post('/backups/manual/local', requireOwnerOrInternal, async (req, res) => { try { const client = getDiscordClient(req); const guildId = String(req.body?.guildId || '').trim(); const reason = String(req.body?.reason || 'Manual owner backup').trim(); if (!client?.guilds?.cache) return res.status(503).json({ success: false, error: 'Discord client unavailable.' }); if (!guildId) return res.status(400).json({ success: false, error: 'guildId is required.' }); const guild = client.guilds.cache.get(guildId) || await client.guilds.fetch(guildId).catch(() => null); if (!guild) return res.status(404).json({ success: false, error: 'Guild not found in this runtime.' }); const backup = await serverBackup.createServerBackup(guild, { type: 'runtime', requestedBy: req.session?.user?.id || 'owner-internal', createdBy: req.session?.user?.id || 'owner-internal', reason }); return res.json({ success: true, owner: true, environment: getRuntimeMode(), backup: { backupId: backup.backupId, backupType: backup.backupType || backup.type || 'runtime', guildId: backup.guild?.id || guild.id, guildName: backup.guild?.name || guild.name, createdAt: backup.createdAt, createdBy: backup.createdBy || null, reason: backup.reason, path: backup.filePath || backup.file || backup.path || null, roles: backup.roles?.length || 0, channels: backup.channels?.length || 0, integrity: backup.integrity || null }, overview: buildBackupOverview(req, getRuntimeMode()), updatedAt: new Date().toISOString() }); } catch (error) { console.error('[OWNER MANUAL BACKUP LOCAL]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.post('/backups/manual', requireOwner, async (req, res) => { try { const targetEnvironment = getEnvironmentLabel(req.body?.environment || getRuntimeMode()); const target = ENVIRONMENT_PORTS.find((item) => item.environment === targetEnvironment); if (!target) return res.status(400).json({ success: false, error: 'Invalid environment.' }); const payload = await proxyManualBackup(target.port, target.environment, { guildId: req.body?.guildId, reason: req.body?.reason || 'Manual owner backup' }); if (payload?.status === 'offline') return res.status(503).json({ success: false, error: payload.error || `${target.environment} is unavailable.` }); return res.json(payload); } catch (error) { console.error('[OWNER MANUAL BACKUP]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.get('/runtime/local', requireOwnerOrInternal, async (req, res) => { try { return res.json({ success: true, owner: true, runtime: buildRuntimePayload(req, getRuntimeMode()) }); } catch (error) { console.error('[OWNER RUNTIME LOCAL]', error); return res.status(500).json({ success: false, error: error.message }); } });
router.get('/runtime', requireOwner, async (req, res) => { try { const environments = await Promise.all(ENVIRONMENT_PORTS.map((environmentConfig) => fetchEnvironmentRuntime(environmentConfig.port, environmentConfig.environment))); const current = buildRuntimePayload(req, getRuntimeMode()); return res.json({ success: true, owner: true, mode: 'GLOBAL', runtimeMode: 'GLOBAL', runtime: { ...current, environments, summary: summariseRuntimeEnvironments(environments) }, environments, summary: summariseRuntimeEnvironments(environments), updatedAt: new Date().toISOString() }); } catch (error) { console.error('[OWNER RUNTIME]', error); return res.status(500).json({ success: false, error: error.message }); } });

module.exports = router;
