'use strict';

const faq=require('./faq');
const panel=require('./faqPanel');
const { isModuleEnabled }=require('../../../core/guild/guildManager');
const { DEFAULT_BOT_CHANNEL_PERMISSIONS, guardChannelAccess }=require('../../../core/security/protection/permissions');

async function getChannel(guild,id,label){if(!id)throw new Error(`Select a ${label} first.`);const channel=guild.channels.cache.get(id)||await guild.channels.fetch(id).catch(()=>null);if(!channel?.send)throw new Error(`${label} is unavailable or not sendable.`);return channel;}
async function deploy(guild,actorId=null){if(!guild?.id)throw new Error('Guild is required.');if(!isModuleEnabled(guild.id,'faq'))throw new Error('FAQ module is disabled.');const section=faq.getSection(guild.id);const channel=await getChannel(guild,section.settings.channelId,'FAQ channel');await guardChannelAccess(guild,channel.id,DEFAULT_BOT_CHANNEL_PERMISSIONS,{scope:'faq.panel_deployment',autoFix:true,throwOnFail:true,reason:'Goliath FAQ panel deployment validation'});let message=section.panel.messageId?await channel.messages.fetch(section.panel.messageId).catch(()=>null):null;const payload=panel.buildHomePanel(guild.id);if(message)await message.edit(payload);else message=await channel.send(payload);faq.updateSection(guild.id,s=>({...s,panel:{channelId:channel.id,messageId:message.id,deployedAt:new Date().toISOString(),deployedBy:actorId},updatedAt:new Date().toISOString()}),guild);return message;}
async function refreshPublicPanel(guild){const s=faq.getSection(guild.id);if(!s.panel.channelId||!s.panel.messageId)return null;const channel=await getChannel(guild,s.panel.channelId,'FAQ channel');const message=await channel.messages.fetch(s.panel.messageId).catch(()=>null);if(message)await message.edit(panel.buildHomePanel(guild.id));return message;}
async function submitQuestion(guild,user,question,details=''){if(!isModuleEnabled(guild.id,'faq'))throw new Error('FAQ is currently disabled.');const section=faq.getSection(guild.id);const inbox=await getChannel(guild,section.settings.inboxChannelId,'team FAQ inbox');await guardChannelAccess(guild,inbox.id,DEFAULT_BOT_CHANNEL_PERMISSIONS,{scope:'faq.team_inbox',autoFix:true,throwOnFail:true,reason:'Goliath FAQ team inbox validation'});const ref=faq.allocateReference(guild.id,guild.name,guild);let submission=faq.saveSubmission(guild.id,{id:faq.createId('submission'),reference:ref.reference,referenceNumber:ref.number,question,details,submittedBy:user.id,status:'submitted',teamChannelId:inbox.id},guild);const message=await inbox.send(panel.buildTeamSubmission(guild.id,submission.id));submission=faq.patchSubmission(guild.id,submission.id,{teamMessageId:message.id},guild);increment(guild.id,'submitted',guild);return submission;}
async function refreshTeamMessage(guild,submissionId){const s=faq.getSubmission(guild.id,submissionId);if(!s?.teamChannelId||!s.teamMessageId)return null;const channel=guild.channels.cache.get(s.teamChannelId)||await guild.channels.fetch(s.teamChannelId).catch(()=>null);const message=await channel?.messages?.fetch(s.teamMessageId).catch(()=>null);if(message)await message.edit(panel.buildTeamSubmission(guild.id,s.id));return message;}
async function createPublicThread(guild,entry){const section=faq.getSection(guild.id);const channel=await getChannel(guild,section.settings.channelId,'FAQ channel');if(!channel.threads?.create)throw new Error('The configured FAQ channel does not support public threads.');const safeQuestion=entry.question.replace(/[\r\n]+/g,' ').trim();const name=`${entry.reference || 'FAQ'}・${safeQuestion}`.slice(0,100);const thread=await channel.threads.create({name,autoArchiveDuration:10080,reason:`Published FAQ ${entry.reference||entry.id}`});const message=await thread.send(panel.buildAnswerPanel(guild.id,entry.id));await thread.setLocked(true,'Published FAQ threads are read-only').catch(()=>null);return{thread,message,url:`https://discord.com/channels/${guild.id}/${thread.id}/${message.id}`};}
async function publishSubmission(guild,submissionId,userId){const s=faq.getSubmission(guild.id,submissionId);if(!s)throw new Error('Submission no longer exists.');if(!s.answer)throw new Error('Add an answer before publishing.');if(!s.categoryId||!faq.getSection(guild.id).categories[s.categoryId])throw new Error('Select a category before publishing.');let entry=faq.saveEntry(guild.id,{id:s.entryId||faq.createId('faq'),reference:s.reference,categoryId:s.categoryId,question:s.question,answer:s.answer,resources:s.resources,supportChannelId:s.supportChannelId,sourceSubmissionId:s.id,keywords:s.question.toLowerCase().split(/\W+/).filter(x=>x.length>3).slice(0,20)},guild);if(!entry.threadId){const published=await createPublicThread(guild,entry);entry=faq.saveEntry(guild.id,{...entry,threadId:published.thread.id,threadMessageId:published.message.id,threadUrl:published.url},guild);}faq.patchSubmission(guild.id,s.id,{status:'published',entryId:entry.id,threadId:entry.threadId,threadUrl:entry.threadUrl,publishedBy:userId,publishedAt:new Date().toISOString()},guild);increment(guild.id,'published',guild);await refreshTeamMessage(guild,s.id);await refreshPublicPanel(guild).catch(()=>null);return entry;}
function increment(guildId,key,guild){faq.updateSection(guildId,s=>({...s,analytics:{...s.analytics,[key]:Math.max(0,Number(s.analytics?.[key]||0))+1},updatedAt:new Date().toISOString()}),guild);}
module.exports={deploy,refreshPublicPanel,submitQuestion,refreshTeamMessage,publishSubmission,increment};
