'use strict';

const crypto = require('crypto');
const { getModuleSection, saveModuleSection, updateModuleSection } = require('../../core/guild/moduleSectionManager');
const guildManager = require('../../core/guild/guildManager');

const MODULE = 'verification';
const SCHEMA_VERSION = 3;
const CONFIG_HISTORY_LIMIT = 5;
const STATES = new Set(['new','pending','verifying','verified','quarantined','review','failed','timed_out','rejected']);
const SECURITY_METHODS = new Set(['simple','captcha','minigame','account_age','discord_screening','bot_protection','staff_approval','one_time_challenge','risk_based','rejoin_history']);
const now = () => new Date().toISOString();
const clone = v => v == null ? v : JSON.parse(JSON.stringify(v));
const cleanString = (v,f='',n=1000) => String(v ?? f).trim().slice(0,n);
const cleanId = v => { const id=String(v||'').replace(/[<@&#!>]/g,'').trim(); return /^\d{15,25}$/.test(id)?id:null; };
const cleanIds = v => [...new Set((Array.isArray(v)?v:v?[v]:[]).map(cleanId).filter(Boolean))];
const cleanInt = (v,f=0,min=0,max=Number.MAX_SAFE_INTEGER) => { const n=Number.parseInt(v,10); return Number.isFinite(n)?Math.min(max,Math.max(min,n)):f; };
const cleanDate = v => { const d=v?new Date(v):null; return d&&Number.isFinite(d.getTime())?d.toISOString():null; };
const createId = (p='verify') => `${p}_${crypto.randomUUID().slice(0,8)}`;

function defaultMessages(){return {success:'Verification complete. Welcome to {server}.',alreadyVerified:'You are already Verified.',unavailable:'Verification is currently unavailable. Please contact a management member.',start:'Verification has started.',screeningRequired:'Please complete Discord Membership Screening before continuing.',pendingRoleRequired:'You do not currently have the required pending role.',accountTooNew:'Your Discord account must be at least {minimumAccountAgeDays} day(s) old.',membershipTooNew:'You must remain in the server for at least {minimumMembershipAgeMinutes} minute(s) before verifying.',botBlocked:'Bot accounts cannot use this verification flow.',cooldown:'Please wait {cooldownSeconds} second(s) before trying again.',failed:'Verification failed. Please try again.',retry:'Verification failed. You have {attemptsRemaining} attempt(s) remaining.',quarantined:'Verification has been locked and your case has been escalated to staff.',timedOut:'Your verification session expired.',dmSuccess:'You are now verified in {server}.',pendingAssigned:'Your pending verification role has been assigned in {server}.',screeningCompletedLog:'📜 {user} completed Discord Membership Screening.',successLog:'✅ {user} completed verification.',failureLog:'❌ {user} failed verification: {reason}',intelligenceFlagLog:'🧠 {user} was flagged by Verification Intelligence: {reason}',quarantineLog:'🚨 {user} was quarantined after {attempts} failed verification attempt(s).'};}
function defaultPanelTemplate(){return {title:'Server Verification',description:'Press the button below to begin verification.',color:'#57f287',footer:'Goliath Verification',thumbnailUrl:null,imageUrl:null,buttonLabel:'Verify',buttonEmoji:null,buttonStyle:'success'};}
function defaultSettings(){return {method:'button',verificationChannelId:null,logChannelId:null,roles:{pending:[],verifying:[],verified:[],auto:[],bot:[],bypass:[],quarantine:[],staff:[]},security:{simple:true,captcha:false,minigame:false,accountAge:false,discordScreening:false,botProtection:true,staffApproval:false,oneTimeChallenge:false,riskBased:false,rejoinHistory:true,minimumAccountAgeDays:0,allowReverification:true,maximumFailedAttempts:5,attemptCooldownSeconds:10,retryResetMinutes:1440,quarantineOnLimit:true,minigameConfig:{random:true,difficulty:'normal',rounds:1,timeLimitSeconds:60,enabledGames:['target_match','memory_match','sequence','pattern_match','reaction','odd_one_out','order']}},intelligence:{enabled:false,initialScan:true,continuousScan:false,rescanMinutes:1440,logEnabled:true,logSuccessfulScans:false,logFlags:true,logErrors:true},flow:{enabled:true,orderedSecurity:['simple'],discordScreeningGate:false,resetActiveSessionOnLeave:true,retainSecurityHistory:true,failClosed:true},logs:{joinChannelId:null,intelligenceChannelId:null,attemptChannelId:null,failureChannelId:null,successChannelId:null,rolesChannelId:null,botChannelId:null,raidChannelId:null,quarantineChannelId:null,staffChannelId:null,errorChannelId:null},raid:{enabled:true,automatic:true,windowSeconds:60,joinThreshold:10,elevateSecurity:true},quarantine:{enabled:true,attemptThreshold:5,categoryId:null,staffRoleIds:[],autoExpireMinutes:0},botPolicy:{denySuspicious:true,allowConfiguredBots:true},health:{testMode:false,cleanupEnabled:true},waitForDiscordScreening:false,skipScreeningIfUnavailable:true,logScreeningCompletion:true,stagedRoleFlow:false,arrivalRoleIds:[],usePendingRoles:true,assignPendingRoles:true,pendingRoleTiming:'on_join',requirePendingRole:false,removePendingRoles:true,removePendingRole:true,verifiedRoleIds:[],pendingRoleIds:[],verifiedRoleId:null,unverifiedRoleId:null,dmOnVerify:true,dmOnPendingRole:false,logSuccess:true,logFailure:true,blockBots:true,allowStaffBypass:false,allowReverification:true,minimumAccountAgeDays:0,minimumMembershipAgeMinutes:0,attemptCooldownSeconds:10,maximumFailedAttempts:5};}
function defaultAnalytics(){return {verified:0,failed:0,alreadyVerified:0,screeningBlocked:0,screeningCompleted:0,requirementBlocked:0,accountAgeBlocked:0,membershipAgeBlocked:0,botBlocked:0,cooldownBlocked:0,pendingRolesAssigned:0,unavailable:0,roleManageFailed:0,quarantined:0,intelligenceFlags:0,raidEscalations:0,lastVerificationAt:null,lastFailedAt:null,lastScreeningCompletedAt:null,lastPendingRoleAssignedAt:null,lastQuarantineAt:null};}
function defaultSection(){return {schemaVersion:SCHEMA_VERSION,configRevision:1,lastKnownGoodRevision:1,configHistory:[],settings:defaultSettings(),messages:defaultMessages(),panelTemplate:defaultPanelTemplate(),activePanelId:null,panels:{},sessions:{},attempts:{},securityHistory:{},analytics:defaultAnalytics(),createdAt:now(),updatedAt:now()};}
function normalizeSettings(input={}){const s=input&&typeof input==='object'?input:{},b=defaultSettings();const lp=cleanIds(s.pendingRoleIds?.length?s.pendingRoleIds:(s.unverifiedRoleId?[s.unverifiedRoleId]:[])),lv=cleanIds(s.verifiedRoleIds?.length?s.verifiedRoleIds:(s.verifiedRoleId?[s.verifiedRoleId]:[]));const roles={...b.roles,...clone(s.roles||{})};roles.pending=cleanIds(roles.pending?.length?roles.pending:lp);roles.verified=cleanIds(roles.verified?.length?roles.verified:lv);for(const k of ['verifying','auto','bot','bypass','quarantine','staff'])roles[k]=cleanIds(roles[k]);const security={...b.security,...clone(s.security||{})};security.maximumFailedAttempts=cleanInt(security.maximumFailedAttempts??s.maximumFailedAttempts,5,0,1000);security.attemptCooldownSeconds=cleanInt(security.attemptCooldownSeconds??s.attemptCooldownSeconds,10,0,86400);security.minimumAccountAgeDays=cleanInt(security.minimumAccountAgeDays??s.minimumAccountAgeDays,0,0,3650);security.discordScreening=security.discordScreening===true||s.waitForDiscordScreening===true;security.botProtection=security.botProtection!==false&&s.blockBots!==false;security.allowReverification=security.allowReverification!==false&&s.allowReverification!==false;const intelligence={...b.intelligence,...clone(s.intelligence||{})},flow={...b.flow,...clone(s.flow||{})},logs={...b.logs,...clone(s.logs||{})},quarantine={...b.quarantine,...clone(s.quarantine||{})},raid={...b.raid,...clone(s.raid||{})},botPolicy={...b.botPolicy,...clone(s.botPolicy||{})},health={...b.health,...clone(s.health||{})};quarantine.staffRoleIds=cleanIds(quarantine.staffRoleIds?.length?quarantine.staffRoleIds:roles.staff);quarantine.categoryId=cleanId(quarantine.categoryId);const ordered=Array.isArray(flow.orderedSecurity)?flow.orderedSecurity.filter(x=>SECURITY_METHODS.has(x)):[];flow.orderedSecurity=ordered.length?ordered:['simple'];const out={...b,...clone(s),roles,security,intelligence,flow,logs,quarantine,raid,botPolicy,health};out.verificationChannelId=cleanId(s.verificationChannelId);out.logChannelId=cleanId(s.logChannelId);out.pendingRoleIds=roles.pending;out.verifiedRoleIds=roles.verified;out.verifiedRoleId=roles.verified[0]||null;out.unverifiedRoleId=roles.pending[0]||null;out.arrivalRoleIds=cleanIds(s.arrivalRoleIds);out.maximumFailedAttempts=security.maximumFailedAttempts;out.attemptCooldownSeconds=security.attemptCooldownSeconds;out.minimumAccountAgeDays=security.minimumAccountAgeDays;out.waitForDiscordScreening=security.discordScreening;out.blockBots=security.botProtection;out.allowReverification=security.allowReverification;return out;}
function normalizeMessages(m={}){const b=defaultMessages(),s=m&&typeof m==='object'?m:{};return Object.fromEntries(Object.entries({...b,...s}).map(([k,v])=>[k,cleanString(v,b[k]||'',1500)]));}
function normalizePanelTemplate(t={}){const b=defaultPanelTemplate(),s=t&&typeof t==='object'?t:{};return {...b,...clone(s),title:cleanString(s.title||b.title,b.title,100),description:cleanString(s.description||b.description,b.description,1000),footer:cleanString(s.footer||b.footer,b.footer,200)};}
function normalizeSession(v={},userId=null){const s=v&&typeof v==='object'?v:{},state=STATES.has(s.state)?s.state:'new';return {...clone(s),sessionId:cleanString(s.sessionId||createId('session'),'session',80),userId:cleanId(s.userId||userId),state,requiredSecurity:Array.isArray(s.requiredSecurity)?s.requiredSecurity.filter(x=>SECURITY_METHODS.has(x)):[],completedSecurity:Array.isArray(s.completedSecurity)?s.completedSecurity.filter(x=>SECURITY_METHODS.has(x)):[],failedAttempts:cleanInt(s.failedAttempts,0,0,100000),flags:Array.isArray(s.flags)?clone(s.flags):[],createdAt:cleanDate(s.createdAt)||now(),updatedAt:cleanDate(s.updatedAt)||now(),startedAt:cleanDate(s.startedAt),verifiedAt:cleanDate(s.verifiedAt),quarantinedAt:cleanDate(s.quarantinedAt)};}
function normalizeMap(map,fn){if(!map||typeof map!=='object'||Array.isArray(map))return {};return Object.fromEntries(Object.entries(map).map(([k,v])=>[k,fn(v,k)]));}
function normalizeSection(input={}){const b=defaultSection(),s=input&&typeof input==='object'?input:{};return {...b,...clone(s),schemaVersion:SCHEMA_VERSION,settings:normalizeSettings(s.settings),messages:normalizeMessages(s.messages),panelTemplate:normalizePanelTemplate(s.panelTemplate),sessions:normalizeMap(s.sessions,normalizeSession),attempts:normalizeMap(s.attempts,a=>({...clone(a),failed:cleanInt(a?.failed,0,0,100000),lastAttemptAt:cleanDate(a?.lastAttemptAt),lastFailureAt:cleanDate(a?.lastFailureAt)})),securityHistory:normalizeMap(s.securityHistory,h=>Array.isArray(h)?h.slice(-100).map(clone):[]),analytics:{...b.analytics,...clone(s.analytics||{})},createdAt:s.createdAt||b.createdAt,updatedAt:now()};}
function getVerificationSection(guildId){return normalizeSection(getModuleSection(guildId,MODULE)||{});}function saveVerificationSection(guildId,section){return saveModuleSection(guildId,MODULE,normalizeSection(section));}function updateVerificationSection(guildId,updater){return updateModuleSection(guildId,MODULE,current=>normalizeSection(typeof updater==='function'?updater(normalizeSection(current||{})):current||{}));}
function getSession(guildId,userId){return getVerificationSection(guildId).sessions[String(userId)]||null;}function upsertSession(guildId,userId,patch={}){let result;updateVerificationSection(guildId,section=>{const current=section.sessions[String(userId)]||{};result=normalizeSession({...current,...clone(patch),userId,updatedAt:now()},userId);section.sessions[String(userId)]=result;return section;});return result;}function resetActiveSession(guildId,userId){return upsertSession(guildId,userId,{sessionId:createId('session'),state:'new',requiredSecurity:[],completedSecurity:[],failedAttempts:0,flags:[],startedAt:null,verifiedAt:null,quarantinedAt:null});}function addSecurityHistory(guildId,userId,event={}){updateVerificationSection(guildId,section=>{const key=String(userId),list=Array.isArray(section.securityHistory[key])?section.securityHistory[key]:[];list.push({...clone(event),at:cleanDate(event.at)||now()});section.securityHistory[key]=list.slice(-100);return section;});}function incrementAttempt(guildId,userId,failed=false){let result;updateVerificationSection(guildId,section=>{const key=String(userId),a=section.attempts[key]||{};result={...a,failed:cleanInt(a.failed,0)+(failed?1:0),lastAttemptAt:now(),lastFailureAt:failed?now():a.lastFailureAt||null};section.attempts[key]=result;return section;});return result;}function isEnabled(guildId){return guildManager.isModuleEnabled(guildId,MODULE);}
module.exports={MODULE,SCHEMA_VERSION,STATES,SECURITY_METHODS,CONFIG_HISTORY_LIMIT,defaultSettings,defaultMessages,defaultPanelTemplate,defaultVerificationSection:defaultSection,normalizeSettings,normalizeMessages,normalizePanelTemplate,normalizeVerificationSection:normalizeSection,getVerificationSection,saveVerificationSection,updateVerificationSection,getSession,upsertSession,resetActiveSession,addSecurityHistory,incrementAttempt,isEnabled,createId};
