'use strict';

const { PermissionFlagsBits } = require('discord.js');
const guildManager = require('../../core/guild/guildManager');
const verificationManager = require('./verificationManager');
const verificationStore = require('./verificationStore');

const MODULE = 'verification';

function requireGuild(guild) { if (!guild?.id) throw new Error('Guild is unavailable.'); return guild; }
function add(warnings, value) { if (value && !warnings.includes(value)) warnings.push(value); }
function ids(value) { return [...new Set((Array.isArray(value) ? value : []).filter(Boolean))]; }
function roleGroups(settings) { const roles=settings.roles||{}; return { Pending:ids(roles.pending||settings.pendingRoleIds), Verifying:ids(roles.verifying), Verified:ids(roles.verified||settings.verifiedRoleIds), 'Auto Role':ids(roles.auto), 'Bot Auto Role':ids(roles.bot), Bypass:ids(roles.bypass), Quarantine:ids(roles.quarantine), Staff:ids(roles.staff) }; }
function validateRoles(guild, settings, warnings) { const groups=roleGroups(settings),used=new Map(),bot=guild.members.me; for(const [label,roleIds] of Object.entries(groups)){for(const roleId of roleIds){const role=guild.roles.cache.get(roleId);if(!role){add(warnings,`${label} role ${roleId} no longer exists.`);continue;}if(role.managed)add(warnings,`${label} role ${role.name} is integration-managed and cannot be assigned by Goliath.`);if(bot&&bot.roles.highest.position<=role.position)add(warnings,`Goliath's role must be above ${role.name} to manage the configured ${label} role.`);const prior=used.get(roleId);if(prior&&prior!==label)add(warnings,`${role.name} is configured as both ${prior} and ${label}. Security lifecycle roles should be distinct.`);else used.set(roleId,label);}}if(!groups.Verified.length)add(warnings,'No Verified role is configured. Successful verification cannot grant server access through Verification.');if(settings.quarantine?.enabled&&!groups.Quarantine.length)add(warnings,'Quarantine is enabled but no Quarantine role is configured.');return groups; }
function validateSecurity(guild, settings, warnings) { const security=settings.security||{},flow=settings.flow||{},enabled=[];if(security.simple)enabled.push('simple');if(security.captcha)enabled.push('captcha');if(security.minigame)enabled.push('minigame');if(security.accountAge)enabled.push('account_age');if(security.discordScreening)enabled.push('discord_screening');if(security.botProtection)enabled.push('bot_protection');if(security.staffApproval)enabled.push('staff_approval');if(security.oneTimeChallenge)enabled.push('one_time_challenge');if(security.riskBased)enabled.push('risk_based');if(security.rejoinHistory)enabled.push('rejoin_history');if(!enabled.length)add(warnings,'No Verification security method is enabled.');if(security.discordScreening&&!verificationManager.hasDiscordScreening(guild))add(warnings,'Discord Membership Screening is enabled in Verification but is not enabled for this guild.');const order=Array.isArray(flow.orderedSecurity)?flow.orderedSecurity:[];for(const method of order)if(!enabled.includes(method))add(warnings,`Flow contains ${method}, but that security method is disabled.`);for(const method of enabled)if(!order.includes(method))add(warnings,`${method} is enabled but is not present in the Verification Flow.`);if(security.riskBased&&!settings.intelligence?.enabled)add(warnings,'Risk-Based Security is enabled while Intelligence is disabled.');if(security.maximumFailedAttempts>0&&settings.quarantine?.enabled&&Number(settings.quarantine.attemptThreshold||0)<=0)add(warnings,'Quarantine is enabled but its failure threshold is not configured.');if(security.captcha){if(Number(security.captchaConfig?.timeLimitSeconds||0)<15)add(warnings,'CAPTCHA time limit is too short.');if(Number(security.captchaConfig?.maxChallengeAttempts||0)<1)add(warnings,'CAPTCHA must allow at least one challenge attempt.');}if(security.minigame){const games=security.minigameConfig?.enabledGames;if(!Array.isArray(games)||!games.length)add(warnings,'Mini-game security is enabled but no mini-games are selected.');if(Number(security.minigameConfig?.rounds||0)<1)add(warnings,'Mini-game security must contain at least one round.');}if(security.staffApproval&&!roleGroups(settings).Staff.length)add(warnings,'Staff Approval is enabled but no Staff role is configured.');if(security.oneTimeChallenge&&Number(security.oneTimeChallengeConfig?.maxChallengeAttempts||0)<1)add(warnings,'One-Time Challenge must allow at least one attempt.');if(Number(security.sessionTimeoutMinutes||0)<1)add(warnings,'Verification session timeout must be at least one minute.');return enabled; }
function validateChannels(guild, settings, warnings) { const configured={Verification:settings.verificationChannelId,JoinLog:settings.logs?.joinChannelId,IntelligenceLog:settings.logs?.intelligenceChannelId,AttemptLog:settings.logs?.attemptChannelId,FailureLog:settings.logs?.failureChannelId,SuccessLog:settings.logs?.successChannelId,RoleLog:settings.logs?.rolesChannelId,BotLog:settings.logs?.botChannelId,RaidLog:settings.logs?.raidChannelId,QuarantineLog:settings.logs?.quarantineChannelId,StaffLog:settings.logs?.staffChannelId,ErrorLog:settings.logs?.errorChannelId};for(const [label,channelId] of Object.entries(configured))if(channelId&&!guild.channels.cache.has(channelId))add(warnings,`${label} channel ${channelId} no longer exists.`);if(settings.quarantine?.categoryId&&!guild.channels.cache.has(settings.quarantine.categoryId))add(warnings,`Quarantine category ${settings.quarantine.categoryId} no longer exists.`); }
function validateBotPermissions(guild, settings, warnings) { const bot=guild.members.me;if(!bot){add(warnings,'Goliath member could not be resolved in this guild.');return;}if(!bot.permissions.has(PermissionFlagsBits.ManageRoles))add(warnings,'Goliath requires Manage Roles for Verification role transitions.');if(!bot.permissions.has(PermissionFlagsBits.ViewChannel))add(warnings,'Goliath requires View Channels for Verification health and logging.');if(!bot.permissions.has(PermissionFlagsBits.SendMessages))add(warnings,'Goliath requires Send Messages for Verification panels and logs.');if(settings.quarantine?.enabled&&settings.quarantine?.categoryId&&!bot.permissions.has(PermissionFlagsBits.ManageChannels))add(warnings,'Goliath requires Manage Channels to maintain configured quarantine case channels.'); }

async function buildHealthReport(guild) { const target=requireGuild(guild),base=await verificationManager.buildHealthReport(target),section=verificationStore.getVerificationSection(target.id),settings=section.settings||{},warnings=Array.isArray(base.warnings)?[...base.warnings]:[];validateBotPermissions(target,settings,warnings);const roles=validateRoles(target,settings,warnings),securityMethods=validateSecurity(target,settings,warnings);validateChannels(target,settings,warnings);const activeChallenges=Object.values(section.sessions||{}).filter(session=>session?.activeChallenge?.status==='pending').length;return {...base,warnings,enabled:guildManager.isModuleEnabled(target.id,MODULE),roles,securityMethods,activeChallenges,failClosed:settings.flow?.failClosed!==false}; }
async function repairMissingPanelMessages(guild, report, meta={}) { const missing=(report?.panels||[]).filter(panel=>panel?.ok===false&&panel?.status==='Missing message'&&panel?.panelId);if(!missing.length)return {repaired:0,failed:[]};let repaired=0;const failed=[];for(const health of missing){const panel=verificationStore.getPanel(guild.id,health.panelId);if(!panel?.channelId){failed.push({panelId:health.panelId,reason:'Missing panel channel.'});continue;}try{await verificationManager.restoreMissingVerificationPanel(guild,health.panelId,{action:'verification_health_restore_missing_message',actorId:'system:verification-health',...meta});repaired+=1;}catch(error){failed.push({panelId:health.panelId,reason:error?.message||'Panel restore failed.'});}}return {repaired,failed}; }
async function repair(guild, meta={}) { const target=requireGuild(guild),before=await buildHealthReport(target),recovery=await repairMissingPanelMessages(target,before,meta),after=recovery.repaired?await buildHealthReport(target):before;return {...after,repair:recovery}; }
module.exports={buildHealthReport,repair,repairMissingPanelMessages};
