'use strict';

const { EmbedBuilder, AuditLogEvent, PermissionFlagsBits } = require('discord.js');
const guildManager = require('../../core/guild/guildManager');
const autoRoleManager = require('../../modules/roleStudio/autoRoles/autoRoles');
const statsManager = require('../../modules/utilityStudio/stats/statsManager');
const verificationManager = require('../../modules/securityStudio/verificationManager');
const verificationStore = require('../../modules/securityStudio/verificationStore');
const welcomeManager = require('../../modules/messageStudio/welcome/welcome');
const welcomeAvatarSync = require('../../modules/messageStudio/welcome/welcomeAvatarSync');
const goodbyeDeparture = require('../../modules/messageStudio/goodbye/goodbyeDeparture');

function formatTimestamp(timestamp, style = 'R') { return timestamp ? `<t:${Math.floor(timestamp / 1000)}:${style}>` : 'Unknown'; }
function formatUser(user) { if (!user) return 'Unknown User'; return `${user} \`${user.tag || user.username || user.id}\``; }
function getAvatar(member) { return member.displayAvatarURL({ extension: 'png', size: 256 }); }
function getRolesText(member, addedRoles = []) { const roles=member.roles.cache.filter(role=>role.id!==member.guild.id).sort((a,b)=>b.position-a.position).map(role=>role.toString()); for(const role of addedRoles) if(!roles.includes(role.toString())) roles.push(role.toString()); return roles.length?roles.join(', ').slice(0,1024):'No roles'; }
function isLogEnabled(guildId,eventName){if(typeof guildManager.isLogEventEnabled!=='function')return true;return guildManager.isLogEventEnabled(guildId,eventName)!==false;}
function delay(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
const REMOVAL_TYPES={left:{key:'left',title:'👋 Member Left',color:'#ED4245',eventName:'memberLeave',reasonLabel:'No reason — the member left voluntarily.'},kicked:{key:'kicked',title:'👢 Member Kicked',color:'#FAA61A',eventName:'memberKick',auditType:AuditLogEvent.MemberKick,reasonLabel:'No reason provided.'},banned:{key:'banned',title:'🔨 Member Banned',color:'#ED4245',eventName:'memberBan',auditType:AuditLogEvent.MemberBanAdd,reasonLabel:'No reason provided.'},pruned:{key:'pruned',title:'🧹 Member Pruned / Removed',color:'#FEE75C',eventName:'memberPrune',auditType:AuditLogEvent.MemberPrune,reasonLabel:'Member removed during a server prune.'}};
async function findRecentAuditLog(guild,userId,auditType,maxAgeMs=15000,allowTargetless=false){if(!auditType)return null;try{const logs=await guild.fetchAuditLogs({limit:10,type:auditType});return logs.entries.find(entry=>{const targetId=entry.target?.id||null;return(targetId===userId||(allowTargetless&&!targetId))&&Date.now()-entry.createdTimestamp<maxAgeMs;})||null;}catch(error){console.warn(`[joinLeave] Audit log check failed for ${auditType}:`,error.message);return null;}}
async function findRecentAuditLogWithRetry(guild,userId,auditType,options={}){const{maxAgeMs=30000,allowTargetless=false,attempts=4,retryDelayMs=750}=options;for(let attempt=0;attempt<attempts;attempt+=1){const entry=await findRecentAuditLog(guild,userId,auditType,maxAgeMs,allowTargetless);if(entry)return entry;if(attempt<attempts-1)await delay(retryDelayMs*(attempt+1));}return null;}
async function fetchActiveBan(guild,userId){try{return await guild.bans.fetch(userId);}catch(error){if(error?.code!==10026)console.warn('[joinLeave] Active ban check failed:',error.message||error);return null;}}
async function detectRemoval(member){const guild=member.guild,userId=member.user.id;await delay(750);const activeBan=await fetchActiveBan(guild,userId);if(activeBan){const banLog=await findRecentAuditLogWithRetry(guild,userId,AuditLogEvent.MemberBanAdd,{maxAgeMs:45000,attempts:4,retryDelayMs:750});return{...REMOVAL_TYPES.banned,auditLog:banLog,reasonLabel:activeBan.reason||REMOVAL_TYPES.banned.reasonLabel};}const banLog=await findRecentAuditLogWithRetry(guild,userId,AuditLogEvent.MemberBanAdd,{maxAgeMs:45000,attempts:4,retryDelayMs:750});if(banLog)return{...REMOVAL_TYPES.banned,auditLog:banLog};const kickLog=await findRecentAuditLogWithRetry(guild,userId,AuditLogEvent.MemberKick,{maxAgeMs:35000,attempts:3,retryDelayMs:600});if(kickLog)return{...REMOVAL_TYPES.kicked,auditLog:kickLog};const pruneLog=await findRecentAuditLogWithRetry(guild,userId,AuditLogEvent.MemberPrune,{maxAgeMs:45000,allowTargetless:true,attempts:2,retryDelayMs:500});if(pruneLog)return{...REMOVAL_TYPES.pruned,auditLog:pruneLog};return{...REMOVAL_TYPES.left,auditLog:null};}
async function getAdminMemberLogChannel(guild,eventName='memberJoin'){const channelId=guildManager.getLogChannelId(guild.id,eventName,'member');if(!channelId)return null;const channel=guild.channels.cache.get(channelId)||await guild.channels.fetch(channelId).catch(()=>null);return channel?.isTextBased?.()?channel:null;}
function buildAdminJoinLog(member,addedRoles=[]){const guild=member.guild;return new EmbedBuilder().setColor('#57F287').setTitle('👥 Member Joined').setThumbnail(getAvatar(member)).addFields({name:'User',value:formatUser(member.user),inline:true},{name:'User ID',value:`\`${member.user.id}\``,inline:true},{name:'Type',value:member.user.bot?'🤖 Bot':'👤 User',inline:true},{name:'Account Created',value:`${formatTimestamp(member.user.createdTimestamp,'R')}\n${formatTimestamp(member.user.createdTimestamp,'F')}`,inline:true},{name:'Joined Server',value:`${formatTimestamp(member.joinedTimestamp,'R')}\n${formatTimestamp(member.joinedTimestamp,'F')}`,inline:true},{name:'Member Count',value:`\`${guild.memberCount}\``,inline:true},{name:'Roles',value:getRolesText(member,addedRoles),inline:false}).setFooter({text:'Admin Log'}).setTimestamp();}
function buildAdminRemovalLog(member,removal){const guild=member.guild,auditLog=removal?.auditLog||null,reason=auditLog?.reason||removal?.reasonLabel||'No reason provided',moderator=auditLog?.executor||null;const embed=new EmbedBuilder().setColor(removal.color||'#ED4245').setTitle(removal.title||'🚪 Member Removed').setThumbnail(getAvatar(member)).addFields({name:'User',value:formatUser(member.user),inline:true},{name:'User ID',value:`\`${member.user.id}\``,inline:true},{name:'Type',value:member.user.bot?'🤖 Bot':'👤 User',inline:true},{name:'Removal Type',value:`\`${removal.key||'unknown'}\``,inline:true},{name:'Account Created',value:`${formatTimestamp(member.user.createdTimestamp,'R')}\n${formatTimestamp(member.user.createdTimestamp,'F')}`,inline:true},{name:'Joined Server',value:member.joinedTimestamp?`${formatTimestamp(member.joinedTimestamp,'R')}\n${formatTimestamp(member.joinedTimestamp,'F')}`:'Unknown',inline:true},{name:'Member Count',value:`\`${guild.memberCount}\``,inline:true},{name:'Roles',value:getRolesText(member),inline:false},{name:'Reason',value:String(reason).slice(0,1024),inline:false}).setFooter({text:'Admin Log'}).setTimestamp();if(moderator)embed.addFields({name:'Moderator',value:formatUser(moderator),inline:true});return embed;}
async function sendAdminMemberJoinLog(member,addedRoles=[]){try{if(!isLogEnabled(member.guild.id,'memberJoin'))return;const channel=await getAdminMemberLogChannel(member.guild,'memberJoin');if(channel)await channel.send({embeds:[buildAdminJoinLog(member,addedRoles)]});}catch(error){console.error('[joinLeave] Failed to send admin member join log:',error);}}
async function sendAdminMemberRemovalLog(member,removal){try{const eventName=removal?.eventName||'memberRemove';if(!isLogEnabled(member.guild.id,eventName)&&!isLogEnabled(member.guild.id,'memberLeave'))return;const channel=await getAdminMemberLogChannel(member.guild,eventName);if(channel)await channel.send({embeds:[buildAdminRemovalLog(member,removal)]});}catch(error){console.error('[joinLeave] Failed to send admin member removal log:',error);}}
function configuredSecurity(settings){const security=settings.security||{},ordered=Array.isArray(settings.flow?.orderedSecurity)?settings.flow.orderedSecurity:[];return ordered.filter(method=>{if(method==='simple')return security.simple!==false;if(method==='captcha')return security.captcha===true;if(method==='minigame')return security.minigame===true;if(method==='account_age')return security.accountAge===true||Number(security.minimumAccountAgeDays||0)>0;if(method==='discord_screening')return security.discordScreening===true;if(method==='bot_protection')return security.botProtection===true;if(method==='staff_approval')return security.staffApproval===true;if(method==='one_time_challenge')return security.oneTimeChallenge===true;if(method==='risk_based')return security.riskBased===true;if(method==='rejoin_history')return security.rejoinHistory===true;return false;});}
function hasConfiguredRole(member,ids=[]){return ids.some(id=>member.roles.cache.has(id));}
async function applyConfiguredBotRoles(member,settings){const ids=settings.roles?.bot||[];if(!ids.length)return[];const me=member.guild.members.me;if(!me?.permissions.has(PermissionFlagsBits.ManageRoles))throw new Error('Goliath is missing Manage Roles for configured bot roles.');const added=[];for(const id of ids){const role=member.guild.roles.cache.get(id)||await member.guild.roles.fetch(id).catch(()=>null);if(!role||role.managed||role.position>=me.roles.highest.position)throw new Error(`Configured bot role ${id} is missing or cannot be managed.`);if(!member.roles.cache.has(role.id)){await member.roles.add(role,'Goliath Verification approved bot role');added.push(role);}}return added;}
async function initialiseVerificationJourney(member){if(!guildManager.isModuleEnabled(member.guild.id,'verification'))return{handled:false,assigned:[]};const section=verificationStore.getVerificationSection(member.guild.id),settings=section.settings||{},roles=settings.roles||{};if(member.user?.bot){try{const assigned=settings.botPolicy?.allowConfiguredBots!==false?await applyConfiguredBotRoles(member,settings):[];verificationStore.addSecurityHistory(member.guild.id,member.id,{type:'bot_join',assignedRoleIds:assigned.map(role=>role.id)});return{handled:true,bot:true,assigned};}catch(error){verificationStore.addSecurityHistory(member.guild.id,member.id,{type:'bot_role_failure',reason:error?.message||String(error)});throw error;}}
 const bypass=hasConfiguredRole(member,roles.bypass||[]);const required=bypass?[]:configuredSecurity(settings);const state=bypass?'verified':'pending';verificationStore.upsertSession(member.guild.id,member.id,{state,requiredSecurity:required,completedSecurity:bypass?required:[],failedAttempts:0,flags:[],startedAt:new Date().toISOString(),verifiedAt:bypass?new Date().toISOString():null});verificationStore.addSecurityHistory(member.guild.id,member.id,{type:'member_joined',state,requiredSecurity:required,bypass});return{handled:true,bypass,assigned:[]};}
function resetVerificationJourneyOnLeave(member,removal){if(!guildManager.isModuleEnabled(member.guild.id,'verification'))return;const section=verificationStore.getVerificationSection(member.guild.id),settings=section.settings||{};if(settings.flow?.resetActiveSessionOnLeave===false)return;const current=verificationStore.getSession(member.guild.id,member.id);if(current)verificationStore.addSecurityHistory(member.guild.id,member.id,{type:'member_left',state:current.state,sessionId:current.sessionId,removalType:removal?.key||'left'});verificationStore.resetActiveSession(member.guild.id,member.id);}

module.exports=[{name:'guildMemberAdd',async execute(member){await statsManager.handleGuildMemberAdd(member);let journey={assigned:[]};try{journey=await initialiseVerificationJourney(member);}catch(error){console.error('[verification] Failed to initialise member journey:',error);}const verificationResult=!member.user?.bot&&guildManager.isModuleEnabled(member.guild.id,'verification')?await verificationManager.handleMemberJoin(member).catch(error=>{console.error('[verification] Failed to process member join:',error);return{assigned:[]};}):{assigned:[]};const addedRoles=await autoRoleManager.applyAutoRoles(member).catch(error=>{console.error('[autoRoles] Failed to apply auto roles:',error);return[];});for(const role of [...(journey?.assigned||[]),...(verificationResult?.assigned||[])])if(!addedRoles.some(addedRole=>addedRole.id===role.id))addedRoles.push(role);const welcomeStartedAt=Date.now();const welcomeResult=guildManager.isModuleEnabled(member.guild.id,'welcome')?await welcomeManager.sendWelcome(member).catch(error=>{console.error('[Welcome] Failed to process member join:',error);return null;}):null;if(welcomeResult?.publicSent)await welcomeAvatarSync.trackLatestWelcomeMessage(member,welcomeManager,welcomeStartedAt).catch(error=>console.warn('[Welcome] Failed to track welcome message for avatar sync:',error.message||error));await sendAdminMemberJoinLog(member,addedRoles);}},{name:'guildMemberUpdate',async execute(oldMember,newMember){if(!guildManager.isModuleEnabled(newMember.guild.id,'verification'))return;await verificationManager.handleMemberUpdate(oldMember,newMember).catch(error=>console.error('[verification] Failed to process member update:',error));}},{name:'guildMemberRemove',async execute(member){await statsManager.handleGuildMemberRemove(member);const removal=await detectRemoval(member);try{resetVerificationJourneyOnLeave(member,removal);}catch(error){console.error('[verification] Failed to reset member journey on leave:',error);}if(guildManager.isModuleEnabled(member.guild.id,'goodbye')){await goodbyeDeparture.sendDepartureDm(member,removal).catch(error=>console.warn('[Goodbye] Failed to process departure DM:',error.message||error));await goodbyeDeparture.sendDeparture(member,removal).catch(error=>console.error('[Goodbye] Failed to process member departure:',error));}await sendAdminMemberRemovalLog(member,removal);}}];
