'use strict';

const {ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelSelectMenuBuilder,ChannelType,EmbedBuilder,RoleSelectMenuBuilder,UserSelectMenuBuilder,PermissionFlagsBits}=require('discord.js');
const PREFIX='permaccess:';const sessions=new Map();const cid=(a,g)=>`${PREFIX}${a}:guild:${g}`;const aid=id=>String(id||'').replace(/^permaccess:/,'').replace(/:guild:\d{16,25}$/,'');const gid=(id,i)=>String(id||'').match(/:guild:(\d{16,25})$/)?.[1]||i.guildId;const btn=(id,l,e,s=ButtonStyle.Secondary,d=false)=>new ButtonBuilder().setCustomId(id).setLabel(l).setEmoji(e).setStyle(s).setDisabled(d);
const GROUPS={Access:['ViewChannel','ReadMessageHistory'],Text:['SendMessages','AddReactions','EmbedLinks','AttachFiles','MentionEveryone','ManageMessages','ManageThreads','CreatePublicThreads','CreatePrivateThreads','SendMessagesInThreads'],Voice:['Connect','Speak','Stream','UseVAD','MuteMembers','DeafenMembers','MoveMembers'],Management:['ManageChannels','ManageRoles','ManageWebhooks','CreateInstantInvite']};
function key(i,g){return`${i.user.id}:${g.id}`;}function state(i,g){const k=key(i,g);if(!sessions.has(k))sessions.set(k,{channelId:null,subjectType:'role',roleId:null,userId:null});return sessions.get(k);}
function subject(g,s){return s.subjectType==='member'?g.members.cache.get(s.userId):g.roles.cache.get(s.roleId);}function home(g,s){const c=g.channels.cache.get(s.channelId),sub=subject(g,s);const embed=new EmbedBuilder().setColor(0x5865F2).setTitle('🧪 Effective Access Tester').setDescription(['Inspect the permissions Discord actually resolves for a role or member on a channel, then see where the important decisions come from.','',`**Subject:** ${sub?`**${sub.displayName||sub.name}** (${s.subjectType})`:'Not selected'}`,`**Channel:** ${c?`**${c.name}**`:'Not selected'}`,'','Choose either a role or member. Selecting one clears the other.'].join('\n'));const role=new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId(cid('role',g.id)).setPlaceholder('Test a role…').setMinValues(1).setMaxValues(1));const user=new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId(cid('member',g.id)).setPlaceholder('Or test a member…').setMinValues(1).setMaxValues(1));const ch=new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId(cid('channel',g.id)).setPlaceholder('Select channel/category…').setMinValues(1).setMaxValues(1).addChannelTypes(ChannelType.GuildCategory,ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildVoice,ChannelType.GuildStageVoice,ChannelType.GuildForum,ChannelType.GuildMedia));const actions=new ActionRowBuilder().addComponents(btn(cid('inspect',g.id),'Inspect Effective Access','🔎',ButtonStyle.Primary,!c||!sub),btn(`permstudio:home:guild:${g.id}`,'Back','⬅️'));return{embeds:[embed],components:[role,user,ch,actions]};}
function overwriteState(o,p){const bit=PermissionFlagsBits[p];if(!bit)return null;if(o?.allow?.has(bit))return'ALLOW';if(o?.deny?.has(bit))return'DENY';return null;}
function roleSources(g,role,c,p){const lines=[];const bit=PermissionFlagsBits[p];if(role.permissions.has(PermissionFlagsBits.Administrator))lines.push('🟣 Role has **Administrator**');else if(role.permissions.has(bit))lines.push(`🏠 Role grants **${p}**`);else lines.push(`🏠 Role does not grant **${p}**`);const eo=c.permissionOverwrites.cache.get(g.roles.everyone.id),ro=c.permissionOverwrites.cache.get(role.id);const es=overwriteState(eo,p),rs=overwriteState(ro,p);if(es)lines.push(`${es==='ALLOW'?'✅':'❌'} @everyone channel overwrite: **${es}**`);if(rs)lines.push(`${rs==='ALLOW'?'✅':'❌'} @${role.name} channel overwrite: **${rs}**`);return lines;}
function memberSources(g,m,c,p){const lines=[];const bit=PermissionFlagsBits[p],roles=[...m.roles.cache.values()];if(m.id===g.ownerId)lines.push('👑 Member is **server owner**');else if(m.permissions.has(PermissionFlagsBits.Administrator))lines.push('🟣 Member has **Administrator** through a role');else{const granting=roles.filter(r=>r.permissions.has(bit)).map(r=>r.name);lines.push(granting.length?`🏠 Guild role grant: ${granting.slice(0,4).map(x=>`@${x}`).join(', ')}`:`🏠 No assigned role grants **${p}**`);}const eo=c.permissionOverwrites.cache.get(g.roles.everyone.id),es=overwriteState(eo,p);if(es)lines.push(`${es==='ALLOW'?'✅':'❌'} @everyone overwrite: **${es}**`);const roleOver=roles.map(r=>({r,s:overwriteState(c.permissionOverwrites.cache.get(r.id),p)})).filter(x=>x.s);if(roleOver.length)lines.push(`👥 Role overwrites: ${roleOver.slice(0,5).map(x=>`@${x.r.name}=${x.s}`).join(', ')}`);const ms=overwriteState(c.permissionOverwrites.cache.get(m.id),p);if(ms)lines.push(`👤 Member overwrite: **${ms}**`);return lines;}
function inspect(g,s){const c=g.channels.cache.get(s.channelId),sub=subject(g,s),effective=c.permissionsFor(sub);const embed=new EmbedBuilder().setColor(effective?.has(PermissionFlagsBits.ViewChannel)?0x57F287:0xED4245).setTitle(`🧪 ${sub.displayName||sub.name} → ${c.name}`).setDescription(`Discord effective permissions for this ${s.subjectType}.\n${c.parent?`Parent category: **${c.parent.name}** • ${c.permissionsLocked?'🔗 synced':'⚠️ custom overrides'}`:'Category/root object'}`);for(const [name,perms] of Object.entries(GROUPS)){embed.addFields({name,value:perms.map(p=>`${effective?.has(PermissionFlagsBits[p])?'✅':'❌'} ${p}`).join('\n'),inline:true});}const explain=['ViewChannel','SendMessages','ManageMessages','Connect'].filter(p=>PermissionFlagsBits[p]).map(p=>`**${p}: ${effective?.has(PermissionFlagsBits[p])?'ALLOWED':'DENIED'}**\n${(s.subjectType==='member'?memberSources(g,sub,c,p):roleSources(g,sub,c,p)).map(x=>`↳ ${x}`).join('\n')}`).join('\n\n');embed.addFields({name:'🧭 Why? Key permission trace',value:explain.slice(0,4000)||'No trace available.',inline:false}).setFooter({text:'Final allow/deny values come from discord.js permissionsFor(), matching Discord effective permission resolution.'});return{embeds:[embed],components:[new ActionRowBuilder().addComponents(btn(cid('home',g.id),'Test Another','🧪'),btn(`permstudio:home:guild:${g.id}`,'Back to Studio','⬅️'))]};}
async function handle(i){const raw=String(i.customId||'');if(!raw.startsWith(PREFIX))return false;const gId=gid(raw,i),g=i.client.guilds.cache.get(gId)||await i.client.guilds.fetch(gId).catch(()=>null);if(!g)return false;const s=state(i,g),a=aid(raw);if(a==='home'){await i.update(home(g,s));return true;}if(a==='role'){s.subjectType='role';s.roleId=i.values[0];s.userId=null;await i.update(home(g,s));return true;}if(a==='member'){s.subjectType='member';s.userId=i.values[0];s.roleId=null;if(!g.members.cache.has(s.userId))await g.members.fetch(s.userId).catch(()=>null);await i.update(home(g,s));return true;}if(a==='channel'){s.channelId=i.values[0];await i.update(home(g,s));return true;}if(a==='inspect'){await i.update(inspect(g,s));return true;}return false;}
module.exports={PREFIX,handle,home};
