'use strict';

const {ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,RoleSelectMenuBuilder,StringSelectMenuBuilder,PermissionFlagsBits,ChannelType}=require('discord.js');
const PREFIX='permfind:';const sessions=new Map();const cid=(a,g)=>`${PREFIX}${a}:guild:${g}`;const aid=id=>String(id||'').replace(/^permfind:/,'').replace(/:guild:\d{16,25}$/,'');const gid=(id,i)=>String(id||'').match(/:guild:(\d{16,25})$/)?.[1]||i.guildId;const btn=(id,l,e,s=ButtonStyle.Secondary,d=false)=>new ButtonBuilder().setCustomId(id).setLabel(l).setEmoji(e).setStyle(s).setDisabled(d);
const PERMS=['Administrator','ManageGuild','ManageRoles','ManageChannels','ViewAuditLog','KickMembers','BanMembers','ModerateMembers','ViewChannel','SendMessages','ReadMessageHistory','AddReactions','EmbedLinks','AttachFiles','MentionEveryone','ManageMessages','ManageThreads','ManageWebhooks','Connect','Speak','Stream','MuteMembers','DeafenMembers','MoveMembers'];
function key(i,g){return`${i.user.id}:${g.id}`;}function state(i,g){const k=key(i,g);if(!sessions.has(k))sessions.set(k,{mode:'role-channels',roleId:null,permission:'ViewChannel',page:0});return sessions.get(k);}
function modeLabel(m){return m==='role-channels'?'Role → Channels':m==='roles-with'?'Roles With Permission':'@everyone → Channels';}
function home(g,s){const r=g.roles.cache.get(s.roleId);const embed=new EmbedBuilder().setColor(0x5865F2).setTitle('🔍 Permission Finder').setDescription(['Search the whole server permission structure instead of opening channels one at a time.','',`**Mode:** ${modeLabel(s.mode)}`,`**Permission:** \`${s.permission}\``,s.mode==='role-channels'?`**Role:** ${r?`@${r.name}`:'Not selected'}`:'','', '**Search modes**','• **Role → Channels** — everywhere a selected role effectively has/does not have a permission.','• **Roles With Permission** — roles that hold a guild-level permission.','• **@everyone → Channels** — channels where everyone effectively has/does not have a permission.'].filter(Boolean).join('\n'));const mode=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(cid('mode',g.id)).setPlaceholder('Search mode…').addOptions([{label:'Role → Channels',value:'role-channels',emoji:'👥',default:s.mode==='role-channels'},{label:'Roles With Permission',value:'roles-with',emoji:'🏠',default:s.mode==='roles-with'},{label:'@everyone → Channels',value:'everyone-channels',emoji:'🌐',default:s.mode==='everyone-channels'}]));const perm=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(cid('permission',g.id)).setPlaceholder(`Permission: ${s.permission}`).addOptions(PERMS.slice(0,25).map(p=>({label:p,value:p,default:p===s.permission}))));const rows=[mode,perm];if(s.mode==='role-channels')rows.push(new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId(cid('role',g.id)).setPlaceholder('Select role…').setMinValues(1).setMaxValues(1)));rows.push(new ActionRowBuilder().addComponents(btn(cid('run',g.id),'Run Search','🔍',ButtonStyle.Primary,s.mode==='role-channels'&&!r),btn(`permstudio:home:guild:${g.id}`,'Back','⬅️')));return{embeds:[embed],components:rows};}
function searchableChannels(g){return[...g.channels.cache.values()].filter(c=>[ChannelType.GuildCategory,ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildVoice,ChannelType.GuildStageVoice,ChannelType.GuildForum,ChannelType.GuildMedia].includes(c.type)).sort((a,b)=>a.rawPosition-b.rawPosition);}
function run(g,s){const bit=PermissionFlagsBits[s.permission];if(!bit)return[];if(s.mode==='roles-with')return[...g.roles.cache.values()].filter(r=>r.permissions.has(bit)).sort((a,b)=>b.position-a.position).map(r=>({ok:true,label:`@${r.name}`,detail:`position ${r.position}${r.permissions.has(PermissionFlagsBits.Administrator)&&s.permission!=='Administrator'?' • via Administrator':''}`}));const target=s.mode==='everyone-channels'?g.roles.everyone:g.roles.cache.get(s.roleId);if(!target)return[];return searchableChannels(g).map(c=>{const effective=c.permissionsFor(target);const ok=Boolean(effective?.has(bit));const o=c.permissionOverwrites.cache.get(target.id);let explicit='inherit';if(o?.allow?.has(bit))explicit='explicit allow';else if(o?.deny?.has(bit))explicit='explicit deny';return{ok,label:`${c.type===ChannelType.GuildCategory?'📁':'#'} ${c.name}`,detail:`${explicit}${c.parent?` • ${c.permissionsLocked?'synced':'custom'}`:''}`};});}
function results(g,s,filter='all'){const all=run(g,s),shown=filter==='allow'?all.filter(x=>x.ok):filter==='deny'?all.filter(x=>!x.ok):all;const pageSize=18,maxPage=Math.max(0,Math.ceil(shown.length/pageSize)-1);s.page=Math.min(s.page,maxPage);const chunk=shown.slice(s.page*pageSize,s.page*pageSize+pageSize);const embed=new EmbedBuilder().setColor(0x5865F2).setTitle(`🔍 ${modeLabel(s.mode)} • ${s.permission}`).setDescription(`Matches shown: **${shown.length}** / ${all.length}\nPage **${s.page+1}/${maxPage+1}**\n\n${chunk.length?chunk.map(x=>`${x.ok?'✅':'❌'} **${x.label}** — ${x.detail}`).join('\n'):'No results.'}`).setFooter({text:'✅ effective allow • ❌ effective deny. Explicit state is shown separately where applicable.'});const filters=new ActionRowBuilder().addComponents(btn(cid('all',g.id),'All','📋',ButtonStyle.Secondary),btn(cid('allow',g.id),'Allowed','✅',ButtonStyle.Secondary),btn(cid('deny',g.id),'Denied','❌',ButtonStyle.Secondary),btn(cid('home',g.id),'New Search','🔍'));const pages=new ActionRowBuilder().addComponents(btn(cid(`page-${filter}-${Math.max(0,s.page-1)}`,g.id),'Previous','⬅️',ButtonStyle.Secondary,s.page===0),btn(cid(`page-${filter}-${Math.min(maxPage,s.page+1)}`,g.id),'Next','➡️',ButtonStyle.Secondary,s.page>=maxPage));return{embeds:[embed],components:maxPage>0?[filters,pages]:[filters]};}
async function handle(i){const raw=String(i.customId||'');if(!raw.startsWith(PREFIX))return false;const gId=gid(raw,i),g=i.client.guilds.cache.get(gId)||await i.client.guilds.fetch(gId).catch(()=>null);if(!g)return false;const s=state(i,g),a=aid(raw);if(a==='home'){s.page=0;await i.update(home(g,s));return true;}if(a==='mode'){s.mode=i.values[0];s.page=0;await i.update(home(g,s));return true;}if(a==='permission'){s.permission=i.values[0];s.page=0;await i.update(home(g,s));return true;}if(a==='role'){s.roleId=i.values[0];s.page=0;await i.update(home(g,s));return true;}if(a==='run'||a==='all'||a==='allow'||a==='deny'){s.page=0;await i.update(results(g,s,a==='run'?'all':a));return true;}if(a.startsWith('page-')){const parts=a.split('-');s.page=Number(parts.pop())||0;const filter=parts.slice(1).join('-')||'all';await i.update(results(g,s,filter));return true;}return false;}
module.exports={PREFIX,handle,home};
