'use strict';

const { PermissionFlagsBits, ChannelType } = require('discord.js');
const panel = require('./panel');

const sessions = new Map();
const pending = new Map();
const CHANNEL_PERMISSION_NAMES = new Set(['ViewChannel','ManageChannels','ManageRoles','CreateInstantInvite','SendMessages','SendTTSMessages','ManageMessages','EmbedLinks','AttachFiles','ReadMessageHistory','MentionEveryone','UseExternalEmojis','AddReactions','UseApplicationCommands','ManageWebhooks','ManageThreads','CreatePublicThreads','CreatePrivateThreads','SendMessagesInThreads','UseExternalStickers','SendVoiceMessages','SendPolls','Connect','Speak','Stream','UseVAD','PrioritySpeaker','MuteMembers','DeafenMembers','MoveMembers','UseEmbeddedActivities','RequestToSpeak','UseSoundboard','UseExternalSounds']);

function key(i,g){return `${i.user.id}:${g.id}`;}
function state(i,g){const k=key(i,g);if(!sessions.has(k))sessions.set(k,{clipboard:null,history:[],multiTargetIds:[],multiRoleId:null,multiMemberId:null,pasteMode:'merge'});const s=sessions.get(k);if(!s.pasteMode)s.pasteMode='merge';return s;}
function actionId(id){const raw=String(id||'');if(!raw.startsWith(panel.PREFIX))return null;return raw.slice(panel.PREFIX.length).replace(/:guild:\d{16,25}$/,'');}
function guildId(id){return String(id||'').match(/:guild:(\d{16,25})$/)?.[1]||null;}
async function guildFor(i){const id=guildId(i.customId)||i.guildId;return i.client.guilds.cache.get(id)||i.client.guilds.fetch(id).catch(()=>null);}
function token(){return Math.random().toString(36).slice(2,10);}
function rememberHistory(s,item){s.history.push(item);if(s.history.length>20)s.history.shift();}

function snapshotRole(r){return{kind:'role',id:r.id,label:`@${r.name}`,permissions:r.permissions.bitfield.toString(),copiedAt:Date.now()};}
function snapshotChannel(c){return{kind:c.type===ChannelType.GuildCategory?'category':'channel',id:c.id,label:`${c.type===ChannelType.GuildCategory?'📁':'#'} ${c.name}`,copiedAt:Date.now(),overwrites:[...c.permissionOverwrites.cache.values()].map(o=>({id:o.id,type:o.type,allow:o.allow.bitfield.toString(),deny:o.deny.bitfield.toString()}))};}
function snapshotChannelRole(c,r){const o=c.permissionOverwrites.cache.get(r.id);return{kind:'channel-role',id:`${c.id}:${r.id}`,roleId:r.id,roleName:r.name,label:`${r.name} @ ${c.name}`,copiedAt:Date.now(),allow:(o?.allow?.bitfield||0n).toString(),deny:(o?.deny?.bitfield||0n).toString()};}
function snapshotChannelMember(c,m){const o=c.permissionOverwrites.cache.get(m.id);return{kind:'channel-member',id:`${c.id}:${m.id}`,memberId:m.id,memberName:m.displayName,label:`${m.displayName} @ ${c.name}`,copiedAt:Date.now(),allow:(o?.allow?.bitfield||0n).toString(),deny:(o?.deny?.bitfield||0n).toString()};}
function driftRoleIds(g,c){if(!c?.parent||c.type===ChannelType.GuildCategory)return[];const cm=c.permissionOverwrites.cache,pm=c.parent.permissionOverwrites.cache,ids=new Set([...cm.keys(),...pm.keys()]);return[...ids].filter(id=>g.roles.cache.has(id)).filter(id=>{const co=cm.get(id),po=pm.get(id);return(co?.allow?.bitfield||0n)!==(po?.allow?.bitfield||0n)||(co?.deny?.bitfield||0n)!==(po?.deny?.bitfield||0n);});}

function report(g){
 const roles=[...g.roles.cache.values()],channels=[...g.channels.cache.values()];const unsyncedChannels=channels.filter(c=>c.type!==ChannelType.GuildCategory&&c.parent&&!c.permissionsLocked),memberOverrideChannels=[],conflictChannels=[];let memberOverrides=0,roleOverrides=0;
 for(const c of channels){let hasMember=false;for(const o of c.permissionOverwrites.cache.values()){if(o.type===1){memberOverrides++;hasMember=true;}else roleOverrides++;}if(hasMember)memberOverrideChannels.push(c);const everyone=c.permissionOverwrites.cache.get(g.roles.everyone.id),roleOs=[...c.permissionOverwrites.cache.values()].filter(o=>o.type===0&&o.id!==g.roles.everyone.id),memberOs=[...c.permissionOverwrites.cache.values()].filter(o=>o.type===1),conflicts=[];if(everyone)for(const o of roleOs){const bits=everyone.deny.bitfield&o.allow.bitfield;if(bits)conflicts.push(`@everyone deny → @${g.roles.cache.get(o.id)?.name||o.id} allow: ${Object.entries(PermissionFlagsBits).filter(([,b])=>(bits&b)!==0n).map(([n])=>n).slice(0,4).join(', ')}`);}for(const o of memberOs){const member=g.members.cache.get(o.id);if(!member)continue;let roleAllow=0n,roleDeny=0n;for(const rid of member.roles.cache.keys()){const ro=c.permissionOverwrites.cache.get(rid);if(ro){roleAllow|=ro.allow.bitfield;roleDeny|=ro.deny.bitfield;}}const bits=(o.deny.bitfield&roleAllow)|(o.allow.bitfield&roleDeny);if(bits)conflicts.push(`Member ${member.displayName} directly overrides role access: ${Object.entries(PermissionFlagsBits).filter(([,b])=>(bits&b)!==0n).map(([n])=>n).slice(0,4).join(', ')}`);}if(conflicts.length)conflictChannels.push({channel:c,conflicts});}
 const withPerm=p=>roles.filter(r=>!r.managed&&r.permissions.has(p)),adminRoles=withPerm(PermissionFlagsBits.Administrator),manageGuildRoles=withPerm(PermissionFlagsBits.ManageGuild),manageRolesRoles=withPerm(PermissionFlagsBits.ManageRoles),manageChannelsRoles=withPerm(PermissionFlagsBits.ManageChannels),highImpact=new Map();for(const [label,list] of [['Administrator',adminRoles],['Manage Server',manageGuildRoles],['Manage Roles',manageRolesRoles],['Manage Channels',manageChannelsRoles]])for(const r of list){if(!highImpact.has(r.id))highImpact.set(r.id,{id:r.id,name:r.name,permissions:[]});highImpact.get(r.id).permissions.push(label);}const findings=[];for(const r of adminRoles)findings.push({severity:'critical',kind:'role',id:r.id,title:`Administrator • @${r.name}`,detail:'Role bypasses normal channel permission checks.'});for(const r of manageRolesRoles.filter(r=>!adminRoles.some(a=>a.id===r.id)))findings.push({severity:'high',kind:'role',id:r.id,title:`Manage Roles • @${r.name}`,detail:'Can modify roles below its hierarchy position.'});for(const r of manageGuildRoles.filter(r=>!adminRoles.some(a=>a.id===r.id)))findings.push({severity:'high',kind:'role',id:r.id,title:`Manage Server • @${r.name}`,detail:'Has server-wide management capability.'});for(const r of manageChannelsRoles.filter(r=>!adminRoles.some(a=>a.id===r.id)&&!manageGuildRoles.some(a=>a.id===r.id)))findings.push({severity:'medium',kind:'role',id:r.id,title:`Manage Channels • @${r.name}`,detail:'Can create, edit and remove channels.'});for(const c of unsyncedChannels)findings.push({severity:'medium',kind:'channel',id:c.id,title:`Unsynced • #${c.name}`,detail:`Differs from category ${c.parent?.name||'permissions'}.`});for(const x of conflictChannels)findings.push({severity:'high',kind:'channel',id:x.channel.id,title:`Overwrite conflict • ${x.channel.type===ChannelType.GuildCategory?'📁':'#'}${x.channel.name}`,detail:x.conflicts.slice(0,2).join(' | ')});for(const c of memberOverrideChannels)findings.push({severity:'review',kind:'channel',id:c.id,title:`Member override • ${c.type===ChannelType.GuildCategory?'📁':'#'}${c.name}`,detail:'Contains direct member-specific permission overwrite(s).'});return{roles:roles.length,categories:channels.filter(c=>c.type===ChannelType.GuildCategory).length,channels:channels.filter(c=>c.type!==ChannelType.GuildCategory).length,administrator:adminRoles.length,manageGuild:manageGuildRoles.length,manageRoles:manageRolesRoles.length,manageChannels:manageChannelsRoles.length,unsynced:unsyncedChannels.length,memberOverrides,roleOverrides,conflicts:conflictChannels.length,critical:adminRoles.length>1,findings,highImpactRoles:[...highImpact.values()],affectedChannelIds:[...new Set([...unsyncedChannels,...memberOverrideChannels,...conflictChannels.map(x=>x.channel)].map(c=>c.id))]};
}
function roleDiff(a,b){return Object.keys(PermissionFlagsBits).filter(p=>a.permissions.has(PermissionFlagsBits[p])!==b.permissions.has(PermissionFlagsBits[p])).map(p=>`${a.permissions.has(PermissionFlagsBits[p])?'✅':'❌'} **${p}** → ${b.permissions.has(PermissionFlagsBits[p])?'✅':'❌'}`);}
function overwriteMap(c){return new Map([...c.permissionOverwrites.cache.values()].map(o=>[o.id,`${o.allow.bitfield}:${o.deny.bitfield}`]));}
function channelDiff(g,a,b){const am=overwriteMap(a),bm=overwriteMap(b),ids=new Set([...am.keys(),...bm.keys()]),lines=[];for(const id of ids)if(am.get(id)!==bm.get(id))lines.push(`• **${g.roles.cache.get(id)?.name||g.members.cache.get(id)?.displayName||id}** differs`);return lines;}

async function applyClipboard(g,s,target){
 const clip=s.clipboard;if(!clip)throw new Error('Clipboard is empty.');const mode=target.mode||s.pasteMode||'merge';
 if(target.kind==='role'){const role=g.roles.cache.get(target.id);if(!role||role.managed)throw new Error('Target role cannot be edited.');if(clip.kind!=='role')throw new Error('Only a copied role can be pasted to a server role.');const before=role.permissions.bitfield.toString();await role.setPermissions(BigInt(clip.permissions),'Goliath Permissions Studio paste');return{label:`@${role.name}: role permissions pasted`,undo:{kind:'role',id:role.id,permissions:before}};}
 const channel=g.channels.cache.get(target.id);if(!channel)throw new Error('Target channel unavailable.');const before=snapshotChannel(channel);
 if(clip.kind==='channel'||clip.kind==='category'){const copied=clip.overwrites.map(o=>({id:o.id,type:o.type,allow:BigInt(o.allow),deny:BigInt(o.deny)}));if(mode==='replace')await channel.permissionOverwrites.set(copied,'Goliath Permissions Studio replace paste');else for(const o of copied)await channel.permissionOverwrites.edit(o.id,{allow:o.allow,deny:o.deny},{type:o.type,reason:`Goliath Permissions Studio merge paste from ${clip.label}`});}
 else if(clip.kind==='channel-role'){const rid=target.roleId||clip.roleId,r=g.roles.cache.get(rid);if(!r||r.managed)throw new Error('Destination role cannot be edited.');await channel.permissionOverwrites.edit(rid,{allow:BigInt(clip.allow),deny:BigInt(clip.deny)},{reason:`Goliath Permissions Studio override paste from ${clip.label}`});}
 else if(clip.kind==='channel-member'){const mid=target.memberId||clip.memberId,m=g.members.cache.get(mid)||await g.members.fetch(mid).catch(()=>null);if(!m)throw new Error('Destination member unavailable.');await channel.permissionOverwrites.edit(mid,{allow:BigInt(clip.allow),deny:BigInt(clip.deny)},{reason:`Goliath Permissions Studio member override paste from ${clip.label}`});}
 else if(clip.kind==='role'){const source=g.roles.cache.get(clip.id);if(!source)throw new Error('Copied role is unavailable in this server.');const rid=target.roleId||source.id,r=g.roles.cache.get(rid);if(!r||r.managed)throw new Error('Destination role cannot be edited.');const allow=Object.entries(PermissionFlagsBits).filter(([n,b])=>CHANNEL_PERMISSION_NAMES.has(n)&&source.permissions.has(b)).reduce((v,[,b])=>v|b,0n);await channel.permissionOverwrites.edit(rid,{allow,deny:0n},{reason:`Goliath Permissions Studio role-to-channel paste from @${source.name}`});}
 return{label:`${channel.name}: ${mode} paste from ${clip.label}${target.memberId?` → ${g.members.cache.get(target.memberId)?.displayName||target.memberId}`:''}`,undo:{kind:'channel',id:channel.id,overwrites:before.overwrites}};
}
async function undo(g,s){const item=s.history.pop();if(!item?.undo)return false;if(item.undo.kind==='role'){const r=g.roles.cache.get(item.undo.id);if(r&&!r.managed)await r.setPermissions(BigInt(item.undo.permissions),'Goliath Permissions Studio undo');}if(item.undo.kind==='channel'){const c=g.channels.cache.get(item.undo.id);if(c)await c.permissionOverwrites.set(item.undo.overwrites.map(o=>({id:o.id,type:o.type,allow:BigInt(o.allow),deny:BigInt(o.deny)})),'Goliath Permissions Studio undo');}if(item.undo.kind==='multi'){for(const x of item.undo.items){const c=g.channels.cache.get(x.id);if(c)await c.permissionOverwrites.set(x.overwrites.map(o=>({id:o.id,type:o.type,allow:BigInt(o.allow),deny:BigInt(o.deny)})),'Goliath Permissions Studio multi-paste undo');}}return true;}

async function handle(i){
 const action=actionId(i.customId);if(!action)return false;const g=await guildFor(i);if(!g){await i.reply({content:'❌ Server context unavailable.',ephemeral:true});return true;}const s=state(i,g);
 if(action==='home'){await i.update(panel.home(g,s));return true;}if(action==='audit'){await i.update(panel.audit(g));return true;}if(action==='scan'){await i.update(panel.audit(g,report(g)));return true;}
 if(action==='audit-channel'){const c=g.channels.cache.get(i.values[0]);if(!c)throw new Error('Audit channel unavailable.');const memberIds=[...c.permissionOverwrites.cache.values()].filter(o=>o.type===1).map(o=>o.id),drift=driftRoleIds(g,c);if(memberIds.length===1&&!drift.length){const m=g.members.cache.get(memberIds[0])||await g.members.fetch(memberIds[0]).catch(()=>null);if(m){await i.update(panel.channelMember(g,c,m));return true;}}if(drift.length===1){const r=g.roles.cache.get(drift[0]);await i.update(panel.driftRepair(g,c,r));}else await i.update(panel.channel(g,c,s));return true;}
 if(action==='audit-role'){const r=g.roles.cache.get(i.values[0]);if(!r)throw new Error('Audit role unavailable.');await i.update(panel.role(g,r,s));return true;}if(action==='main'||action==='role-back'){await i.update(panel.main(g));return true;}if(action==='channels'){await i.update(panel.channels(g));return true;}if(action==='clipboard'){await i.update(panel.clipboard(g,s));return true;}
 if(action==='paste-mode-merge'||action==='paste-mode-replace'){s.pasteMode=action.endsWith('replace')?'replace':'merge';await i.update(panel.pasteMany(g,s));return true;}
 if(action==='clear-clipboard'){s.clipboard=null;s.multiTargetIds=[];s.multiRoleId=null;s.multiMemberId=null;s.pasteMode='merge';await i.update(panel.clipboard(g,s));return true;}if(action==='undo'){await undo(g,s);await i.update(panel.clipboard(g,s));return true;}
 if(action==='paste-many'){s.multiTargetIds=[];s.multiRoleId=null;s.multiMemberId=null;s.pasteMode=s.pasteMode||'merge';await i.update(panel.pasteMany(g,s));return true;}if(action==='paste-many-channels'){s.multiTargetIds=i.values;await i.update(panel.pasteMany(g,s));return true;}if(action==='paste-many-role'){s.multiRoleId=i.values[0];s.multiMemberId=null;await i.update(panel.pasteMany(g,s));return true;}if(action==='paste-many-member'){s.multiMemberId=i.values[0];s.multiRoleId=null;await i.update(panel.pasteMany(g,s));return true;}
 if(action==='paste-many-preview'){const t=token();pending.set(`${key(i,g)}:${t}`,{kind:'multi',ids:[...s.multiTargetIds],roleId:s.multiRoleId,memberId:s.multiMemberId,mode:s.pasteMode||'merge'});await i.update(panel.pasteManyPreview(g,s,t));return true;}
 if(action.startsWith('paste-children-')){const category=g.channels.cache.get(action.slice(15));if(!category||category.type!==ChannelType.GuildCategory)throw new Error('Category unavailable.');const ids=[...category.children.cache.values()].map(c=>c.id);if(!ids.length)throw new Error('This category has no child channels.');s.multiTargetIds=ids;s.multiRoleId=null;s.multiMemberId=null;const t=token();pending.set(`${key(i,g)}:${t}`,{kind:'multi',ids,roleId:null,memberId:null,categoryId:category.id,mode:s.pasteMode||'merge'});await i.update(panel.pasteManyPreview(g,s,t));return true;}
 if(action.startsWith('confirm-many-')){const t=action.slice(13),pk=`${key(i,g)}:${t}`,p=pending.get(pk);if(!p)throw new Error('Multi-paste preview expired.');pending.delete(pk);await i.deferUpdate();const before=[];for(const id of p.ids){const c=g.channels.cache.get(id);if(c)before.push(snapshotChannel(c));}for(const id of p.ids)await applyClipboard(g,s,{kind:'channel',id,roleId:p.roleId,memberId:p.memberId,mode:p.mode});const remap=p.memberId?` → ${g.members.cache.get(p.memberId)?.displayName||p.memberId}`:'';rememberHistory(s,{label:`${p.categoryId?'Category child paste':'Multi-paste'} (${p.mode||'merge'}): ${s.clipboard.label}${remap} → ${before.length} destination(s)`,undo:{kind:'multi',items:before}});s.multiTargetIds=[];s.multiRoleId=null;s.multiMemberId=null;await i.editReply(panel.clipboard(g,s));return true;}
 if(action==='role-select'){const r=g.roles.cache.get(i.values[0]);await i.update(panel.role(g,r,s));return true;}if(action==='channel-select'){const c=g.channels.cache.get(i.values[0]);await i.update(panel.channel(g,c,s));return true;}if(action.startsWith('open-channel-')){const c=g.channels.cache.get(action.slice(13));await i.update(panel.channel(g,c,s));return true;}if(action.startsWith('channel-role-')){const c=g.channels.cache.get(action.slice(13)),r=g.roles.cache.get(i.values[0]);await i.update(panel.channelRole(g,c,r));return true;}if(action.startsWith('channel-member-')){const c=g.channels.cache.get(action.slice(15)),m=g.members.cache.get(i.values[0])||await g.members.fetch(i.values[0]).catch(()=>null);if(!c||!m)throw new Error('Member override target unavailable.');await i.update(panel.channelMember(g,c,m));return true;}if(action.startsWith('channel-member-open-')){const[channelId,memberId]=action.slice(20).split('-'),c=g.channels.cache.get(channelId),m=g.members.cache.get(memberId)||await g.members.fetch(memberId).catch(()=>null);if(!c||!m)throw new Error('Member override target unavailable.');await i.update(panel.channelMember(g,c,m));return true;}
 if(action.startsWith('copy-channel-member-')){const[channelId,memberId]=action.slice(20).split('-'),c=g.channels.cache.get(channelId),m=g.members.cache.get(memberId)||await g.members.fetch(memberId).catch(()=>null);if(!c||!m||!c.permissionOverwrites.cache.get(memberId))throw new Error('Member override unavailable.');s.clipboard=snapshotChannelMember(c,m);await i.update(panel.channelMember(g,c,m));return true;}if(action.startsWith('remove-member-')){const[channelId,memberId]=action.slice(14).split('-'),c=g.channels.cache.get(channelId),m=g.members.cache.get(memberId)||await g.members.fetch(memberId).catch(()=>null);if(!c||!m||!c.permissionOverwrites.cache.get(memberId))throw new Error('Member override unavailable.');const t=token();pending.set(`${key(i,g)}:${t}`,{kind:'remove-member',channelId,memberId});await i.update(panel.removeMemberPreview(g,c,m,t));return true;}if(action.startsWith('confirm-remove-member-')){const t=action.slice(22),pk=`${key(i,g)}:${t}`,p=pending.get(pk);if(!p||p.kind!=='remove-member')throw new Error('Removal preview expired.');pending.delete(pk);const c=g.channels.cache.get(p.channelId),m=g.members.cache.get(p.memberId)||await g.members.fetch(p.memberId).catch(()=>null);if(!c||!m)throw new Error('Member override target unavailable.');const before=snapshotChannel(c);await c.permissionOverwrites.delete(p.memberId,'Goliath Permissions Studio remove member override');rememberHistory(s,{label:`${c.name}: removed direct override for ${m.displayName}`,undo:{kind:'channel',id:c.id,overwrites:before.overwrites}});await i.update(panel.channel(g,c,s));return true;}
 if(action.startsWith('drift-role-')){const c=g.channels.cache.get(action.slice(11)),r=g.roles.cache.get(i.values[0]);if(!c?.parent||!r)throw new Error('Drift repair target unavailable.');await i.update(panel.driftRepair(g,c,r));return true;}if(action.startsWith('repair-drift-role-')){const[channelId,roleId]=action.slice(18).split('-'),c=g.channels.cache.get(channelId),r=g.roles.cache.get(roleId);if(!c?.parent||!r)throw new Error('Drift repair target unavailable.');const before=snapshotChannel(c),po=c.parent.permissionOverwrites.cache.get(roleId);if(po)await c.permissionOverwrites.edit(roleId,{allow:po.allow.bitfield,deny:po.deny.bitfield},{reason:`Goliath Permissions Studio selective drift repair from ${c.parent.name}`});else await c.permissionOverwrites.delete(roleId,`Goliath Permissions Studio selective drift repair from ${c.parent.name}`);rememberHistory(s,{label:`${c.name}: @${r.name} matched parent category ${c.parent.name}`,undo:{kind:'channel',id:c.id,overwrites:before.overwrites}});await i.update(panel.channel(g,c,s));return true;}
 if(action.startsWith('copy-role-')){const r=g.roles.cache.get(action.slice(10));s.clipboard=snapshotRole(r);await i.update(panel.role(g,r,s));return true;}if(action.startsWith('copy-channel-role-')){const[channelId,roleId]=action.slice(18).split('-'),c=g.channels.cache.get(channelId),r=g.roles.cache.get(roleId);s.clipboard=snapshotChannelRole(c,r);await i.update(panel.channelRole(g,c,r));return true;}if(action.startsWith('copy-channel-')){const c=g.channels.cache.get(action.slice(13));s.clipboard=snapshotChannel(c);await i.update(panel.channel(g,c,s));return true;}
 if(action.startsWith('paste-role-')){const id=action.slice(11),r=g.roles.cache.get(id),t=token();pending.set(`${key(i,g)}:${t}`,{kind:'role',id,mode:s.pasteMode||'merge'});await i.update(panel.pastePreview(g,s.clipboard,`@${r.name}`,t,'Guild-level role permissions will be replaced by the copied role permissions.',s));return true;}
 if(action.startsWith('paste-channel-role-')){const[channelId,roleId]=action.slice(19).split('-'),c=g.channels.cache.get(channelId),r=g.roles.cache.get(roleId),t=token();pending.set(`${key(i,g)}:${t}`,{kind:'channel',id:channelId,roleId,mode:s.pasteMode||'merge'});const summary=s.clipboard?.kind==='channel-role'?`Only **@${r?.name||roleId}** on **${c?.name}** will receive the copied Allow / Deny / Inherit override. Other channel overwrites stay untouched.`:s.clipboard?.kind==='role'?`The copied guild permissions will be converted to channel permissions for **@${r?.name||roleId}** on **${c?.name}**. Other overwrites stay untouched.`:'Use the channel-level Paste button for this clipboard type.';await i.update(panel.pastePreview(g,s.clipboard,`${r?.name||roleId} @ ${c?.name||channelId}`,t,summary,s));return true;}
 if(action.startsWith('paste-channel-')){const id=action.slice(14),c=g.channels.cache.get(id),t=token();pending.set(`${key(i,g)}:${t}`,{kind:'channel',id,mode:s.pasteMode||'merge'});const summary=s.clipboard?.kind==='channel-member'?`The copied member override for **${s.clipboard.memberName}** will be applied to the same member on **${c.name}**. Use Paste to Many to remap it to a different member.`:s.clipboard?.kind==='channel-role'?`The copied **${s.clipboard.roleName||'role'}** override will be applied to the same role on **${c.name}**.`:s.clipboard?.kind==='role'?`A channel overwrite will be created for **${s.clipboard.label}** using its channel-relevant guild permissions.`:(s.pasteMode==='replace'?`The full ${s.clipboard?.kind||'channel'} overwrite map will replace the overwrite map on **${c.name}**.`:`Copied overwrites will be merged into **${c.name}**; unrelated destination overwrites will be preserved.`);await i.update(panel.pastePreview(g,s.clipboard,c.name,t,summary,s));return true;}
 if(action.startsWith('confirm-')){const t=action.slice(8),pk=`${key(i,g)}:${t}`,target=pending.get(pk);if(!target)throw new Error('Paste preview expired.');pending.delete(pk);await i.deferUpdate();const h=await applyClipboard(g,s,target);rememberHistory(s,h);await i.editReply(panel.clipboard(g,s));return true;}
 if(action.startsWith('sync-channel-')){const c=g.channels.cache.get(action.slice(13));if(c?.parent){const before=snapshotChannel(c);await c.lockPermissions();rememberHistory(s,{label:`${c.name}: synced with ${c.parent.name}`,undo:{kind:'channel',id:c.id,overwrites:before.overwrites}});}await i.update(panel.channel(g,c,s));return true;}if(action.startsWith('compare-role-')){await i.update(panel.comparePicker(g,'role',action.slice(13)));return true;}if(action.startsWith('compare-channel-')){await i.update(panel.comparePicker(g,'channel',action.slice(16)));return true;}if(action.startsWith('compare-target-role-')){const a=g.roles.cache.get(action.slice(20)),b=g.roles.cache.get(i.values[0]);await i.update(panel.diff(g,`${a.name} ↔ ${b.name}`,roleDiff(a,b)));return true;}if(action.startsWith('compare-target-channel-')){const a=g.channels.cache.get(action.slice(23)),b=g.channels.cache.get(i.values[0]);await i.update(panel.diff(g,`${a.name} ↔ ${b.name}`,channelDiff(g,a,b)));return true;}return false;
}
module.exports={handle,home:(i,g)=>panel.home(g,state(i,g))};