'use strict';

const { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionFlagsBits, RoleSelectMenuBuilder, StringSelectMenuBuilder, ChannelType } = require('discord.js');
const PREFIX = 'permfinder:';
const sessions = new Map();
const id = (action, guildId) => `${PREFIX}${action}:guild:${guildId}`;
const actionFrom = customId => String(customId || '').replace(/^permfinder:/, '').replace(/:guild:\d{16,25}$/, '');
const guildFrom = (customId, interaction) => String(customId || '').match(/:guild:(\d{16,25})$/)?.[1] || interaction.guildId;
const button = (customId, label, emoji, disabled = false) => new ButtonBuilder().setCustomId(customId).setLabel(label).setEmoji(emoji).setStyle(ButtonStyle.Secondary).setDisabled(disabled);
const PERMISSIONS = ['Administrator','ManageGuild','ManageRoles','ManageChannels','ViewAuditLog','KickMembers','BanMembers','ModerateMembers','ViewChannel','SendMessages','ReadMessageHistory','AddReactions','EmbedLinks','AttachFiles','MentionEveryone','ManageMessages','ManageThreads','ManageWebhooks','Connect','Speak','Stream','MuteMembers','DeafenMembers','MoveMembers'].filter(name => PermissionFlagsBits[name] !== undefined);
function state(i,g){const k=`${i.user.id}:${g.id}`;if(!sessions.has(k))sessions.set(k,{mode:'role',roleId:null,permission:'ViewChannel',filter:'all',page:0});return sessions.get(k);}
function channels(g){const types=new Set([ChannelType.GuildCategory,ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildVoice,ChannelType.GuildStageVoice,ChannelType.GuildForum,ChannelType.GuildMedia].filter(v=>v!==undefined));return [...g.channels.cache.values()].filter(c=>types.has(c.type)&&typeof c.permissionsFor==='function').sort((a,b)=>(a.rawPosition||0)-(b.rawPosition||0));}
function home(g,s){const role=g.roles.cache.get(s.roleId);const embed=new EmbedBuilder().setColor(0x5865F2).setTitle('🔍 Permission Finder').setDescription(`Search the entire server permission structure.\n\n**Mode:** ${s.mode==='role'?'Role → Channels':s.mode==='roles'?'Roles With Permission':'@everyone → Channels'}\n**Permission:** \`${s.permission}\`${s.mode==='role'?`\n**Role:** ${role?`@${role.name}`:'Not selected'}`:''}`);const mode=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(id('mode',g.id)).setPlaceholder('Search mode').addOptions([{label:'Role → Channels',value:'role',default:s.mode==='role'},{label:'Roles With Permission',value:'roles',default:s.mode==='roles'},{label:'@everyone → Channels',value:'everyone',default:s.mode==='everyone'}]));const perm=new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(id('permission',g.id)).setPlaceholder(`Permission: ${s.permission}`).addOptions(PERMISSIONS.map(p=>({label:p,value:p,default:p===s.permission}))));const rows=[mode,perm];if(s.mode==='role')rows.push(new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId(id('role',g.id)).setPlaceholder('Select role').setMinValues(1).setMaxValues(1)));rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(id('run',g.id)).setLabel('Run Search').setEmoji('🔍').setStyle(ButtonStyle.Primary).setDisabled(s.mode==='role'&&!role),button(`permstudio:home:guild:${g.id}`,'Back','⬅️')));return{embeds:[embed],components:rows};}
function scan(g,s){const bit=PermissionFlagsBits[s.permission];if(bit===undefined)return[];if(s.mode==='roles')return[...g.roles.cache.values()].filter(r=>r.permissions.has(bit)).sort((a,b)=>b.position-a.position).map(r=>({allowed:true,name:`@${r.name}`,detail:r.permissions.has(PermissionFlagsBits.Administrator)&&s.permission!=='Administrator'?'via Administrator':'guild permission'}));const role=s.mode==='everyone'?g.roles.everyone:g.roles.cache.get(s.roleId);if(!role)return[];return channels(g).map(c=>{const allowed=Boolean(c.permissionsFor(role)?.has(bit));const overwrite=c.permissionOverwrites?.cache?.get(role.id);let explicit='inherit';if(overwrite?.allow?.has(bit))explicit='explicit allow';else if(overwrite?.deny?.has(bit))explicit='explicit deny';return{allowed,name:`${c.type===ChannelType.GuildCategory?'📁':'#'} ${c.name}`,detail:`${explicit}${c.parent?` • ${c.permissionsLocked?'synced':'custom'}`:''}`};});}
function results(g,s){const all=scan(g,s);const filtered=s.filter==='allow'?all.filter(x=>x.allowed):s.filter==='deny'?all.filter(x=>!x.allowed):all;const size=18,max=Math.max(0,Math.ceil(filtered.length/size)-1);s.page=Math.max(0,Math.min(s.page,max));const chunk=filtered.slice(s.page*size,s.page*size+size);const embed=new EmbedBuilder().setColor(0x5865F2).setTitle(`🔍 Permission Finder • ${s.permission}`).setDescription(`Showing **${filtered.length}** of **${all.length}** results • Page **${s.page+1}/${max+1}**\n\n${chunk.length?chunk.map(x=>`${x.allowed?'✅':'❌'} **${x.name}** — ${x.detail}`).join('\n'):'No results.'}`).setFooter({text:'Effective access is resolved by Discord permissionsFor(); explicit overwrite state is shown separately.'});const filterRow=new ActionRowBuilder().addComponents(button(id('all',g.id),'All','📋'),button(id('allow',g.id),'Allowed','✅'),button(id('deny',g.id),'Denied','❌'),button(id('home',g.id),'New Search','🔍'));if(!max)return{embeds:[embed],components:[filterRow]};const pageRow=new ActionRowBuilder().addComponents(button(id('prev',g.id),'Previous','⬅️',s.page===0),button(id('next',g.id),'Next','➡️',s.page>=max));return{embeds:[embed],components:[filterRow,pageRow]};}
async function handle(i){const raw=String(i.customId||'');if(!raw.startsWith(PREFIX))return false;const guildId=guildFrom(raw,i);const g=i.client.guilds.cache.get(guildId)||await i.client.guilds.fetch(guildId).catch(()=>null);if(!g)return false;const s=state(i,g),a=actionFrom(raw);if(a==='home'){s.page=0;await i.update(home(g,s));return true;}if(a==='mode'){s.mode=i.values[0];s.page=0;s.filter='all';await i.update(home(g,s));return true;}if(a==='permission'){s.permission=i.values[0];s.page=0;s.filter='all';await i.update(home(g,s));return true;}if(a==='role'){s.roleId=i.values[0];s.page=0;s.filter='all';await i.update(home(g,s));return true;}if(a==='run'){s.page=0;s.filter='all';await i.update(results(g,s));return true;}if(['all','allow','deny'].includes(a)){s.page=0;s.filter=a;await i.update(results(g,s));return true;}if(a==='prev'){s.page=Math.max(0,s.page-1);await i.update(results(g,s));return true;}if(a==='next'){s.page++;await i.update(results(g,s));return true;}return false;}
module.exports={PREFIX,handle,home};
