import React, { useEffect, useMemo, useState } from 'react';

import EmptyState from '../../shared/EmptyState.jsx';
import { api } from '../../services/apiClient.js';
import { ChannelSelect } from '../../ui/DiscordResourceSelects.jsx';

function getGuildId(selectedGuild, selectedGuildData) { return String(selectedGuildData?.guildId || selectedGuildData?.id || selectedGuild || '').split(':').pop().trim(); }
function normalizeList(payload, key) { if (Array.isArray(payload)) return payload; if (Array.isArray(payload?.[key])) return payload[key]; if (Array.isArray(payload?.data)) return payload.data; return []; }
function buttonStyle(theme, tone = 'default') { const colors = { primary: 'rgba(37,99,235,0.22)', success: 'rgba(22,163,74,0.22)', danger: 'rgba(220,38,38,0.22)', default: 'rgba(15,23,42,0.45)' }; return { border: `1px solid ${theme.cardBorder}`, background: colors[tone] || colors.default, color: theme.cardText, borderRadius: 14, padding: '11px 14px', fontWeight: 950, cursor: 'pointer' }; }
function fieldStyle(theme) { return { border: `1px solid ${theme.cardBorder}`, background: 'rgba(15,23,42,0.55)', color: theme.cardText, borderRadius: 14, padding: '12px 14px', fontWeight: 800, width: '100%' }; }
function Stat({ theme, label, value, hint }) { return <div style={{ border: `1px solid ${theme.cardBorder}`, background: 'rgba(15,23,42,0.32)', borderRadius: 18, padding: 16 }}><div style={{ color: theme.mutedText, fontSize: 11, fontWeight: 900, textTransform: 'uppercase' }}>{label}</div><div style={{ marginTop: 7, color: theme.cardText, fontSize: 27, fontWeight: 950 }}>{value}</div>{hint ? <div style={{ marginTop: 3, color: theme.mutedText, fontSize: 12 }}>{hint}</div> : null}</div>; }
function PreviewMessage({ theme, title, payload }) { if (!payload) return null; return <div style={{ border: `1px solid ${theme.cardBorder}`, borderRadius: 16, padding: 14, background: 'rgba(15,23,42,0.32)', display: 'grid', gap: 10 }}><strong>{title}</strong>{payload.content ? <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>{payload.content}</div> : null}{(payload.embeds || []).map((embed, index) => <div key={index} style={{ borderLeft: `4px solid ${embed.color ? `#${Number(embed.color).toString(16).padStart(6, '0')}` : '#5865f2'}`, background: 'rgba(2,6,23,0.48)', borderRadius: 8, padding: 14, display: 'grid', gap: 7 }}>{embed.author?.name ? <div style={{ fontSize: 12, fontWeight: 850 }}>{embed.author.name}</div> : null}{embed.title ? <strong style={{ fontSize: 16 }}>{embed.title}</strong> : null}{embed.description ? <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>{embed.description}</div> : null}{(embed.fields || []).map((field, i) => <div key={i}><strong>{field.name}</strong><div style={{ whiteSpace: 'pre-wrap', color: theme.mutedText }}>{field.value}</div></div>)}{embed.footer?.text ? <div style={{ color: theme.mutedText, fontSize: 11 }}>{embed.footer.text}</div> : null}</div>)}</div>; }
function customFromTemplate(template) { const embed = template?.embed || {}; return { content: template?.content || '', title: embed.title || '', description: embed.description === '\u200b' ? '' : (embed.description || ''), footer: embed.footer?.text || '', color: embed.color || '#5865F2' }; }
function CustomEditor({ theme, value, onChange, onSave, busy, dm = false }) { return <div style={{ border: `1px solid ${theme.cardBorder}`, borderRadius: 16, padding: 14, display: 'grid', gap: 12, background: 'rgba(2,6,23,0.28)' }}><div><strong>🛠 {dm ? 'Custom DM Welcome' : 'Custom Public Welcome'}</strong><div style={{ color: theme.mutedText, fontSize: 12, marginTop: 4 }}>Simple editor for Welcome. Guild variables such as {'{userMention}'}, {'{username}'}, {'{guild}'} and {'{memberCount}'} are resolved by the shared renderer.</div></div><label style={{ display: 'grid', gap: 6 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>MESSAGE CONTENT</span><textarea rows={3} maxLength={2000} value={value.content} onChange={(e) => onChange({ ...value, content: e.target.value })} style={fieldStyle(theme)} /></label><label style={{ display: 'grid', gap: 6 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>EMBED TITLE</span><input maxLength={256} value={value.title} onChange={(e) => onChange({ ...value, title: e.target.value })} style={fieldStyle(theme)} /></label><label style={{ display: 'grid', gap: 6 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>EMBED DESCRIPTION</span><textarea rows={6} maxLength={4096} value={value.description} onChange={(e) => onChange({ ...value, description: e.target.value })} style={fieldStyle(theme)} /></label><div style={{ display: 'grid', gridTemplateColumns: 'minmax(120px,180px) 1fr', gap: 12 }}><label style={{ display: 'grid', gap: 6 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>COLOUR</span><input type="color" value={/^#[0-9a-f]{6}$/i.test(value.color) ? value.color : '#5865F2'} onChange={(e) => onChange({ ...value, color: e.target.value })} style={{ ...fieldStyle(theme), minHeight: 46, padding: 5 }} /></label><label style={{ display: 'grid', gap: 6 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>FOOTER</span><input maxLength={2048} value={value.footer} onChange={(e) => onChange({ ...value, footer: e.target.value })} style={fieldStyle(theme)} /></label></div><div style={{ display: 'flex', justifyContent: 'flex-end' }}><button type="button" disabled={busy || (!value.content.trim() && !value.title.trim() && !value.description.trim())} onClick={onSave} style={buttonStyle(theme, 'success')}>{busy ? 'Saving...' : `Save ${dm ? 'Custom DM' : 'Custom Welcome'}`}</button></div></div>; }

export default function Welcome({ theme, selectedGuild, selectedGuildData }) {
  const guildId = getGuildId(selectedGuild, selectedGuildData);
  const [config, setConfig] = useState(null); const [scheduled, setScheduled] = useState(null); const [overview, setOverview] = useState({}); const [templates, setTemplates] = useState([]); const [binding, setBinding] = useState(null); const [channels, setChannels] = useState([]); const [roles, setRoles] = useState([]); const [queue, setQueue] = useState([]); const [preview, setPreview] = useState(null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [customPublic, setCustomPublic] = useState(customFromTemplate(null)); const [customDm, setCustomDm] = useState(customFromTemplate(null));
  const card = useMemo(() => ({ border: `1px solid ${theme.cardBorder}`, background: theme.cardBg, color: theme.cardText, borderRadius: 22, boxShadow: theme.shadow, padding: 22 }), [theme]);
  const analytics = overview.analytics || config?.analytics || {}; const health = overview.health || null; const scheduledHealth = overview.scheduledHealth || null; const messageSource = overview.messageSource || config?.messageSource || 'preset'; const dmMessageSource = overview.dmMessageSource || config?.dmMessageSource || 'inherit'; const activeTemplateId = binding?.templateId || overview.templateId || config?.templateId || 'welcome_default'; const activeTemplate = templates.find((t) => String(t.templateId) === String(activeTemplateId)) || binding || null; const dmTemplateId = overview.dmTemplateId || config?.dmTemplateId || (dmMessageSource === 'inherit' ? activeTemplateId : 'dm_welcome_default'); const dmTemplate = templates.find((t) => String(t.templateId) === String(dmTemplateId)) || null; const selectedRoleIds = Array.isArray(config?.mentionRoleIds) ? config.mentionRoleIds : []; const selectableRoles = roles.filter((r) => String(r.id) !== String(guildId) && r.managed !== true);

  async function load() { if (!guildId) return; setBusy('load'); setError(''); try { const [payload, channelPayload, rolePayload] = await Promise.all([api.request(`/api/welcome/${guildId}/overview`), api.getGuildChannels(guildId), api.getGuildRoles(guildId)]); const list = Array.isArray(payload.templates) ? payload.templates : []; setConfig(payload.config || {}); setScheduled(payload.scheduled || {}); setOverview(payload.overview || {}); setTemplates(list); setBinding(payload.binding || null); setChannels(normalizeList(channelPayload, 'channels')); setRoles(normalizeList(rolePayload, 'roles')); const pub = list.find((t) => t.templateId === 'welcome_custom_public'); const dm = list.find((t) => t.templateId === 'welcome_custom_dm'); if (pub) setCustomPublic(customFromTemplate(pub)); if (dm) setCustomDm(customFromTemplate(dm)); } catch (e) { setError(e.message || 'Failed to load Welcome.'); } finally { setBusy(''); } }
  useEffect(() => { setPreview(null); load(); }, [guildId]);
  async function act(name, fn, successText) { setBusy(name); setError(''); setNotice(''); try { const result = await fn(); if (successText) setNotice(successText); await load(); return result; } catch (e) { setError(e.message || 'Welcome action failed.'); return null; } finally { setBusy(''); } }
  async function saveInstant(patch, message = 'Instant Welcome settings saved.') { setPreview(null); setConfig({ ...(config || {}), ...patch }); return act('instant', () => api.request(`/api/welcome/${guildId}/config`, { method: 'PUT', body: JSON.stringify(patch) }), message); }
  async function saveScheduled(patch, message = 'Scheduled Welcome settings saved.') { setScheduled({ ...(scheduled || {}), ...patch }); return act('scheduled', () => api.request(`/api/welcome/${guildId}/scheduled`, { method: 'PUT', body: JSON.stringify(patch) }), message); }
  async function setMessageSource(source, templateId = '') { setPreview(null); return act('messageSource', () => api.request(`/api/welcome/${guildId}/message-source`, { method: 'POST', body: JSON.stringify({ slot: 'welcome', source, templateId }) }), source === 'preset' ? 'Welcome preset selected.' : 'Welcome message source updated.'); }
  async function setDmMessageSource(source, templateId = '') { setPreview(null); return act('dmMessageSource', () => api.request(`/api/welcome/${guildId}/message-source`, { method: 'POST', body: JSON.stringify({ slot: 'dm_welcome', source, templateId }) }), source === 'inherit' ? 'DM now uses the Public Welcome message.' : source === 'preset' ? 'DM Welcome preset selected.' : 'DM Welcome message source updated.'); }
  async function saveCustom(slot, value) { setPreview(null); return act(slot === 'dm_welcome' ? 'customDm' : 'customPublic', () => api.request(`/api/welcome/${guildId}/custom-message`, { method: 'POST', body: JSON.stringify({ slot, ...value }) }), slot === 'dm_welcome' ? 'Custom DM Welcome saved and selected.' : 'Custom Welcome saved and selected.'); }
  async function chooseCustom(slot) { const id = slot === 'dm_welcome' ? 'welcome_custom_dm' : 'welcome_custom_public'; const exists = templates.some((t) => t.templateId === id); if (exists) return slot === 'dm_welcome' ? setDmMessageSource('custom', id) : setMessageSource('custom', id); if (slot === 'dm_welcome') { setOverview({ ...overview, dmMessageSource: 'custom' }); setConfig({ ...(config || {}), dmMessageSource: 'custom' }); } else { setOverview({ ...overview, messageSource: 'custom' }); setConfig({ ...(config || {}), messageSource: 'custom' }); } setNotice('Fill in the Custom Welcome editor below, then save it.'); }
  async function previewWelcome() { setBusy('preview'); setError(''); setNotice(''); try { const result = await api.request(`/api/welcome/${guildId}/preview`, { method: 'POST', body: JSON.stringify({ userId: selectedGuildData?.userId }) }); setPreview(result.preview || null); setNotice('Private Welcome preview generated. Nothing was posted to Discord.'); } catch (e) { setError(e.message || 'Failed to generate Welcome preview.'); } finally { setBusy(''); } }
  async function previewQueue() { setBusy('queue'); setError(''); try { const result = await api.request(`/api/welcome/${guildId}/scheduled/queue`); setQueue(Array.isArray(result.members) ? result.members : []); setNotice(`Scheduled Welcome queue contains ${result.count || 0} member(s).`); } catch (e) { setError(e.message || 'Failed to load queue.'); } finally { setBusy(''); } }
  async function resetModule() { if (!window.confirm('Reset Instant and Scheduled Welcome settings and analytics?')) return; await act('reset', () => api.request(`/api/welcome/${guildId}/reset`, { method: 'POST' }), 'Welcome reset to defaults.'); setQueue([]); setPreview(null); }

  if (!guildId) return <EmptyState theme={theme} icon="👋" title="Select a server" description="Select a server to manage Welcome." />;
  const customIds = ['welcome_default', 'dm_welcome_default', 'welcome_custom_public', 'welcome_custom_dm'];
  return <div style={{ display: 'grid', gap: 18 }}>
    <section style={{ ...card, background: 'linear-gradient(135deg, rgba(52,211,153,0.18), rgba(15,23,42,0.08) 48%, rgba(59,130,246,0.14))' }}><div style={{ color: '#86efac', fontWeight: 950, textTransform: 'uppercase', letterSpacing: '0.08em' }}>Goliath Message Studio</div><h1 style={{ margin: '8px 0 0', fontSize: 'clamp(28px,4vw,42px)' }}>Welcome</h1><p style={{ color: theme.mutedText, lineHeight: 1.6 }}>Choose when Welcome runs and which message it delivers. Use Embed Studio for full design, a Goliath preset for speed, or build a simple Custom Welcome here.</p></section>
    {(error || notice) ? <section style={{ ...card, color: error ? '#fca5a5' : '#86efac', fontWeight: 850 }}>{error || notice}</section> : null}
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,170px),1fr))', gap: 12 }}><Stat theme={theme} label="Welcome" value={overview.enabled || config?.enabled ? 'Enabled' : 'Disabled'} /><Stat theme={theme} label="Instant Sent" value={analytics.publicSent || 0} hint={`${analytics.dmSent || 0} DM`} /><Stat theme={theme} label="Message Source" value={messageSource === 'embedStudio' ? 'Embed Studio' : messageSource === 'custom' ? 'Custom' : 'Preset'} /><Stat theme={theme} label="Scheduled" value={scheduled?.enabled ? 'Enabled' : 'Disabled'} hint={`${scheduledHealth?.waitingMembers || 0} waiting`} /><Stat theme={theme} label="Instant Health" value={health?.healthy ? 'Healthy' : 'Attention'} /><Stat theme={theme} label="Scheduled Health" value={scheduledHealth?.healthy ? 'Healthy' : 'Attention'} /></section>

    <section style={{ ...card, display: 'grid', gap: 16 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><h2 style={{ margin: 0 }}>⚡ Instant Welcome</h2><p style={{ margin: '6px 0 0', color: theme.mutedText }}>Runs immediately from the Discord member-join event.</p></div><button type="button" disabled={busy} onClick={() => saveInstant({ enabled: !(overview.enabled || config?.enabled) }, overview.enabled || config?.enabled ? 'Welcome disabled.' : 'Welcome enabled.')} style={buttonStyle(theme, 'primary')}>{overview.enabled || config?.enabled ? 'Disable Welcome' : 'Enable Welcome'}</button></div>
      <ChannelSelect theme={theme} resources={channels} value={config?.channelId || ''} onChange={(value) => saveInstant({ channelId: value || null })} label="Instant Welcome Channel" />
      <div style={{ border: `1px solid ${theme.cardBorder}`, background: 'rgba(15,23,42,0.28)', borderRadius: 18, padding: 16, display: 'grid', gap: 14 }}>
        <div><strong>💬 Welcome Message</strong><div style={{ color: theme.mutedText, fontSize: 12, marginTop: 4 }}>Every source uses the same canonical delivery renderer.</div></div>
        <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>MESSAGE SOURCE</span><select value={messageSource} onChange={(e) => { const source = e.target.value; if (source === 'preset') setMessageSource('preset'); else if (source === 'custom') chooseCustom('welcome'); else { const first = templates.find((t) => !customIds.includes(String(t.templateId))); if (!first) setError('Create or save an Embed Studio message first.'); else setMessageSource('embedStudio', !customIds.includes(String(activeTemplateId)) ? activeTemplateId : first.templateId); } }} disabled={busy} style={fieldStyle(theme)}><option value="embedStudio">💎 Embed Studio</option><option value="preset">📦 Welcome Preset</option><option value="custom">🛠 Custom Welcome</option></select></label>
        {messageSource === 'embedStudio' ? <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>SAVED MESSAGE</span><select value={activeTemplateId} onChange={(e) => setMessageSource('embedStudio', e.target.value)} disabled={busy} style={fieldStyle(theme)}>{templates.filter((t) => !customIds.includes(String(t.templateId))).map((t) => <option key={t.templateId} value={t.templateId}>{t.name || t.templateId}</option>)}</select></label> : null}
        {messageSource === 'preset' ? <div style={{ color: theme.mutedText }}><strong style={{ color: theme.cardText }}>📦 Goliath Welcome Preset</strong><br />Uses the built-in Welcome preset through the shared renderer.</div> : null}
        {messageSource === 'custom' ? <CustomEditor theme={theme} value={customPublic} onChange={setCustomPublic} onSave={() => saveCustom('welcome', customPublic)} busy={busy === 'customPublic'} /> : null}
        {activeTemplate ? <div><span style={{ color: theme.mutedText, fontSize: 12 }}>ACTIVE MESSAGE</span><div style={{ marginTop: 4, fontWeight: 950 }}>{activeTemplate.name || activeTemplate.templateId}</div></div> : null}
      </div>

      <div style={{ border: `1px solid ${theme.cardBorder}`, background: 'rgba(15,23,42,0.28)', borderRadius: 18, padding: 16, display: 'grid', gap: 14 }}>
        <div><strong>📨 Direct Message</strong><div style={{ color: theme.mutedText, fontSize: 12, marginTop: 4 }}>Follow Public Welcome or use a separate DM message.</div></div><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={config?.dmEnabled === true} onChange={(e) => saveInstant({ dmEnabled: e.target.checked })} /> Send DM Welcome</label>
        <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>DM MESSAGE SOURCE</span><select value={dmMessageSource} onChange={(e) => { const source = e.target.value; if (source === 'inherit') setDmMessageSource('inherit'); else if (source === 'preset') setDmMessageSource('preset'); else if (source === 'custom') chooseCustom('dm_welcome'); else { const first = templates.find((t) => !customIds.includes(String(t.templateId))); if (!first) setError('Create or save an Embed Studio message first.'); else setDmMessageSource('embedStudio', !customIds.includes(String(dmTemplateId)) ? dmTemplateId : first.templateId); } }} disabled={busy} style={fieldStyle(theme)}><option value="inherit">↩ Same as Public</option><option value="embedStudio">💎 Embed Studio</option><option value="preset">📦 Welcome Preset</option><option value="custom">🛠 Custom Welcome</option></select></label>
        {dmMessageSource === 'embedStudio' ? <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>DM SAVED MESSAGE</span><select value={dmTemplateId} onChange={(e) => setDmMessageSource('embedStudio', e.target.value)} disabled={busy} style={fieldStyle(theme)}>{templates.filter((t) => !customIds.includes(String(t.templateId))).map((t) => <option key={t.templateId} value={t.templateId}>{t.name || t.templateId}</option>)}</select></label> : null}
        {dmMessageSource === 'inherit' ? <div style={{ color: theme.mutedText }}><strong style={{ color: theme.cardText }}>↩ Same as Public Welcome</strong><br />Public message changes automatically apply to DM Welcome.</div> : null}{dmMessageSource === 'preset' ? <div style={{ color: theme.mutedText }}><strong style={{ color: theme.cardText }}>📦 Goliath DM Welcome Preset</strong><br />Uses the DM-specific preset through the shared renderer.</div> : null}{dmMessageSource === 'custom' ? <CustomEditor theme={theme} value={customDm} onChange={setCustomDm} onSave={() => saveCustom('dm_welcome', customDm)} busy={busy === 'customDm'} dm /> : null}
        <div><span style={{ color: theme.mutedText, fontSize: 12 }}>ACTIVE DM MESSAGE</span><div style={{ marginTop: 4, fontWeight: 950 }}>{dmMessageSource === 'inherit' ? `Same as Public · ${activeTemplate?.name || activeTemplateId}` : overview.dmTemplateName || dmTemplate?.name || dmTemplateId || 'Not set'}</div></div>
      </div>

      <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap' }}><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={config?.allowUserPing !== false} onChange={(e) => saveInstant({ allowUserPing: e.target.checked })} /> Ping new member</label><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={config?.allowRolePings === true} disabled={selectedRoleIds.length === 0} onChange={(e) => saveInstant({ allowRolePings: e.target.checked })} /> Ping selected roles</label><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={config?.ignoreBots !== false} onChange={(e) => saveInstant({ ignoreBots: e.target.checked })} /> Ignore bots</label></div>
      <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>INSTANT NOTIFICATION ROLES</span><select multiple size={Math.min(8, Math.max(4, selectableRoles.length))} value={selectedRoleIds} onChange={(e) => { const mentionRoleIds = Array.from(e.target.selectedOptions).map((o) => o.value).slice(0, 10); saveInstant({ mentionRoleIds, ...(mentionRoleIds.length === 0 ? { allowRolePings: false } : {}) }, 'Instant notification roles saved.'); }} disabled={busy || selectableRoles.length === 0} style={{ ...fieldStyle(theme), minHeight: 120 }}>{selectableRoles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><button type="button" disabled={busy} onClick={previewWelcome} style={buttonStyle(theme, 'primary')}>{busy === 'preview' ? 'Generating Preview...' : 'Preview'}</button><button type="button" disabled={busy || (!config?.channelId && !config?.dmEnabled)} onClick={() => act('test', () => api.request(`/api/welcome/${guildId}/test`, { method: 'POST', body: JSON.stringify({ userId: selectedGuildData?.userId }) }), 'Test Welcome delivered.')} style={buttonStyle(theme, 'success')}>Send Test</button><button type="button" disabled={busy} onClick={() => act('repair', () => api.request(`/api/welcome/${guildId}/repair`, { method: 'POST' }), 'Welcome configuration repaired.')} style={buttonStyle(theme, 'primary')}>Repair All</button></div>
      {preview ? <div style={{ border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 16, display: 'grid', gap: 12 }}><div><strong>👁 Private Preview</strong><div style={{ color: theme.mutedText, fontSize: 12, marginTop: 4 }}>Dashboard only. No Discord message or DM is sent and analytics are untouched.</div></div><PreviewMessage theme={theme} title="Public Welcome" payload={preview.public} /><PreviewMessage theme={theme} title="DM Welcome" payload={preview.dm} /></div> : null}
    </section>

    <section style={{ ...card, display: 'grid', gap: 16 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><h2 style={{ margin: 0 }}>📅 Scheduled Welcome</h2><p style={{ margin: '6px 0 0', color: theme.mutedText }}>Finds members by queue role, welcomes them in safe batches, then removes that role after successful delivery.</p></div><button type="button" disabled={busy || (!scheduled?.queueRoleId || !scheduled?.channelId)} onClick={() => saveScheduled({ enabled: !scheduled?.enabled }, scheduled?.enabled ? 'Scheduled Welcome disabled.' : 'Scheduled Welcome enabled.')} style={buttonStyle(theme, scheduled?.enabled ? 'default' : 'success')}>{scheduled?.enabled ? 'Disable Scheduled' : 'Enable Scheduled'}</button></div>
      <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontSize: 12, fontWeight: 900 }}>WELCOME QUEUE ROLE</span><select value={scheduled?.queueRoleId || ''} onChange={(e) => saveScheduled({ queueRoleId: e.target.value || null, completedMemberIds: [] })} style={fieldStyle(theme)}><option value="">Select a role</option>{selectableRoles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><ChannelSelect theme={theme} resources={channels} value={scheduled?.channelId || ''} onChange={(value) => saveScheduled({ channelId: value || null })} label="Scheduled Welcome Channel" />
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,220px),1fr))', gap: 12 }}><label style={{ display: 'grid', gap: 7 }}><span style={{ color: theme.mutedText, fontWeight: 850 }}>Daily time</span><input value={scheduled?.time || '19:00'} onChange={(e) => setScheduled({ ...(scheduled || {}), time: e.target.value })} onBlur={(e) => saveScheduled({ time: e.target.value })} placeholder="19:00" style={fieldStyle(theme)} /></label><label style={{ display: 'grid', gap: 7 }}><span style={{ color: theme.mutedText, fontWeight: 850 }}>Timezone</span><input value={scheduled?.timezone || 'Europe/London'} onChange={(e) => setScheduled({ ...(scheduled || {}), timezone: e.target.value })} onBlur={(e) => saveScheduled({ timezone: e.target.value })} placeholder="Europe/London" style={fieldStyle(theme)} /></label></div>
      <label style={{ display: 'grid', gap: 8 }}><span style={{ color: theme.mutedText, fontWeight: 850 }}>Scheduled message</span><textarea value={scheduled?.message || ''} onChange={(e) => setScheduled({ ...(scheduled || {}), message: e.target.value })} onBlur={(e) => saveScheduled({ message: e.target.value })} rows={6} maxLength={1800} style={fieldStyle(theme)} /><span style={{ color: theme.mutedText, fontSize: 12 }}>Variables: {'{members}'} {'{memberNames}'} {'{memberCount}'} {'{server}'} {'{role}'} {'{date}'}</span></label>
      <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap' }}><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={scheduled?.pingMembers !== false} onChange={(e) => saveScheduled({ pingMembers: e.target.checked })} /> Ping members</label><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={scheduled?.removeQueueRole !== false} onChange={(e) => saveScheduled({ removeQueueRole: e.target.checked })} /> Remove queue role after send</label><label style={{ color: theme.mutedText, fontWeight: 850 }}><input type="checkbox" checked={scheduled?.ignoreBots !== false} onChange={(e) => saveScheduled({ ignoreBots: e.target.checked })} /> Ignore bots</label></div>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><button type="button" disabled={busy} onClick={previewQueue} style={buttonStyle(theme)}>Preview Queue</button><button type="button" disabled={busy || !scheduled?.queueRoleId || !scheduled?.channelId} onClick={() => act('run', () => api.request(`/api/welcome/${guildId}/scheduled/run`, { method: 'POST' }), 'Scheduled Welcome run complete.')} style={buttonStyle(theme, 'success')}>Run Now</button><button type="button" disabled={busy} onClick={() => act('scheduledRepair', () => api.request(`/api/welcome/${guildId}/scheduled/repair`, { method: 'POST' }), 'Scheduled Welcome repaired.')} style={buttonStyle(theme, 'primary')}>Repair Scheduled</button></div>
      {queue.length ? <div style={{ border: `1px solid ${theme.cardBorder}`, borderRadius: 16, padding: 14 }}><strong>Waiting members ({queue.length})</strong><div style={{ marginTop: 8, color: theme.mutedText }}>{queue.slice(0, 50).map((m) => m.displayName || m.username).join(', ')}</div></div> : null}<div style={{ color: scheduledHealth?.healthy ? '#86efac' : '#fbbf24', fontWeight: 850 }}>{scheduledHealth?.healthy ? '✅ Scheduled Welcome is healthy.' : `⚠ ${(scheduledHealth?.issues || []).join(' · ') || 'Scheduled Welcome needs attention.'}`}</div>
    </section>
    <section style={{ ...card, display: 'flex', gap: 10, flexWrap: 'wrap' }}><a href={`/api/welcome/${guildId}/export`} style={{ ...buttonStyle(theme), textDecoration: 'none' }}>Export Welcome JSON</a><button type="button" disabled={busy} onClick={resetModule} style={buttonStyle(theme, 'danger')}>Reset All Welcome</button><button type="button" disabled={busy === 'load'} onClick={load} style={buttonStyle(theme)}>{busy === 'load' ? 'Refreshing...' : 'Refresh'}</button></section>
  </div>;
}
