'use strict';

const fs = require('fs');
const path = require('path');
const { PROJECT_ROOT, getRuntimePaths } = require('../../config/runtimePaths');

const paths = getRuntimePaths(process.env.BOT_MODE || 'DEV');
const root = path.join(paths.data, 'audit');
const HISTORY_LIMIT = 100;
const LEGACY_CONFIG_FILE = path.join(root, 'config.json');
const SHARED_ROOT = path.dirname(PROJECT_ROOT);
const SHARED_CONFIG_FILE = path.join(SHARED_ROOT, '.goliath-audit-control.json');
const COMMAND_CENTER_GUILD_ID = '1515201360386068642';
const REGISTRY_MODES = ['DEV', 'BETA', 'PRODUCTION'];
const LIVE_PROBE_REQUEST_LIMIT = 25;
const LIVE_PROBE_TTL_MS = 30 * 1000;
const REMOTE_COMMAND_LIMIT = 100;
const REMOTE_COMMAND_TTL_MS = 5 * 60 * 1000;

function runtimeMode() { const mode=String(process.env.BOT_MODE || 'DEV').trim().toUpperCase(); if (mode==='PROD'||mode==='PRODUCTION') return 'PRODUCTION'; if (mode==='BETA') return 'BETA'; return 'DEV'; }
function registryFile(mode=runtimeMode()) { return path.join(SHARED_ROOT, `.goliath-audit-registry-${String(mode).toLowerCase()}.json`); }
function scopedGuildIds(mode) { const envName=mode==='PRODUCTION'?'PRODUCTION_GUILD_IDS':`${mode}_GUILD_IDS`; return String(process.env[envName]||'').split(',').map(v=>v.trim()).filter(Boolean); }
function ensure(dir){fs.mkdirSync(dir,{recursive:true});return dir;} function readJson(file,fallback={}){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}} function writeJson(file,value){ensure(path.dirname(file));fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,'utf8');} function monthKey(date=new Date()){return date.toISOString().slice(0,7);}
function defaultConfig(){return{version:1,commandCenter:{guildId:COMMAND_CENTER_GUILD_ID,categoryId:null,channelId:null,messageId:null,layoutMode:'owner-managed',channelName:null,categoryName:null},autoProvision:true,guilds:{},control:{liveProbeRequests:[],remoteCommands:[]}};}
function normalizeConfig(current={}){return{...defaultConfig(),...current,commandCenter:{...defaultConfig().commandCenter,...(current.commandCenter||{}),guildId:String(current.commandCenter?.guildId||COMMAND_CENTER_GUILD_ID).trim()},guilds:current.guilds&&typeof current.guilds==='object'?current.guilds:{},control:{...defaultConfig().control,...(current.control&&typeof current.control==='object'?current.control:{}),liveProbeRequests:Array.isArray(current.control?.liveProbeRequests)?current.control.liveProbeRequests:[],remoteCommands:Array.isArray(current.control?.remoteCommands)?current.control.remoteCommands:[]}};}
function bootstrapSharedConfig(){if(fs.existsSync(SHARED_CONFIG_FILE))return;if(runtimeMode()!=='DEV')return;const legacy=readJson(LEGACY_CONFIG_FILE,null);writeJson(SHARED_CONFIG_FILE,normalizeConfig(legacy||defaultConfig()));}
function getConfig(){bootstrapSharedConfig();if(fs.existsSync(SHARED_CONFIG_FILE))return normalizeConfig(readJson(SHARED_CONFIG_FILE,defaultConfig()));return normalizeConfig(readJson(LEGACY_CONFIG_FILE,defaultConfig()));}
function saveConfig(config){const next=normalizeConfig(config||{});if(runtimeMode()==='DEV')writeJson(SHARED_CONFIG_FILE,next);else if(!fs.existsSync(SHARED_CONFIG_FILE))writeJson(LEGACY_CONFIG_FILE,next);return next;}
function updateConfig(patch={}){const current=getConfig();const next={...current,...patch,commandCenter:patch.commandCenter?{...current.commandCenter,...patch.commandCenter}:current.commandCenter,guilds:patch.guilds?{...current.guilds,...patch.guilds}:current.guilds,control:patch.control?{...current.control,...patch.control}:current.control};return saveConfig(next);}
function mutateControl(key,limit,mutator){const current=getConfig();const list=Array.isArray(current.control?.[key])?current.control[key]:[];const next=mutator([...list]);const config=normalizeConfig({...current,control:{...(current.control||{}),[key]:(Array.isArray(next)?next:list).slice(-limit)}});writeJson(SHARED_CONFIG_FILE,config);return config.control[key];}
function writeSharedControlRequests(requests){return mutateControl('liveProbeRequests',LIVE_PROBE_REQUEST_LIMIT,()=>requests);}
function liveProbeTerminalAt(r){return Date.parse(r?.completedAt||r?.failedAt||r?.expiredAt||'')||0;} function normalizeLiveProbeLifecycle(r,now=Date.now()){if(!r||typeof r!=='object')return r;const s=String(r.status||'pending').toLowerCase(),e=Date.parse(r.expiresAt||'')||0;if((s==='pending'||s==='claimed')&&e&&e<=now)return{...r,status:'expired',expiredAt:r.expiredAt||new Date(now).toISOString(),result:r.result||{started:false,reason:'expired'}};return r;}
function mutateLiveProbeRequests(mutator){const now=Date.now(),current=getConfig().control?.liveProbeRequests||[];const active=current.map(r=>normalizeLiveProbeLifecycle(r,now)).filter(r=>{const s=String(r?.status||'pending').toLowerCase();if(!['completed','failed','expired'].includes(s))return true;const at=liveProbeTerminalAt(r);return!at||now-at<LIVE_PROBE_TTL_MS;});return writeSharedControlRequests(mutator([...active]));}
function refreshLiveProbeLifecycle(){return mutateLiveProbeRequests(r=>r);} function createLiveProbeRequest(guildId,targetMode,requestedBy=null){const guild=String(guildId||'').trim(),target=String(targetMode||'').trim().toUpperCase();if(!guild||!REGISTRY_MODES.includes(target))return null;const now=Date.now(),request={id:`${now.toString(36)}-${Math.random().toString(36).slice(2,9)}`,guildId:guild,targetMode:target,requestedBy:requestedBy?String(requestedBy):null,requestedFrom:runtimeMode(),status:'pending',createdAt:new Date(now).toISOString(),expiresAt:new Date(now+LIVE_PROBE_TTL_MS).toISOString(),claimedAt:null,claimedBy:null,completedAt:null,completedBy:null,failedAt:null,failedBy:null,expiredAt:null,result:null};mutateLiveProbeRequests(r=>[...r,request]);return request;}
function getLiveProbeRequest(id){return refreshLiveProbeLifecycle().find(r=>String(r?.id||'')===String(id||''))||null;} function getPendingLiveProbeRequests(mode=runtimeMode()){const target=String(mode).toUpperCase();return refreshLiveProbeLifecycle().filter(r=>r?.status==='pending'&&String(r.targetMode||'').toUpperCase()===target);}
function claimLiveProbeRequest(id,claimedBy=runtimeMode()){const mode=String(claimedBy).toUpperCase();let claimed=null;mutateLiveProbeRequests(rs=>rs.map(r=>{if(String(r?.id||'')!==String(id)||r.status!=='pending'||String(r.targetMode||'').toUpperCase()!==mode)return r;claimed={...r,status:'claimed',claimedAt:new Date().toISOString(),claimedBy:mode};return claimed;}));return claimed;}
function completeLiveProbeRequest(id,result={},completedBy=runtimeMode()){const mode=String(completedBy).toUpperCase();let completed=null;mutateLiveProbeRequests(rs=>rs.map(r=>{if(String(r?.id||'')!==String(id))return r;const owner=String(r.claimedBy||r.targetMode||'').toUpperCase();if(!['claimed','pending'].includes(r.status)||owner!==mode)return r;completed={...r,status:'completed',completedAt:new Date().toISOString(),completedBy:mode,failedAt:null,failedBy:null,result:result&&typeof result==='object'?result:{started:false,reason:'invalid-result'}};return completed;}));return completed;}
function failLiveProbeRequest(id,result={},failedBy=runtimeMode()){const mode=String(failedBy).toUpperCase();let failed=null;mutateLiveProbeRequests(rs=>rs.map(r=>{if(String(r?.id||'')!==String(id))return r;const owner=String(r.claimedBy||r.targetMode||'').toUpperCase();if(!['claimed','pending'].includes(r.status)||owner!==mode)return r;failed={...r,status:'failed',failedAt:new Date().toISOString(),failedBy:mode,result:result&&typeof result==='object'?result:{started:false,reason:'invalid-result'}};return failed;}));return failed;}
function normalizeRemoteCommands(now=Date.now()){return mutateControl('remoteCommands',REMOTE_COMMAND_LIMIT,commands=>commands.map(c=>{const status=String(c.status||'pending');const expires=Date.parse(c.expiresAt||'')||0;if(['pending','claimed'].includes(status)&&expires&&expires<=now)return{...c,status:'expired',expiredAt:new Date(now).toISOString(),result:{ok:false,reason:'expired'}};return c;}).filter(c=>{if(!['completed','failed','expired'].includes(String(c.status)))return true;const at=Date.parse(c.completedAt||c.failedAt||c.expiredAt||'')||0;return!at||now-at<REMOTE_COMMAND_TTL_MS;}));}
function createRemoteCommand(guildId,targetMode,action,payload={},requestedBy=null){const guild=String(guildId||''),target=String(targetMode||'').toUpperCase(),name=String(action||'');if(!guild||!REGISTRY_MODES.includes(target)||!name)return null;const now=Date.now();const command={id:`cmd-${now.toString(36)}-${Math.random().toString(36).slice(2,8)}`,guildId:guild,targetMode:target,action:name,payload:payload&&typeof payload==='object'?payload:{},requestedBy:requestedBy?String(requestedBy):null,requestedFrom:runtimeMode(),status:'pending',createdAt:new Date(now).toISOString(),expiresAt:new Date(now+REMOTE_COMMAND_TTL_MS).toISOString(),claimedAt:null,completedAt:null,failedAt:null,result:null};mutateControl('remoteCommands',REMOTE_COMMAND_LIMIT,items=>[...items,command]);return command;}
function getRemoteCommand(id){return normalizeRemoteCommands().find(c=>String(c.id)===String(id))||null;} function getPendingRemoteCommands(mode=runtimeMode()){const target=String(mode).toUpperCase();return normalizeRemoteCommands().filter(c=>c.status==='pending'&&String(c.targetMode).toUpperCase()===target);}
function claimRemoteCommand(id,mode=runtimeMode()){let found=null;mutateControl('remoteCommands',REMOTE_COMMAND_LIMIT,items=>items.map(c=>{if(String(c.id)!==String(id)||c.status!=='pending'||String(c.targetMode).toUpperCase()!==String(mode).toUpperCase())return c;found={...c,status:'claimed',claimedAt:new Date().toISOString(),claimedBy:String(mode).toUpperCase()};return found;}));return found;}
function finishRemoteCommand(id,result={},failed=false,mode=runtimeMode()){let found=null;mutateControl('remoteCommands',REMOTE_COMMAND_LIMIT,items=>items.map(c=>{if(String(c.id)!==String(id)||!['pending','claimed'].includes(c.status))return c;if(String(c.targetMode).toUpperCase()!==String(mode).toUpperCase())return c;found={...c,status:failed?'failed':'completed',[failed?'failedAt':'completedAt']:new Date().toISOString(),completedBy:String(mode).toUpperCase(),result:result&&typeof result==='object'?result:{ok:!failed}};return found;}));return found;}
function registryGuild(guild,observedAt){if(!guild?.id)return null;return{guildId:String(guild.id),name:guild.name||String(guild.id),ownerId:guild.ownerId||null,memberCount:Number.isFinite(guild.memberCount)?guild.memberCount:null,observedAt};}
function publishGuildRegistry(client){if(!client?.guilds?.cache)return null;const observedAt=new Date().toISOString(),mode=runtimeMode(),guilds=[...client.guilds.cache.values()].map(g=>registryGuild(g,observedAt)).filter(Boolean).sort((a,b)=>String(a.name).localeCompare(String(b.name)));const snapshot={version:2,environment:mode,botUserId:client.user?.id||null,botTag:client.user?.tag||null,observedAt,guilds};writeJson(registryFile(mode),snapshot);return snapshot;}
function getGuildRegistry(){const merged=new Map();for(const mode of REGISTRY_MODES){const snapshot=readJson(registryFile(mode),null);if(!snapshot||!Array.isArray(snapshot.guilds))continue;for(const item of snapshot.guilds){if(!item?.guildId)continue;const id=String(item.guildId),current=merged.get(id)||{guildId:id,name:item.name||id,ownerId:item.ownerId||null,memberCount:item.memberCount??null,environments:{},lastSeenAt:null};current.name=item.name||current.name;current.ownerId=item.ownerId||current.ownerId;if(item.memberCount!=null)current.memberCount=item.memberCount;current.environments[mode]={botUserId:snapshot.botUserId||null,botTag:snapshot.botTag||null,observedAt:item.observedAt||snapshot.observedAt||null};const seen=item.observedAt||snapshot.observedAt||null;if(seen&&(!current.lastSeenAt||seen>current.lastSeenAt))current.lastSeenAt=seen;merged.set(id,current);}}
for(const mode of REGISTRY_MODES)for(const id of scopedGuildIds(mode)){const current=merged.get(id)||{guildId:id,name:id,ownerId:null,memberCount:null,environments:{},lastSeenAt:null};current.environments[mode]||={botUserId:null,botTag:null,observedAt:null,source:'configured-scope'};merged.set(id,current);}return[...merged.values()].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));}
function pushUnique(items,value,key=(item)=>JSON.stringify(item),limit=HISTORY_LIMIT){if(value==null)return items;const list=Array.isArray(items)?items:[],identity=key(value),filtered=list.filter(item=>key(item)!==identity);filtered.push(value);return filtered.slice(-limit);} function increment(map,key){if(key)map[key]=Number(map[key]||0)+1;} function eventSummary(event){return{eventId:event.eventId||null,timestamp:event.timestamp||null,type:event.type||'unknown',category:event.category||'system',action:event.action||'observe',title:event.title||event.type||'Audit Event',guildId:event.guildId||null,guildName:event.guildName||null,channelId:event.channel?.id||null,channelName:event.channel?.name||null,reason:event.reason||null,relation:event.relation||'subject'};}
function appendEvent(event){const guildId=String(event.guildId||'system'),file=path.join(ensure(path.join(root,'events',guildId)),`${monthKey(new Date(event.timestamp||Date.now()))}.jsonl`);fs.appendFileSync(file,`${JSON.stringify(event)}\n`,'utf8');updateGuildIndex(event);if(event.user?.id)updateUserIndex(event.user.id,event);if(event.actor?.id){if(event.actor.id!==event.user?.id)updateUserIndex(event.actor.id,{...event,relation:'actor'});else updateActorHistoryOnly(event.actor.id,event);}return event;}
function updateGuildIndex(event){if(!event.guildId)return;const file=path.join(root,'guilds',`${event.guildId}.json`),current=readJson(file,{guildId:event.guildId,guildName:event.guildName||null,firstObservedAt:event.timestamp,eventCount:0,lastEventAt:null,eventTypes:{},categories:{}});current.guildName=event.guildName||current.guildName;current.eventCount=Number(current.eventCount||0)+1;current.lastEventAt=event.timestamp;current.eventTypes||={};current.categories||={};increment(current.eventTypes,event.type||'unknown');increment(current.categories,event.category||'system');writeJson(file,current);}
function updateIdentity(current,user,event){if(!user)return;current.bot=user.bot??current.bot??null;current.accountCreatedAt=user.createdAt||current.accountCreatedAt||null;if(user.username)current.names=pushUnique(current.names,user.username,v=>String(v).toLowerCase(),25);if(user.globalName)current.globalNames=pushUnique(current.globalNames,user.globalName,v=>String(v).toLowerCase(),25);if(user.displayName)current.displayNames=pushUnique(current.displayNames,user.displayName,v=>String(v).toLowerCase(),25);if(user.nickname)current.nicknames=pushUnique(current.nicknames,{guildId:event.guildId||null,guildName:event.guildName||null,nickname:user.nickname,observedAt:event.timestamp},e=>`${e.guildId}:${String(e.nickname).toLowerCase()}`,100);}
function updateMembershipHistory(current,event,user){if(event.relation==='actor')return;const type=String(event.type||'');if(type==='member.join')current.joinHistory=pushUnique(current.joinHistory,{guildId:event.guildId,guildName:event.guildName,joinedAt:event.timestamp,eventId:event.eventId},e=>e.eventId||`${e.guildId}:${e.joinedAt}`);if(type==='member.leave'||type==='member.kick'||type==='member.ban')current.leaveHistory=pushUnique(current.leaveHistory,{guildId:event.guildId,guildName:event.guildName,leftAt:event.timestamp,type,eventId:event.eventId},e=>e.eventId||`${e.guildId}:${e.leftAt}:${e.type}`);if(event.guildId){current.guilds||={};const g=current.guilds[event.guildId]||{guildId:event.guildId,guildName:event.guildName||null,firstObservedAt:event.timestamp,lastObservedAt:null,eventCount:0,eventTypes:{}};g.guildName=event.guildName||g.guildName;g.lastObservedAt=event.timestamp;g.eventCount=Number(g.eventCount||0)+1;g.eventTypes||={};increment(g.eventTypes,type||'unknown');current.guilds[event.guildId]=g;}}
function updateRoleHistory(current,event){if(event.relation==='actor'||!/^member\.(roles|role|update)/.test(String(event.type||'')))return;current.roleHistory=pushUnique(current.roleHistory,{guildId:event.guildId,guildName:event.guildName,timestamp:event.timestamp,type:event.type,before:event.before||null,after:event.after||null,eventId:event.eventId},e=>e.eventId||`${e.guildId}:${e.timestamp}:${e.type}`);}
function updateModerationHistory(current,event){if(event.relation==='actor')return;if(event.category!=='moderation'&&!/^member\.(ban|unban|kick|timeout|prune)/.test(String(event.type||'')))return;current.moderationHistory=pushUnique(current.moderationHistory,{guildId:event.guildId,guildName:event.guildName,timestamp:event.timestamp,type:event.type,title:event.title||null,actorId:event.actor?.id||null,actorName:event.actor?.globalName||event.actor?.username||null,reason:event.reason||null,before:event.before||null,after:event.after||null,eventId:event.eventId},e=>e.eventId||`${e.guildId}:${e.timestamp}:${e.type}`);}
function updateVoiceHistory(current,event){if(event.relation==='actor'||event.category!=='voice')return;current.voiceHistory=pushUnique(current.voiceHistory,{guildId:event.guildId,guildName:event.guildName,timestamp:event.timestamp,type:event.type,before:event.before||null,after:event.after||null,eventId:event.eventId},e=>e.eventId||`${e.guildId}:${e.timestamp}`);}
function updateActorHistory(current,event){if(event.relation!=='actor')return;current.actorHistory=pushUnique(current.actorHistory,{guildId:event.guildId,guildName:event.guildName,timestamp:event.timestamp,type:event.type||'unknown',category:event.category||'system',action:event.action||'observe',title:event.title||event.type||'Audit Event',target:event.target||(event.user?.id?{id:event.user.id,label:event.user.globalName||event.user.username||event.user.id}:null),channelId:event.channel?.id||null,channelName:event.channel?.name||null,reason:event.reason||null,source:event.source||null,result:event.result||null,actorSnapshot:event.actor||null,auditLogId:event.metadata?.auditLog?.auditLogId||null,operationId:event.metadata?.operation?.operationId||null,eventId:event.eventId||null},e=>e.eventId||`${e.guildId}:${e.timestamp}:${e.type}`,HISTORY_LIMIT);}
function updateActorHistoryOnly(userId,event){const file=path.join(root,'users',`${userId}.json`),current=readJson(file,null);if(!current)return updateUserIndex(userId,{...event,relation:'actor'});current.actorHistory||=[];current.relations||={subject:0,actor:0};increment(current.relations,'actor');current.lastObservedAt=event.timestamp||current.lastObservedAt||null;updateActorHistory(current,{...event,relation:'actor'});writeJson(file,current);}
function updateUserIndex(userId,event){const file=path.join(root,'users',`${userId}.json`),current=readJson(file,{userId,firstObservedAt:event.timestamp,lastObservedAt:null,eventCount:0,names:[],globalNames:[],displayNames:[],nicknames:[],guilds:{},eventTypes:{},categories:{},relations:{subject:0,actor:0},joinHistory:[],leaveHistory:[],roleHistory:[],moderationHistory:[],voiceHistory:[],actorHistory:[],recentEvents:[]});const user=event.user?.id===userId?event.user:event.actor?.id===userId?event.actor:null;current.firstObservedAt||=event.timestamp;current.lastObservedAt=event.timestamp;current.eventCount=Number(current.eventCount||0)+1;current.eventTypes||={};current.categories||={};current.relations||={subject:0,actor:0};current.actorHistory||=[];increment(current.eventTypes,event.type||'unknown');increment(current.categories,event.category||'system');increment(current.relations,event.relation==='actor'?'actor':'subject');updateIdentity(current,user,event);updateMembershipHistory(current,event,user);updateRoleHistory(current,event);updateModerationHistory(current,event);updateVoiceHistory(current,event);updateActorHistory(current,event);current.recentEvents=pushUnique(current.recentEvents,eventSummary(event),e=>e.eventId||`${e.timestamp}:${e.type}`,50);writeJson(file,current);}
function getUser(userId){return readJson(path.join(root,'users',`${String(userId)}.json`),null);} function modeAuditRoot(mode){const normalized=String(mode||'').toUpperCase();if(normalized===runtimeMode())return root;const folder=normalized==='PRODUCTION'?'production':normalized.toLowerCase();return path.join(SHARED_ROOT,folder,'src','runtime',folder,'data','audit');} function availableAuditRoots(){const roots=[];for(const mode of REGISTRY_MODES){const candidate=modeAuditRoot(mode);if(fs.existsSync(candidate))roots.push({mode,root:candidate});}if(!roots.some(i=>i.root===root)&&fs.existsSync(root))roots.push({mode:runtimeMode(),root});return roots;}
function readGuildEventsAt(base,guildId,limit=100){const dir=path.join(base,'events',String(guildId||''));if(!guildId||!fs.existsSync(dir))return[];const files=fs.readdirSync(dir).filter(n=>/^\d{4}-\d{2}\.jsonl$/.test(n)).sort().reverse(),found=[];for(const name of files){const lines=fs.readFileSync(path.join(dir,name),'utf8').split(/\r?\n/).filter(Boolean).reverse();for(const line of lines){try{found.push(JSON.parse(line));}catch{}if(found.length>=limit)return found;}}return found;}
function getGuildAcrossModes(guildId,options={}){const id=String(guildId||'');if(!id)return null;const limit=Math.min(500,Math.max(1,Number(options.limit||100))),environments={},events=[];let merged=null;for(const item of availableAuditRoots()){const record=readJson(path.join(item.root,'guilds',`${id}.json`),null);const modeEvents=readGuildEventsAt(item.root,id,limit);if(!record&&!modeEvents.length)continue;const last=record?.lastEventAt||modeEvents[0]?.timestamp||null;environments[item.mode]={eventCount:Number(record?.eventCount||0),lastEventAt:last,observedTypes:Object.keys(record?.eventTypes||{}).length};if(record){merged||={guildId:id,guildName:record.guildName||id,firstObservedAt:record.firstObservedAt||null,lastEventAt:null,eventCount:0,eventTypes:{},categories:{}};merged.guildName=record.guildName||merged.guildName;merged.eventCount+=Number(record.eventCount||0);for(const[k,v]of Object.entries(record.eventTypes||{}))merged.eventTypes[k]=Number(merged.eventTypes[k]||0)+Number(v||0);for(const[k,v]of Object.entries(record.categories||{}))merged.categories[k]=Number(merged.categories[k]||0)+Number(v||0);if(record.lastEventAt&&(!merged.lastEventAt||record.lastEventAt>merged.lastEventAt))merged.lastEventAt=record.lastEventAt;}for(const event of modeEvents)events.push({...event,_sentinelEnvironment:item.mode});}
if(!merged&&!events.length)return null;events.sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));return{...(merged||{guildId:id,guildName:id,eventCount:events.length,eventTypes:{},categories:{},lastEventAt:events[0]?.timestamp||null}),environments,events:events.slice(0,limit)};}
function mergeCountMap(target,source){for(const[k,v]of Object.entries(source||{}))target[k]=Number(target[k]||0)+Number(v||0);return target;} function mergeUniqueArray(target,source,keyFn,limit=HISTORY_LIMIT){const map=new Map();for(const item of[...(target||[]),...(source||[])]){if(item==null)continue;const key=keyFn(item);if(key)map.set(key,item);}return[...map.values()].sort((a,b)=>String(a?.timestamp||a?.observedAt||a?.joinedAt||a?.leftAt||'').localeCompare(String(b?.timestamp||b?.observedAt||b?.joinedAt||b?.leftAt||''))).slice(-limit);}
function mergeGuildMembership(target,source){const next={...(target||{})};for(const[guildId,guild]of Object.entries(source||{})){const current=next[guildId]||{},cl=String(current.lastObservedAt||''),il=String(guild.lastObservedAt||'');next[guildId]={...current,...guild,firstObservedAt:[current.firstObservedAt,guild.firstObservedAt].filter(Boolean).sort()[0]||null,lastObservedAt:cl>il?current.lastObservedAt:guild.lastObservedAt||current.lastObservedAt||null,eventCount:Number(current.eventCount||0)+Number(guild.eventCount||0),joinCount:Number(current.joinCount||0)+Number(guild.joinCount||0),leaveCount:Number(current.leaveCount||0)+Number(guild.leaveCount||0),eventTypes:mergeCountMap({...current.eventTypes},guild.eventTypes||{})};}return next;}
function getUserAcrossModes(userId){const id=String(userId||'');if(!id)return null;let merged=null;const environments={};for(const item of availableAuditRoots()){const record=readJson(path.join(item.root,'users',`${id}.json`),null);if(!record)continue;environments[item.mode]={firstObservedAt:record.firstObservedAt||null,lastObservedAt:record.lastObservedAt||null,eventCount:Number(record.eventCount||0)};if(!merged)merged={userId:id,firstObservedAt:record.firstObservedAt||null,lastObservedAt:record.lastObservedAt||null,eventCount:0,names:[],globalNames:[],displayNames:[],nicknames:[],guilds:{},eventTypes:{},categories:{},relations:{subject:0,actor:0},joinHistory:[],leaveHistory:[],roleHistory:[],moderationHistory:[],voiceHistory:[],actorHistory:[],recentEvents:[]};merged.firstObservedAt=[merged.firstObservedAt,record.firstObservedAt].filter(Boolean).sort()[0]||null;if(record.lastObservedAt&&(!merged.lastObservedAt||record.lastObservedAt>merged.lastObservedAt))merged.lastObservedAt=record.lastObservedAt;merged.eventCount+=Number(record.eventCount||0);merged.names=mergeUniqueArray(merged.names,record.names,v=>String(v).toLowerCase(),25);merged.globalNames=mergeUniqueArray(merged.globalNames,record.globalNames,v=>String(v).toLowerCase(),25);merged.displayNames=mergeUniqueArray(merged.displayNames,record.displayNames,v=>String(v).toLowerCase(),25);merged.nicknames=mergeUniqueArray(merged.nicknames,record.nicknames,e=>`${e.guildId||''}:${String(e.nickname||'').toLowerCase()}`,100);merged.guilds=mergeGuildMembership(merged.guilds,record.guilds);mergeCountMap(merged.eventTypes,record.eventTypes);mergeCountMap(merged.categories,record.categories);mergeCountMap(merged.relations,record.relations);for(const key of['joinHistory','leaveHistory','roleHistory','moderationHistory','voiceHistory','actorHistory','recentEvents'])merged[key]=mergeUniqueArray(merged[key],record[key],e=>e.eventId||`${e.guildId}:${e.timestamp||e.joinedAt||e.leftAt}:${e.type||''}`,100);if(record.bot!=null)merged.bot=record.bot;if(record.accountCreatedAt&&!merged.accountCreatedAt)merged.accountCreatedAt=record.accountCreatedAt;}if(!merged)return null;merged.environments=environments;return merged;}
function searchIdentityValues(userId,record){const values=[{value:userId,kind:'id',weight:100}];for(const value of record.names||[])values.push({value,kind:'username',weight:50});for(const value of record.globalNames||[])values.push({value,kind:'globalName',weight:60});for(const value of record.displayNames||[])values.push({value,kind:'displayName',weight:70});for(const entry of record.nicknames||[])if(entry?.nickname)values.push({value:entry.nickname,kind:'nickname',weight:40});return values.filter(e=>e.value!=null&&String(e.value).trim());}
function identityMatchScore(value,c){const n=String(c?.value||'').trim().toLowerCase(),w=Number(c?.weight||0);if(!n)return 0;if(n===value)return 1000+w;if(n.startsWith(value))return 700+w;if(n.includes(value))return 400+w;return 0;} function identityMatchKindLabel(kind){return({id:'ID',username:'username',globalName:'global name',displayName:'display name',nickname:'nickname'})[kind]||String(kind||'identity');}
function searchUsersAcrossModes(query,options={}){const value=String(query||'').trim().toLowerCase();if(!value)return[];const limit=Math.min(25,Math.max(1,Number(options.limit||25))),guildId=options.guildId?String(options.guildId):null,found=new Map();for(const item of availableAuditRoots()){const dir=path.join(item.root,'users');if(!fs.existsSync(dir))continue;for(const name of fs.readdirSync(dir).filter(f=>f.endsWith('.json'))){const userId=name.slice(0,-5),record=readJson(path.join(dir,name),null);if(!record||(guildId&&!record.guilds?.[guildId]))continue;const matches=searchIdentityValues(userId,record).map(c=>({...c,score:identityMatchScore(value,c)})).filter(c=>c.score>0).sort((a,b)=>b.score-a.score);if(!matches.length)continue;const best=matches[0],latest=record.displayNames?.at?.(-1)||record.globalNames?.at?.(-1)||record.names?.at?.(-1)||userId,current=found.get(userId)||{id:userId,label:latest,environments:new Set(),score:0,matchedOn:null,matchedValue:null,lastObservedAt:null};current.environments.add(item.mode);if(best.score>current.score){current.score=best.score;current.matchedOn=best.kind;current.matchedValue=String(best.value);}if(record.lastObservedAt&&(!current.lastObservedAt||record.lastObservedAt>current.lastObservedAt)){current.lastObservedAt=record.lastObservedAt;current.label=latest;}found.set(userId,current);}}return[...found.values()].sort((a,b)=>b.score-a.score||b.environments.size-a.environments.size||String(b.lastObservedAt||'').localeCompare(String(a.lastObservedAt||''))).slice(0,limit).map(e=>({id:e.id,label:e.matchedOn&&e.matchedValue?`${String(e.label||e.id).slice(0,45)} • matched ${identityMatchKindLabel(e.matchedOn)}: ${String(e.matchedValue).slice(0,35)}`:e.label,environments:REGISTRY_MODES.filter(m=>e.environments.has(m)),matchedOn:e.matchedOn,matchedValue:e.matchedValue}));}
function getGuild(guildId){return readJson(path.join(root,'guilds',`${String(guildId)}.json`),null);} function getGuildEvents(guildId,options={}){const events=readGuildEventsAt(root,guildId,Math.min(100,Math.max(1,Number(options.limit||25))));const category=options.category?String(options.category):null,prefix=options.typePrefix?String(options.typePrefix):null;return events.filter(e=>(!category||String(e.category||'system')===category)&&(!prefix||String(e.type||'').startsWith(prefix))).slice(0,Math.min(100,Math.max(1,Number(options.limit||25))));} function getRoot(){return root;} function getControlConfigPath(){return SHARED_CONFIG_FILE;}
module.exports={appendEvent,getUser,getUserAcrossModes,searchUsersAcrossModes,getGuild,getGuildAcrossModes,getGuildEvents,getRoot,getControlConfigPath,getConfig,saveConfig,updateConfig,publishGuildRegistry,getGuildRegistry,runtimeMode,createLiveProbeRequest,getLiveProbeRequest,getPendingLiveProbeRequests,claimLiveProbeRequest,completeLiveProbeRequest,failLiveProbeRequest,refreshLiveProbeLifecycle,createRemoteCommand,getRemoteCommand,getPendingRemoteCommands,claimRemoteCommand,finishRemoteCommand};
