'use strict';

const decisioning = require('./memberDecisioning');
const SECURITY_STEPS = Object.freeze({accountAge:'account_age',screening:'discord_screening',challenge:'one_time_challenge',staffApproval:'staff_approval',rejoinHistory:'rejoin_history',riskBased:'risk_based',captcha:'captcha',minigame:'minigame'});
const unique=(values=[])=>[...new Set(values.filter(Boolean))];
function configuredExtraSecurity(settings,level){const security=settings.security||{},config=security.riskConfig||{};const raw=level==='high'?config.highExtraSecurity:config.mediumExtraSecurity;return unique((Array.isArray(raw)?raw:[]).filter(step=>Object.values(SECURITY_STEPS).includes(step)));}
function elevatedSecuritySteps(decision,settings={},context={}){const security=settings.security||{},level=['clear','review','high'].includes(decision?.decision)?decision.decision:'clear',reasons=Array.isArray(decision?.reasons)?decision.reasons:[],rejoinSignal=reasons.some(reason=>/join|rejoin/i.test(String(reason))),steps=[];if(rejoinSignal&&security.rejoinHistory===true)steps.push(SECURITY_STEPS.rejoinHistory);if(level!=='clear'&&security.riskBased===true)steps.push(SECURITY_STEPS.riskBased);if(level==='review'||level==='high'){if(security.accountAge===true)steps.push(SECURITY_STEPS.accountAge);if(security.discordScreening===true)steps.push(SECURITY_STEPS.screening);if(security.oneTimeChallenge===true)steps.push(SECURITY_STEPS.challenge);steps.push(...configuredExtraSecurity(settings,level));}if(level==='high'&&security.staffApproval===true)steps.push(SECURITY_STEPS.staffApproval);if(context.raidPressure===true&&settings.raid?.elevateSecurity!==false){if(security.riskBased===true)steps.push(SECURITY_STEPS.riskBased);steps.push(...configuredExtraSecurity(settings,'high'));if(security.staffApproval===true)steps.push(SECURITY_STEPS.staffApproval);}return unique(steps);}
function resolveRequiredSecurity(guildId,userId,baseSteps=[],settings={},context={}){const decision=decisioning.getDecision(guildId,userId);const elevated=elevatedSecuritySteps(decision,settings,context);return{steps:unique([...baseSteps,...elevated]),decision:decision||null,elevated};}
module.exports={SECURITY_STEPS,elevatedSecuritySteps,resolveRequiredSecurity};
