'use strict';

const { EmbedBuilder, Events } = require('discord.js');
const auditStore = require('../../owner/auditIntelligence/auditStore');
const auditRouter = require('../../owner/auditIntelligence/auditRouter');

const snapshots = new Map();
const MAX_SNAPSHOTS = 10000;
const MAX_CONTENT = 3900;

function trim(text, max = MAX_CONTENT) { const value = String(text ?? ''); return value.length > max ? `${value.slice(0, max - 1)}…` : value; }
function iso(value) { try { return value?.toISOString?.() || null; } catch { return null; } }
function author(message) { const user = message?.author; const member = message?.member; return { id:user?.id || null, username:user?.username || null, globalName:user?.globalName || null, displayName:member?.displayName || user?.globalName || user?.username || null, tag:user?.tag || null, avatarUrl:user?.displayAvatarURL?.({ size:128 }) || null, bot:Boolean(user?.bot) }; }
function attachment(item) { return { id:item.id, name:item.name || 'attachment', url:item.url || null, proxyURL:item.proxyURL || null, contentType:item.contentType || null, size:item.size ?? null, width:item.width ?? null, height:item.height ?? null, description:item.description || null, spoiler:Boolean(item.spoiler) }; }
function embedSnapshot(embed) { const data=embed?.data || embed || {}; return { title:data.title || null, description:data.description || null, url:data.url || null, color:data.color ?? null, fields:Array.isArray(data.fields)?data.fields.map(f=>({name:f.name,value:f.value,inline:Boolean(f.inline)})):[], image:data.image?.url || null, thumbnail:data.thumbnail?.url || null, author:data.author?.name || null, footer:data.footer?.text || null }; }
function sticker(item) { return { id:item.id, name:item.name || null, description:item.description || null, format:item.format ?? null, url:item.url || null }; }
function reaction(item) { return { emoji:item.emoji?.id ? `<:${item.emoji.name}:${item.emoji.id}>` : item.emoji?.name || null, count:item.count ?? 0, me:Boolean(item.me) }; }
function snapshot(message) { if(!message)return null; return { id:message.id, content:message.content ?? '', cleanContent:message.cleanContent ?? message.content ?? '', author:author(message), channelId:message.channelId || null, channelName:message.channel?.name || null, categoryId:message.channel?.parentId || null, categoryName:message.channel?.parent?.name || null, guildId:message.guildId || message.guild?.id || null, guildName:message.guild?.name || null, createdAt:iso(message.createdAt), editedAt:iso(message.editedAt), pinned:Boolean(message.pinned), tts:Boolean(message.tts), type:message.type ?? null, system:Boolean(message.system), webhookId:message.webhookId || null, reference:message.reference ? { messageId:message.reference.messageId || null, channelId:message.reference.channelId || null, guildId:message.reference.guildId || null } : null, attachments:[...(message.attachments?.values?.() || [])].map(attachment), embeds:(message.embeds || []).map(embedSnapshot), stickers:[...(message.stickers?.values?.() || [])].map(sticker), reactions:[...(message.reactions?.cache?.values?.() || [])].map(reaction), jumpURL:message.url || null }; }
function remember(state) { if(!state?.id)return; snapshots.set(state.id,state); while(snapshots.size>MAX_SNAPSHOTS)snapshots.delete(snapshots.keys().next().value); }
function routeEnabled(guildId) { const cfg=auditStore.getConfig().guilds?.[String(guildId)] || {}; return cfg.enabled !== false && cfg.monitoring?.messages !== false; }
function identity(state) { const a=state?.author || {}; return a.id ? `**${a.displayName || a.globalName || a.username || 'Unknown'}** • @${a.username || 'unknown'} • <@${a.id}> • \`${a.id}\`` : '**Unknown author**'; }
function location(state) { return `${state?.categoryName ? `**${state.categoryName}** → ` : ''}${state?.channelId ? `<#${state.channelId}>` : `#${state?.channelName || 'unknown'}`}`; }
function attachmentLines(state) { return (state?.attachments || []).map((a,i)=>`${i+1}. **${trim(a.name,120)}**${a.contentType?` • ${a.contentType}`:''}${Number.isFinite(a.size)?` • ${Math.ceil(a.size/1024)} KB`:''}${a.url?`\n${a.url}`:''}`).join('\n\n'); }
function embedLines(state) { return (state?.embeds || []).map((e,i)=>`**Embed ${i+1}${e.title?` • ${trim(e.title,100)}`:''}**${e.description?`\n${trim(e.description,500)}`:''}${e.url?`\n${e.url}`:''}`).join('\n\n'); }
function stickerLines(state) { return (state?.stickers || []).map(s=>`**${s.name || 'Sticker'}**${s.url?` • ${s.url}`:''}`).join('\n'); }
function common(embed,state) { embed.addFields({name:'Who Said It',value:identity(state),inline:false},{name:'Where',value:location(state),inline:true},{name:'Message ID',value:`\`${state?.id || 'unknown'}\``,inline:true}); if(state?.reference?.messageId)embed.addFields({name:'Reply / Reference',value:`Message \`${state.reference.messageId}\`${state.reference.channelId?` in <#${state.reference.channelId}>`:''}`}); if(state?.jumpURL)embed.addFields({name:'Original Message',value:state.jumpURL}); if(state?.attachments?.length)embed.addFields({name:`Attachments (${state.attachments.length})`,value:trim(attachmentLines(state),1024)}); if(state?.embeds?.length)embed.addFields({name:`Embedded Content (${state.embeds.length})`,value:trim(embedLines(state),1024)}); if(state?.stickers?.length)embed.addFields({name:`Stickers (${state.stickers.length})`,value:trim(stickerLines(state),1024)}); const image=state?.attachments?.find(a=>String(a.contentType||'').startsWith('image/') && a.url); if(image)embed.setImage(image.url); if(state?.author?.avatarUrl)embed.setAuthor({name:state.author.displayName || state.author.username || 'Unknown author',iconURL:state.author.avatarUrl}); return embed; }
function words(text) { return String(text ?? '').split(/(\s+)/); }
function diff(before,after) { const a=words(before),b=words(after); let start=0; while(start<a.length&&start<b.length&&a[start]===b[start])start++; let ae=a.length-1,be=b.length-1; while(ae>=start&&be>=start&&a[ae]===b[be]){ae--;be--;} const oldText=a.slice(start,ae+1).join('') || '(nothing)'; const newText=b.slice(start,be+1).join('') || '(nothing)'; return { oldText:trim(oldText,900), newText:trim(newText,900) }; }
async function destination(client,message) { if(!message?.guild || !routeEnabled(message.guild.id))return null; return auditRouter.configuredRouteChannel(client,message.guild,{type:'message.fidelity',category:'message'}).catch(()=>null); }
async function send(client,message,embed) { const channel=await destination(client,message); if(!channel?.isTextBased?.())return false; return Boolean(await channel.send({embeds:[embed],allowedMentions:{parse:[]}}).catch(e=>{console.warn('[Sentinel Message Fidelity] mirror failed:',e?.message||e);return null;})); }
async function created(client,message) { if(!message?.guild || message.author?.bot)return; const state=snapshot(message); remember(state); const e=common(new EmbedBuilder().setColor(0x57F287).setTitle('💬 Message Sent').setDescription(trim(state.content || '*No text content — see attachments/embeds/stickers below.*')),state).setFooter({text:`Sentinel CCTV • ${String(process.env.BOT_MODE||'DEV').toUpperCase()} • exact observed message snapshot`}).setTimestamp(message.createdAt || new Date()); await send(client,message,e); }
async function updated(client,before,after) { if(!after?.guild || after.author?.bot)return; const oldState=snapshots.get(after.id) || snapshot(before),newState=snapshot(after); remember(newState); if(!oldState)return; const change=diff(oldState.content,newState.content); const e=common(new EmbedBuilder().setColor(0xFEE75C).setTitle('✏️ Message Edited').setDescription('Sentinel retained both observed revisions.').addFields({name:'Before — Exact Text',value:trim(oldState.content || '*No text content*',1024)},{name:'After — Exact Text',value:trim(newState.content || '*No text content*',1024)},{name:'Highlighted Change',value:`🔴 **Removed / replaced**\n${change.oldText}\n\n🟢 **Added / replacement**\n${change.newText}`}),newState).setFooter({text:`Sentinel CCTV • ${String(process.env.BOT_MODE||'DEV').toUpperCase()} • revision evidence retained`}).setTimestamp(after.editedAt || new Date()); await send(client,after,e); }
async function deleted(client,message) { if(!message?.guild || message.author?.bot)return; const state=snapshots.get(message.id) || snapshot(message); snapshots.delete(message.id); const e=common(new EmbedBuilder().setColor(0xED4245).setTitle('🗑️ Message Deleted').setDescription(trim(state?.content || '*No text content was available to Goliath at deletion time.*')),state).addFields({name:'Who Deleted It',value:'**Pending Discord Audit Log correlation.** If Discord exposes an executor, the normal Sentinel moderation/audit evidence will identify them; otherwise Sentinel will not guess.'}).setFooter({text:`Sentinel CCTV • ${String(process.env.BOT_MODE||'DEV').toUpperCase()} • deleted message evidence`}).setTimestamp(new Date()); await send(client,message,e); }
async function reactionEvent(client,reaction,user,action) { const message=reaction?.message;if(!message?.guild || user?.bot)return; const state=snapshot(message); const emoji=reaction.emoji?.id?`<:${reaction.emoji.name}:${reaction.emoji.id}>`:reaction.emoji?.name || 'reaction'; const e=common(new EmbedBuilder().setColor(0x5865F2).setTitle(action==='add'?'➕ Reaction Added':'➖ Reaction Removed').setDescription(`<@${user.id}> ${action==='add'?'reacted with':'removed'} **${emoji}**`).addFields({name:'Message Text',value:trim(state.content || '*No text content*',1024)}),state).setFooter({text:`Sentinel CCTV • ${String(process.env.BOT_MODE||'DEV').toUpperCase()} • reaction evidence`}).setTimestamp(); await send(client,message,e); }
module.exports={name:Events.ClientReady,once:true,async execute(client){client.on(Events.MessageCreate,m=>created(client,m).catch(e=>console.warn('[Sentinel Message Fidelity] create:',e?.message||e)));client.on(Events.MessageUpdate,(b,a)=>updated(client,b,a).catch(e=>console.warn('[Sentinel Message Fidelity] update:',e?.message||e)));client.on(Events.MessageDelete,m=>deleted(client,m).catch(e=>console.warn('[Sentinel Message Fidelity] delete:',e?.message||e)));client.on(Events.MessageReactionAdd,(r,u)=>reactionEvent(client,r,u,'add').catch(()=>null));client.on(Events.MessageReactionRemove,(r,u)=>reactionEvent(client,r,u,'remove').catch(()=>null));console.log('[Sentinel Message Fidelity] Exact-message CCTV mirror online.');}};
