'use strict';

const { AuditLogEvent, EmbedBuilder, Events, PermissionsBitField } = require('discord.js');
const auditRouter = require('../../owner/auditIntelligence/auditRouter');
const auditStore = require('../../owner/auditIntelligence/auditStore');

const recent = new Map();
const DEDUPE_MS = 5000;
const AUDIT_WINDOW_MS = 15000;
const trim=(v,n=1024)=>{const s=String(v??'');return s.length>n?`${s.slice(0,n-1)}…`:s;};
function enabled(guildId,family='moderation'){const c=auditStore.getConfig().guilds?.[String(guildId)]||{};return c.enabled!==false&&c.monitoring?.[family]!==false;}
function key(type,guildId,targetId){return`${type}:${guildId}:${targetId||'none'}`;}
function duplicate(type,guildId,targetId){const k=key(type,guildId,targetId),now=Date.now(),last=recent.get(k)||0;recent.set(k,now);for(const[x,t]of recent)if(now-t>60000)recent.delete(x);return now-last<DEDUPE_MS;}
function userLabel(u){if(!u)return'Unknown / Discord did not expose an actor';return`**${u.globalName||u.username||u.tag||'Unknown'}**\n@${u.username||'unknown'} • <@${u.id}> • \`${u.id}\``;}
function memberLabel(m){const u=m?.user||m;if(!u?.id)return'Unknown member';return`**${m?.displayName||u.globalName||u.username||'Unknown'}**\n@${u.username||'unknown'} • <@${u.id}> • \`${u.id}\``;}
function roles(m){return m?.roles?.cache?[...m.roles.cache.values()].filter(r=>r.id!==m.guild.id).sort((a,b)=>b.position-a.position).map(r=>`<@&${r.id}>`).join(' ')||'*No guild roles*':'*Role snapshot unavailable*';}
function channelLabel(ch){return ch?.id?`${ch.parent?.name?`**${ch.parent.name}** → `:''}<#${ch.id}>`:'Unknown channel';}
function permNames(bits){try{return new PermissionsBitField(BigInt(bits||0)).toArray();}catch{return[];}}
function permissionDiff(before,after){const b=new Set(permNames(before)),a=new Set(permNames(after)),added=[...a].filter(x=>!b.has(x)),removed=[...b].filter(x=>!a.has(x));const rows=[];for(const x of added)rows.push(`🟢 **${x}** — added`);for(const x of removed)rows.push(`🔴 **${x}** — removed`);return rows.join('\n')||'No named permission bit changed.';}
function overwriteMap(ch){const map=new Map();for(const o of ch?.permissionOverwrites?.cache?.values?.()||[])map.set(o.id,{id:o.id,type:o.type,allow:o.allow.bitfield,deny:o.deny.bitfield});return map;}
function overwriteDiff(before,after){const b=overwriteMap(before),a=overwriteMap(after),ids=new Set([...b.keys(),...a.keys()]),rows=[];for(const id of ids){const x=b.get(id),y=a.get(id);if(!x&&y){rows.push(`🟢 <@&${id}> overwrite added`);continue;}if(x&&!y){rows.push(`🔴 <@&${id}> overwrite removed`);continue;}if(x.allow!==y.allow){const d=permissionDiff(x.allow,y.allow);if(d!=='No named permission bit changed.')rows.push(`**<@&${id}> allowed**\n${d}`);}if(x.deny!==y.deny){const old=permNames(x.deny),now=permNames(y.deny),oldSet=new Set(old),nowSet=new Set(now);for(const p of now)if(!oldSet.has(p))rows.push(`🔴 **<@&${id}> ${p}** — explicitly denied`);for(const p of old)if(!nowSet.has(p))rows.push(`🟢 **<@&${id}> ${p}** — deny removed`);}}return trim(rows.join('\n')||'No permission overwrite difference was available.',1024);}
async function auditActor(guild,type,targetId){if(!guild?.members?.me?.permissions?.has?.('ViewAuditLog'))return{actor:null,reason:null,id:null,status:'Goliath lacks View Audit Log'};try{const logs=await guild.fetchAuditLogs({type,limit:6});const now=Date.now();const entry=[...logs.entries.values()].find(x=>{const at=x.createdTimestamp||0,target=x.target?.id||x.targetId||null;return now-at<=AUDIT_WINDOW_MS&&(!targetId||String(target)===String(targetId));});if(!entry)return{actor:null,reason:null,id:null,status:'Discord did not expose a matching Audit Log entry'};return{actor:entry.executor||null,reason:entry.reason||null,id:entry.id,status:'Confirmed by Discord Audit Log'};}catch{return{actor:null,reason:null,id:null,status:'Audit Log lookup failed'};}}
async function destinations(client,guild,event,user){const out=[];const route=await auditRouter.configuredRouteChannel(client,guild,event).catch(()=>null);if(route?.isTextBased?.())out.push(route);if(user?.id){const userCh=await auditRouter.ensureUserAuditChannel(client,guild,{user}).catch(()=>null);if(userCh?.isTextBased?.()&&!out.some(c=>c.id===userCh.id))out.push(userCh);}return out;}
async function send(client,guild,event,user,embed){for(const ch of await destinations(client,guild,event,user))await ch.send({embeds:[embed],allowedMentions:{parse:[]}}).catch(e=>console.warn('[Sentinel Moderation Fidelity]',e?.message||e));}
function base(title,color,guild,target,actorInfo){const e=new EmbedBuilder().setColor(color).setTitle(title).addFields({name:'Server',value:`**${guild.name}**\n\`${guild.id}\``,inline:true},{name:'Affected Person / Target',value:target||'Unknown',inline:true},{name:'Who Performed It',value:userLabel(actorInfo?.actor),inline:false},{name:'Attribution',value:`${actorInfo?.status||'Not available'}${actorInfo?.id?`\nAudit Log ID: \`${actorInfo.id}\``:''}${actorInfo?.reason?`\nReason: **${trim(actorInfo.reason,500)}**`:''}`}).setFooter({text:'Sentinel CCTV • moderation/admin evidence • no guessed attribution'}).setTimestamp();return e;}
async function memberRemove(client,m){if(!m?.guild||!enabled(m.guild.id,'members')||duplicate('remove',m.guild.id,m.id))return;await new Promise(r=>setTimeout(r,1200));let info=await auditActor(m.guild,AuditLogEvent.MemberKick,m.id);let title='🚪 Member Left',action='Discord did not expose a moderator removal; recorded as a leave.';if(info.actor){title='🥾 Member Kicked';action='Member was removed by a moderator/admin.';}else{const ban=await auditActor(m.guild,AuditLogEvent.MemberBanAdd,m.id);if(ban.actor){info=ban;title='🔨 Member Banned';action='Member was banned and removed from the guild.';}}const e=base(title,info.actor?0xED4245:0xFEE75C,m.guild,memberLabel(m),info).addFields({name:'Roles At Last Observation',value:trim(roles(m))},{name:'What Happened',value:action});await send(client,m.guild,{type:'member.fidelity',category:info.actor?'moderation':'member'},m.user,e);}
async function banAdd(client,ban){const g=ban?.guild,u=ban?.user;if(!g||!u||!enabled(g.id,'moderation')||duplicate('ban',g.id,u.id))return;await new Promise(r=>setTimeout(r,700));const info=await auditActor(g,AuditLogEvent.MemberBanAdd,u.id),e=base('🔨 Member Banned',0xED4245,g,userLabel(u),info).addFields({name:'What Happened',value:'The member was banned from the server.'});await send(client,g,{type:'moderation.ban.fidelity',category:'moderation'},u,e);}
async function banRemove(client,ban){const g=ban?.guild,u=ban?.user;if(!g||!u||!enabled(g.id,'moderation'))return;await new Promise(r=>setTimeout(r,700));const info=await auditActor(g,AuditLogEvent.MemberBanRemove,u.id),e=base('🔓 Member Unbanned',0x57F287,g,userLabel(u),info).addFields({name:'What Happened',value:'The member ban was removed.'});await send(client,g,{type:'moderation.unban.fidelity',category:'moderation'},u,e);}
async function memberUpdate(client,b,a){if(!a?.guild||!enabled(a.guild.id,'members'))return;const roleBefore=new Set(b.roles.cache.keys()),roleAfter=new Set(a.roles.cache.keys()),added=[...roleAfter].filter(x=>!roleBefore.has(x)),removed=[...roleBefore].filter(x=>!roleAfter.has(x));const nick=b.nickname!==a.nickname,timeout=String(b.communicationDisabledUntilTimestamp||'')!==String(a.communicationDisabledUntilTimestamp||'');if(!added.length&&!removed.length&&!nick&&!timeout)return;await new Promise(r=>setTimeout(r,700));let auditType=AuditLogEvent.MemberUpdate;if(added.length||removed.length)auditType=AuditLogEvent.MemberRoleUpdate;const info=await auditActor(a.guild,auditType,a.id),changes=[];for(const id of added)changes.push(`🟢 Role added: <@&${id}>`);for(const id of removed)changes.push(`🔴 Role removed: <@&${id}>`);if(nick)changes.push(`✏️ Nickname: **${b.nickname||'None'}** → **${a.nickname||'None'}**`);if(timeout)changes.push(`⏱️ Timeout: **${b.communicationDisabledUntil?.toISOString?.()||'None'}** → **${a.communicationDisabledUntil?.toISOString?.()||'None'}**`);const e=base(timeout?'⏱️ Member Moderation Changed':'👤 Member Changed',timeout?0xED4245:0x5865F2,a.guild,memberLabel(a),info).addFields({name:'Exactly What Changed',value:trim(changes.join('\n'))},{name:'Current Roles',value:trim(roles(a))});await send(client,a.guild,{type:'member.update.fidelity',category:timeout?'moderation':'member'},a.user,e);}
async function roleUpdate(client,b,a){if(!a?.guild||!enabled(a.guild.id,'roles'))return;const changes=[];if(b.name!==a.name)changes.push(`✏️ Name: **${b.name}** → **${a.name}**`);if(b.color!==a.color)changes.push(`🎨 Colour: **${b.hexColor}** → **${a.hexColor}**`);if(b.hoist!==a.hoist)changes.push(`📌 Display separately: **${b.hoist}** → **${a.hoist}**`);if(b.mentionable!==a.mentionable)changes.push(`💬 Mentionable: **${b.mentionable}** → **${a.mentionable}**`);if(b.permissions.bitfield!==a.permissions.bitfield)changes.push(`**Permissions**\n${permissionDiff(b.permissions.bitfield,a.permissions.bitfield)}`);if(!changes.length)return;await new Promise(r=>setTimeout(r,700));const info=await auditActor(a.guild,AuditLogEvent.RoleUpdate,a.id),e=base('🛡️ Role Changed',0x5865F2,a.guild,`<@&${a.id}> • **${a.name}** • \`${a.id}\``,info).addFields({name:'Exactly What Changed',value:trim(changes.join('\n\n'))});await send(client,a.guild,{type:'role.update.fidelity',category:'role'},null,e);}
async function channelUpdate(client,b,a){if(!a?.guild||!enabled(a.guild.id,'roles'))return;const changes=[];if(b.name!==a.name)changes.push(`✏️ Name: **#${b.name}** → **#${a.name}**`);if(b.parentId!==a.parentId)changes.push(`📁 Category: ${b.parentId?`<#${b.parentId}>`:'None'} → ${a.parentId?`<#${a.parentId}>`:'None'}`);if(b.topic!==a.topic)changes.push(`📝 Topic:\n**Before:** ${trim(b.topic||'None',350)}\n**After:** ${trim(a.topic||'None',350)}`);if(b.rateLimitPerUser!==a.rateLimitPerUser)changes.push(`⏳ Slowmode: **${b.rateLimitPerUser||0}s** → **${a.rateLimitPerUser||0}s**`);const perms=overwriteDiff(b,a);if(perms!=='No permission overwrite difference was available.')changes.push(`**Permission overwrites**\n${perms}`);if(!changes.length)return;await new Promise(r=>setTimeout(r,700));const info=await auditActor(a.guild,AuditLogEvent.ChannelUpdate,a.id),e=base('⚙️ Channel Changed',0x5865F2,a.guild,channelLabel(a),info).addFields({name:'Exactly What Changed',value:trim(changes.join('\n\n'))});await send(client,a.guild,{type:'channel.update.fidelity',category:'role'},null,e);}
async function roleCreateDelete(client,r,created){if(!r?.guild||!enabled(r.guild.id,'roles'))return;await new Promise(x=>setTimeout(x,700));const info=await auditActor(r.guild,created?AuditLogEvent.RoleCreate:AuditLogEvent.RoleDelete,r.id),e=base(created?'🟢 Role Created':'🔴 Role Deleted',created?0x57F287:0xED4245,r.guild,`**${r.name}** • \`${r.id}\``,info).addFields({name:'Role Permissions',value:trim(permNames(r.permissions?.bitfield).join(', ')||'None')});await send(client,r.guild,{type:`role.${created?'create':'delete'}.fidelity`,category:'role'},null,e);}
async function channelCreateDelete(client,ch,created){if(!ch?.guild||!enabled(ch.guild.id,'guild'))return;await new Promise(x=>setTimeout(x,700));const info=await auditActor(ch.guild,created?AuditLogEvent.ChannelCreate:AuditLogEvent.ChannelDelete,ch.id),e=base(created?'🟢 Channel Created':'🔴 Channel Deleted',created?0x57F287:0xED4245,ch.guild,`**#${ch.name}** • \`${ch.id}\``,info).addFields({name:'Location',value:channelLabel(ch)},{name:'Type',value:String(ch.type)});await send(client,ch.guild,{type:`channel.${created?'create':'delete'}.fidelity`,category:'guild'},null,e);}
module.exports={name:Events.ClientReady,once:true,async execute(client){client.on(Events.GuildMemberRemove,m=>memberRemove(client,m).catch(e=>console.warn('[Sentinel Moderation Fidelity] memberRemove',e?.message||e)));client.on(Events.GuildBanAdd,b=>banAdd(client,b).catch(()=>null));client.on(Events.GuildBanRemove,b=>banRemove(client,b).catch(()=>null));client.on(Events.GuildMemberUpdate,(b,a)=>memberUpdate(client,b,a).catch(e=>console.warn('[Sentinel Moderation Fidelity] memberUpdate',e?.message||e)));client.on(Events.GuildRoleUpdate,(b,a)=>roleUpdate(client,b,a).catch(()=>null));client.on(Events.GuildRoleCreate,r=>roleCreateDelete(client,r,true).catch(()=>null));client.on(Events.GuildRoleDelete,r=>roleCreateDelete(client,r,false).catch(()=>null));client.on(Events.ChannelUpdate,(b,a)=>channelUpdate(client,b,a).catch(()=>null));client.on(Events.ChannelCreate,ch=>channelCreateDelete(client,ch,true).catch(()=>null));client.on(Events.ChannelDelete,ch=>channelCreateDelete(client,ch,false).catch(()=>null));console.log('[Sentinel Moderation Fidelity] Actor-aware moderation/permission CCTV online.');}};
