'use strict';

const { EmbedBuilder, Events } = require('discord.js');
const auditStore = require('../../owner/auditIntelligence/auditStore');
const auditRouter = require('../../owner/auditIntelligence/auditRouter');

const snapshots = new Map();
const MAX_SNAPSHOTS = 10000;
const MAX_CONTENT = 3900;
const trim=(v,n=MAX_CONTENT)=>{const s=String(v??'');return s.length>n?`${s.slice(0,n-1)}…`:s;};
const iso=v=>{try{return v?.toISOString?.()||null;}catch{return null;}};
function roles(member){return member?.roles?.cache?[...member.roles.cache.values()].filter(r=>r.id!==member.guild.id).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,position:r.position,color:r.hexColor||null})):[];}
function author(message){const u=message?.author,m=message?.member;return{id:u?.id||null,username:u?.username||null,globalName:u?.globalName||null,displayName:m?.displayName||u?.globalName||u?.username||null,tag:u?.tag||null,avatarUrl:u?.displayAvatarURL?.({size:128})||null,bot:Boolean(u?.bot),roles:roles(m)};}
function attachment(a){return{id:a.id,name:a.name||'attachment',url:a.url||null,proxyURL:a.proxyURL||null,contentType:a.contentType||null,size:a.size??null,width:a.width??null,height:a.height??null,description:a.description||null,spoiler:Boolean(a.spoiler)};}
function embedSnapshot(e){const d=e?.data||e||{};return{title:d.title||null,description:d.description||null,url:d.url||null,fields:Array.isArray(d.fields)?d.fields.map(f=>({name:f.name,value:f.value,inline:Boolean(f.inline)})):[],image:d.image?.url||null,thumbnail:d.thumbnail?.url||null,author:d.author?.name||null,footer:d.footer?.text||null};}
function snapshot(m){if(!m)return null;return{id:m.id,content:m.content??'',cleanContent:m.cleanContent??m.content??'',author:author(m),channelId:m.channelId||null,channelName:m.channel?.name||null,categoryName:m.channel?.parent?.name||null,guildId:m.guildId||m.guild?.id||null,guildName:m.guild?.name||null,createdAt:iso(m.createdAt),editedAt:iso(m.editedAt),pinned:Boolean(m.pinned),reference:m.reference?{messageId:m.reference.messageId||null,channelId:m.reference.channelId||null}:null,attachments:[...(m.attachments?.values?.()||[])].map(attachment),embeds:(m.embeds||[]).map(embedSnapshot),stickers:[...(m.stickers?.values?.()||[])].map(s=>({id:s.id,name:s.name||null,url:s.url||null})),jumpURL:m.url||null};}
function remember(s){if(!s?.id)return;snapshots.set(s.id,s);while(snapshots.size>MAX_SNAPSHOTS)snapshots.delete(snapshots.keys().next().value);}
function enabled(id){const c=auditStore.getConfig().guilds?.[String(id)]||{};return c.enabled!==false&&c.monitoring?.messages!==false;}
function roleLine(s){const list=s?.author?.roles||[];return list.length?list.map(r=>`<@&${r.id}>`).join(' '):'*No guild roles observed*';}
function identity(s){const a=s?.author||{};return a.id?`**${a.displayName||a.globalName||a.username||'Unknown'}**\n@${a.username||'unknown'} • <@${a.id}> • \`${a.id}\``:'**Unknown author**';}
function location(s){return`${s?.categoryName?`**${s.categoryName}** → `:''}${s?.channelId?`<#${s.channelId}>`:`#${s?.channelName||'unknown'}`}`;}
function attachmentLines(s){return(s?.attachments||[]).map((a,i)=>`${i+1}. **${trim(a.name,120)}**${a.contentType?` • ${a.contentType}`:''}${Number.isFinite(a.size)?` • ${Math.ceil(a.size/1024)} KB`:''}${a.url?`\n${a.url}`:''}`).join('\n\n');}
function common(e,s){e.addFields({name:'Person',value:identity(s)},{name:'Roles',value:trim(roleLine(s),1024)},{name:'Where',value:location(s),inline:true},{name:'Message ID',value:`\`${s?.id||'unknown'}\``,inline:true});if(s?.reference?.messageId)e.addFields({name:'Replying To',value:`Message \`${s.reference.messageId}\`${s.reference.channelId?` in <#${s.reference.channelId}>`:''}`});if(s?.jumpURL)e.addFields({name:'Open Original',value:s.jumpURL});if(s?.attachments?.length)e.addFields({name:`Attachments (${s.attachments.length})`,value:trim(attachmentLines(s),1024)});if(s?.embeds?.length)e.addFields({name:`Embeds (${s.embeds.length})`,value:trim(s.embeds.map((x,i)=>`**${i+1}. ${x.title||'Embed'}**${x.description?`\n${x.description}`:''}`).join('\n\n'),1024)});if(s?.stickers?.length)e.addFields({name:'Stickers',value:trim(s.stickers.map(x=>x.name||x.id).join(', '),1024)});const image=s?.attachments?.find(a=>String(a.contentType||'').startsWith('image/')&&a.url);if(image)e.setImage(image.url);if(s?.author?.avatarUrl)e.setAuthor({name:s.author.displayName||s.author.username||'Unknown author',iconURL:s.author.avatarUrl});return e;}
function words(t){return String(t??'').split(/(\s+)/);}function diff(before,after){const a=words(before),b=words(after);let start=0;while(start<a.length&&start<b.length&&a[start]===b[start])start++;let ae=a.length-1,be=b.length-1;while(ae>=start&&be>=start&&a[ae]===b[be]){ae--;be--;}return{oldText:trim(a.slice(start,ae+1).join('')||'(nothing)',900),newText:trim(b.slice(start,be+1).join('')||'(nothing)',900)};}
async function destination(client,m){if(!m?.guild||!enabled(m.guild.id))return null;return auditRouter.configuredRouteChannel(client,m.guild,{type:'message.fidelity',category:'message'}).catch(()=>null);}
async function send(client,m,e){const ch=await destination(client,m);if(!ch?.isTextBased?.())return false;return Boolean(await ch.send({embeds:[e],allowedMentions:{parse:[]}}).catch(err=>{console.warn('[Sentinel Message Fidelity]',err?.message||err);return null;}));}
async function hydrate(m){if(!m)return m;if(m.partial)await m.fetch().catch(()=>null);if(m.guild&&m.author?.id&&!m.member)m.member=await m.guild.members.fetch(m.author.id).catch(()=>null);return m;}
async function created(client,m){await hydrate(m);if(!m?.guild||m.author?.bot)return;const s=snapshot(m);remember(s);const e=common(new EmbedBuilder().setColor(0x57F287).setTitle('💬 Message Sent').addFields({name:'Exact Message',value:trim(s.content||'*No text content*',1024)}),s).setFooter({text:'Sentinel CCTV • exact observed message'}).setTimestamp(m.createdAt||new Date());await send(client,m,e);}
async function updated(client,before,after){await hydrate(after);if(!after?.guild||after.author?.bot)return;const old=snapshots.get(after.id)||snapshot(before),now=snapshot(after);remember(now);if(!old)return;const d=diff(old.content,now.content),e=common(new EmbedBuilder().setColor(0xFEE75C).setTitle('✏️ Message Edited').addFields({name:'BEFORE — exact message',value:trim(old.content||'*No text content*',1024)},{name:'AFTER — exact message',value:trim(now.content||'*No text content*',1024)},{name:'CHANGED',value:`🔴 **Removed / replaced**\n${d.oldText}\n\n🟢 **Added / replacement**\n${d.newText}`}),now).setFooter({text:'Sentinel CCTV • exact revision retained'}).setTimestamp(after.editedAt||new Date());await send(client,after,e);}
async function deleted(client,m){const s=snapshots.get(m.id)||snapshot(m);snapshots.delete(m.id);if(!m?.guild||s?.author?.bot)return;const e=common(new EmbedBuilder().setColor(0xED4245).setTitle('🗑️ Message Deleted').addFields({name:'DELETED — exact observed message',value:trim(s?.content||'*Message content was not available to Goliath*',1024)},{name:'Deleted By',value:'Pending audit-log correlation. Sentinel will identify the moderator when Discord exposes one; it will not guess.'}),s).setFooter({text:'Sentinel CCTV • deleted-message evidence'}).setTimestamp();await send(client,m,e);}
async function reactionEvent(client,r,u,action){const m=r?.message;await hydrate(m);if(!m?.guild||u?.bot)return;const s=snapshot(m),emoji=r.emoji?.id?`<:${r.emoji.name}:${r.emoji.id}>`:r.emoji?.name||'reaction';const e=common(new EmbedBuilder().setColor(0x5865F2).setTitle(action==='add'?'➕ Reaction Added':'➖ Reaction Removed').addFields({name:'Reaction By',value:`<@${u.id}> • \`${u.id}\``},{name:'Reaction',value:emoji},{name:'Exact Message',value:trim(s.content||'*No text content*',1024)}),s).setFooter({text:'Sentinel CCTV • reaction evidence'}).setTimestamp();await send(client,m,e);}
module.exports={name:Events.ClientReady,once:true,async execute(client){client.on(Events.MessageCreate,m=>created(client,m).catch(e=>console.warn('[Sentinel Message Fidelity] create',e?.message||e)));client.on(Events.MessageUpdate,(b,a)=>updated(client,b,a).catch(e=>console.warn('[Sentinel Message Fidelity] update',e?.message||e)));client.on(Events.MessageDelete,m=>deleted(client,m).catch(e=>console.warn('[Sentinel Message Fidelity] delete',e?.message||e)));client.on(Events.MessageReactionAdd,(r,u)=>reactionEvent(client,r,u,'add').catch(()=>null));client.on(Events.MessageReactionRemove,(r,u)=>reactionEvent(client,r,u,'remove').catch(()=>null));console.log('[Sentinel Message Fidelity] Exact-message + role-aware CCTV online.');}};
